### ISSUE TITLE
Differentiate pending transactions

### ISSUE THREAD

**Issue by allenan** [helium/hotspot-app#100]
In the list and details view, we need to differentiate between a pending and a cleared transaction. Right now they look the same.

The designs specify to keep them in a unified list, but to replace the timestamp with `pending`

![image](https://user-images.githubusercontent.com/792845/105079146-dfdc5680-5a43-11eb-9380-326138bb6e59.png)

![image](https://user-images.githubusercontent.com/792845/105079176-ea96eb80-5a43-11eb-8e1e-cc6ba29d2140.png)

**Comment by matthewcarlreetz** [comment]
Create pending txns for

- [ ] assert location
- [ ] add hotspot
- [ ] send payment
- [ ] burn
- [ ] transfer
