### ISSUE TITLE
New hotspots in my area not showing

### ISSUE THREAD

**Issue by taoteh1221** [helium/hotspot-app#1010]
**Describe the bug**
My hotspot and 2 other hotspots have just come online near me over the past 2 weeks in my town. They show on the web based explorer, but they do NOT show in the Android app. All these hotspots are synced, and have witnessed other beacons. Furthermore, 'discovery mode' for me has one response, but I have no idea which hotspot it was as they are no yellow hexagons on the map when viewing discovery results.

**To Reproduce**

1. Go to map in android app for a new hotspot under two weeks old, also look for NEW ACTIVE close hotspots. Compare to what the web based explorer shows.
2. Run discovery mode, check map for yellow hexagons of hotspots that responded.

**Expected behavior**
All active hotspots should show in the Android app, including in discovery mode.

**Smartphone (please complete the following information):**

- Device: moto g power (2020)
- OS: Android v11
- App Version v3.7.0

**Additional context**

**Comment by dmadole** [comment]
I had the same problems and it's half-fixed for me in 3.7.1. Now the hex that contains my hotshot does show yellow on the map, but discovery mode still does not identify which hotspot the response it received came from.

**Comment by taoteh1221** [comment]
I have the same experience @dmadole. I'm guessing from the RSSI of -28 in my results and me being the only hotspot in my hexagon, that the discovery mode is erroneously responding to itself with my 3dbi antenna. Just a guess. It would be a better user experience if responses from one's own hotspot are ignored, it's kinda confusing IMO.

**Comment by tyler-whitman** [comment]
> I had the same problems and it's half-fixed for me in 3.7.1. Now the hex that contains my hotshot does show yellow on the map, but discovery mode still does not identify which hotspot the response it received came from.

Closing this as it was related to new hotspots in the hexagons @dmadole and @taoteh1221 there are discovery mode fixes pending and it should be working properly again soon.
