### ISSUE TITLE
Wallet transaction error 

### ISSUE THREAD

**Issue by mxneyjxrdvn** [helium/hotspot-app#1012]
-After sending a first set of HNT as a test on a New external adresse, all was fine, but then I went to send more HNT days later and received this error “(invalid, duplicate_txn)” 
-Error code seems not referenced on :
https://docs.helium.com/wallets/app-wallet/transaction-failures/
-Transaction appear as confirmed on explorer and Helium app,
except for the transaction error notification displayed in the wallet that asks me to restart the transaction which implies that HNT was returned to me
-Does the HNT return to helium wallet or potentially leads to a permanent loss  ? It isn’t currently there +48hours later .

**To Reproduce**

intermittent error

- Device: [e.g. iPhone X ]
- OS: [e.g. iOS 14.6]
- App Version [e.g. 3.6.0]

**Screenshots**

![image](https://user-images.githubusercontent.com/78317722/139349393-27095725-1983-4250-9974-6a76a0e98f1c.jpeg)

![image](https://user-images.githubusercontent.com/78317722/139349400-d0f4f678-2752-4dab-abb1-a4f07c6c8480.png)

**Comment by cokes518** [comment]
is the balance correct? the wallet-api had some issues a few days ago. if the error message was queued up to when you originally sent the transaction, it might have been delivered late.

**Comment by mxneyjxrdvn** [comment]
The balance on helium app is not correct the amount sent does not appear anymore on my balance and still not received on the external wallet, I have try again with a very small amount of HNT to send on same adresse and this time it work correctly 
But still nothing regarding the failed transaction.
Thanks for your reply

**Comment by cokes518** [comment]
what's your full wallet address?

**Comment by mxneyjxrdvn** [comment]
14sAR7SUdo29fz7S7898xGbAYB1tVprVJD2s9LiT2auv66VuZd3

**Comment by cokes518** [comment]
it looks like one failed because it was sent too close to the previous transaction (same nonce value, 6)

```{
      "updated_at": "2021-10-26T17:53:39.760169Z",
      "type": "payment_v2",
      "txn": {
        "type": "payment_v2",
        "payments": [
          {
            "payee": "149wEL9JpAgNCszXr2EjnFC2RXPp6vrGnTUkFvauQ6WTP6yTjYM",
            "memo": "Z2F0AAAAAAA=",
            "amount": 2016700000
          }
        ],
        "payer": "14sAR7SUdo29fz7S7898xGbAYB1tVprVJD2s9LiT2auv66VuZd3",
        "nonce": 6,
        "hash": "8j-2A00UWMctWSqX_J8QngU6zxOyBLjRy9IJ7q_qt8E",
        "fee": 35000
      },
      "status": "failed",
      "hash": "8j-2A00UWMctWSqX_J8QngU6zxOyBLjRy9IJ7q_qt8E",
      "failed_reason": "{invalid,duplicate_txn}",
      "created_at": "2021-10-26T17:52:32.827430Z"
    },```

you can see your history of transactions here: https://api.helium.io/v1/accounts/14sAR7SUdo29fz7S7898xGbAYB1tVprVJD2s9LiT2auv66VuZd3/pending_transactions

it also checks out on the receiver side. they only got 1 payment from you on the 26th. 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/19331274/139961206-b24bf8d3-5f24-4a48-9c8b-be85bc7e5424.png">


next time, to avoid invalid transactions, avoid sending multiple at once. I also think you were caught in the api outage that happened last week.

**Comment by mxneyjxrdvn** [comment]
Got my HNT back today after lot of mail with gate.io
