### ISSUE TITLE
Can’t transfer hotspot

### ISSUE THREAD

**Issue by smarthousetips** [helium/hotspot-app#1017]
**Describe the bug**
Button is greyed out when trying to transfer hotspot after putting in the address and payment. 

**To Reproduce**

1. Go to settings
2. Click on transfer hotspot 
3. Enter in wallet and ‘0’ for the price
4. Button is greyed out 

Cannot complete transfer or initiate it. 

- Device: iPhone 13 Pro
- OS: iOS 15.1
- App Version: 3.7.1

**Additional context**

**Comment by cokes518** [comment]
Try signing out and signing back in. Make sure you have your 12 words written down correctly and in the right order.

**Comment by b-spillman** [comment]
I am having the same issue. I deleted the app and updated to the latest version and the button is not working properly. It is staying greyed out.
![20211030_153949-IOS](https://user-images.githubusercontent.com/54695026/139599247-8fc8a085-b9ca-4fad-a262-dd9c0d50637d.png)

**Comment by b-spillman** [comment]
No error - the miner is synced and active

**Comment by cokes518** [comment]
the error message might be hidden beneath the button. @b-spillman can you try reducing your screen font size so there's no overlapping UI elements?

**Comment by b-spillman** [comment]
I am aware of the error that is mentioned but again there is no error message on the screen no matter what the font size.

**Comment by smarthousetips** [comment]
@cokes518 Any update on this?

**Comment by cokes518** [comment]
looks like you fixed it by transferring HNT to another wallet? @b-spillman can you sign out and sign back in. and also let me know the hotspot name you're trying to transfer.

**Comment by smarthousetips** [comment]
@cokes518 Yes, I fixed my issue around the wallet not opening. The hotspot that @b-spillman is looking to transfer is to me though. The hotspot name is Mythical Gauze Hamster. Waiting to see if signing up for a new wallet will solve the transfer issue. @b-spillman could you try transferring to the new address I sent you when you are able?

**Comment by cokes518** [comment]
@smarthousetips how's this issue going? still happening?

**Comment by hedst059** [comment]
Is there anyway to transfer if my hotspot has not had activity in the last 1200 blocks?  I set up a bobcat about a month ago and sold it on ebay this week.  It has already been shipped to the buyer (should arrive Thursday) and now I'm not able to transfer.  Are there any solutions for this?

**Comment by hedst059** [comment]
> 

I was able to solve it. The buyer just needs to plug it in and connect to Wi-Fi. Once it syncs and gets a beacon you are able to transfer
