### ISSUE TITLE
Can’t access wallet options

### ISSUE THREAD

**Issue by smarthousetips** [helium/hotspot-app#1019]
Hello. I am not able to access my wallet options. When I click “<>”, the only thing that comes up is my wallet address and I cannot get to the other options to accept a hotspot transfer. I can click to send or receive but I cannot get to the other options that are typically available. 
![Uploading F5B54350-11CA-40FC-B176-6C159F798E0B.png…]()

**Comment by smarthousetips** [comment]
![1E0CE20D-BDC6-442E-8F6E-765322793E1D](https://user-images.githubusercontent.com/18690454/139569540-6dbf7bc8-e68b-4ee0-a1ef-9d0e90fc891b.png)

**Comment by smarthousetips** [comment]
Merge with bug issue.

**Comment by abhay** [comment]
Thanks for reporting and providing more details in #1020. Closing in favor of that one.
