### ISSUE TITLE
Firmware still ob 2021.10.18.1 HS earning nearly 0

### ISSUE THREAD

**Issue by mineHNT1** [helium/hotspot-app#1025]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

**Additional context**

**Comment by cokes518** [comment]
Who is your manufacturer? You need to contact them to push an update.

**Comment by cokes518** [comment]
closing as this is not an app issue.

**Comment by mineHNT1** [comment]
Nebra is the manufacture Gesendet mit der mobilen Mail AppAm 02.11.21 um 18:45 schrieb Coco Tang
                
            
            
                
                    Von: "Coco Tang" ***@***.***>Datum: 2. November 2021An: "helium/hotspot-app" ***@***.***>Cc: "Author" ***@***.***>,"mineHNT1" ***@***.***>Betreff: Re: [helium/hotspot-app] Firmware still ob 2021.10.18.1 HS earning nearly 0 (Issue #1025)
                
                
Who is your manufacturer? You need to contact them to push an update.

**Comment by cokes518** [comment]
check in with the nebra team. they're the ones pushing out firmware updates to your Hotspot.

**Comment by mineHNT1** [comment]
It’s impossible to reach out to them.I sent an email and just get the „ticked closed“ as answer back without any word.Gesendet mit der mobilen Mail AppAm 02.11.21 um 23:59 schrieb Coco Tang
                
            
            
                
                    Von: "Coco Tang" ***@***.***>Datum: 2. November 2021An: "helium/hotspot-app" ***@***.***>Cc: "mineHNT1" ***@***.***>,"Author" ***@***.***>Betreff: Re: [helium/hotspot-app] Firmware still ob 2021.10.18.1 HS earning nearly 0 (Issue #1025)
                
                
check in with the nebra team. they're the ones pushing out firmware updates to your Hotspot.
