### ISSUE TITLE
my wallet has been changed over update 

### ISSUE THREAD

**Issue by kk7nc** [helium/hotspot-app#1026]
in the past week, my app wash crashed and I did a screenshot from all of my 12 words but after logging in with that 12 words all my HNT and hotspots are gone,
I email several times to Helium support but they said that your current wallet is different from the wallet that is associated with a hotspot you used which is not make sense.

and they only keep saying your 12 words is not the words you used for that wallet, I don't know what happened in this app,
Now they only say we cannot recover those words, but still, I don't know what happen with my hotspot.

This is not my fault to forget those words because I have them but I find the bug which if you log in in two devices like iPhone and android with the same words the wallet could be changed and everything will be gone.

now how can I transfer my hotspot based on what is happened to me, I just turn it off.

Device: iPhone and android
OS: IOS 15 and android 11

Why my previous bug issue is closed my problem did not solved

**Comment by cokes518** [comment]
this is not an app bug. you are entering the 12 words incorrectly. Every Hotspot has an owner and if you lose the private key to the wallet that owns the Hotspot, you lose the Hotspot. 

The 12 words act as a seed phrase to your private key.
