### ISSUE TITLE
WHY close my problem all the times I'm sure that i enter 12 words (seeds) correctly I explain the bug which happens to android and IOS

### ISSUE THREAD

**Issue by kk7nc** [helium/hotspot-app#1030]
I'm sure that i enter 12 words (seeds) correctly I explain the bug which happens to android and IOS

_Originally posted by @kk7nc in https://github.com/helium/hotspot-app/issues/1029#issuecomment-958317523_

**Comment by cokes518** [comment]
it is not a bug. The words are entered incorrectly, in the wrong order, or there is a typo. please stop opening issues on this matter or we'll have to block you from creating future issues.

**Comment by malves749** [comment]
I have exactly the same problem.  I only created 1 account.  I have the right 12 words!!!  and now i have 2 addresses 🙁
