### ISSUE TITLE
Bobcat no on-boarding renamed itself

### ISSUE THREAD

**Issue by ProfessorHtx** [helium/hotspot-app#1033]
**Describe the bug**
No on-board key when trying to use Bluetooth. Miner stuck on yellow. Left on for 12 hours prior to on-board.

1. Go to  on board
2. Click on pair
3. Scroll down to  miner stuck

**Expected behavior**
Miner will not pair. The miner name is short lime tiger but now renamed itself to jovial cider kookaburra 

**Screenshots**
![Screenshot_20211101-213557_Helium](https://user-images.githubusercontent.com/92286280/140009865-ff93bf79-9f91-4492-8f7b-1d68be23cdf8.jpg)
![20211101_213308](https://user-images.githubusercontent.com/92286280/140009868-df14200f-56d2-4a7d-88a3-317a5044df5d.jpg)
![Screenshot_20211102-214157_Chrome](https://user-images.githubusercontent.com/92286280/140009872-b5ee03b5-383d-400e-821a-29a72cbacbb0.jpg)

**Smartphone (please complete the following information):**

**Additional context**
Used hot spot utility app to dial into dashboard.
Dash looks different and has limited options see pictures.

**Comment by abhay** [comment]
Please contact Bobcat support. If the miner changed it's name. it's likely a hardware issue.
