### ISSUE TITLE
Moving Hotspot Location - No option to select new location 

### ISSUE THREAD

**Issue by joshhansen29** [helium/hotspot-app#1037]
**Describe the bug**
The app doesn't allow me to select a new location when trying to update the hotspot location.

**To Reproduce**
When the hotspot is selected, click the cog.
Click Update Hotspot.
Click Update Location.
It takes me directly to this page. (Page shows the hotspot at its current location.)
![Screenshot_20211104-101740](https://user-images.githubusercontent.com/51929859/140378148-19c02d48-8a40-4d51-8a5d-a3e4ba55d46b.jpg)

There is no option to select the new location.

**Expected behavior**
A movable map that allows me to select the new location.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [OnePlus 8T]
- OS: [11.0.13.15.KB09CB]
- App Version [3.7.1]

**Additional context**

**Comment by joshhansen29** [comment]
After clicking Change Location, I now see the map that I was expecting to select the new location. May I suggest that you make an adjustment to UI so that it is more clear that you will have an option to select the new location before being charged.

Keep up the good work! :)

**Comment by cokes518** [comment]
sure thing. thanks for the feedback.
