### ISSUE TITLE
Transfer ownership of router not working

### ISSUE THREAD

**Issue by donutloop** [helium/hotspot-app#1051]
**Describe the bug**

 I can't transfer the ownership of router to a new wallet address. If I press the blue transfer button nothing happens.  No error 

**Smartphone (please complete the following information):**

- Device: iPad air 4 
- OS: latest version
- App Version 3.7.1

**Comment by donutloop** [comment]
The ticket can be closed. The router ownership has successfully transferred to the new owner.

**Comment by cokes518** [comment]
glad to hear it
