### ISSUE TITLE
font scaling affecting location assertion

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#1054]
to reproduce: set font scaling to a non-default value. try 200-300%.
1. go to hotspot > assert location
2. drop the pin on a map, proceed to next step
3. pin moves to a different location.

video on discord: https://discord.com/channels/404106811252408320/733699201887764511/907302163234058301

confirmed with user that if he removes font scaling, the location doesn't move "as much".

questions to consider: is it the svg? can we use lock the icon resolution?

**Comment by tfspire** [comment]
Any workaround for this? This happens to, I'm trying to set location but it always move on the following screens
