### ISSUE TITLE
App crash when pairing

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#1055]
on android, 3.8.0. user reporting the app is crashing.

wallet address: https://discord.com/channels/404106811252408320/733699201887764511/907331821648347157

**Comment by That1Reefer** [comment]
14TAsyfPRmhgXfxKgioMQcdvutaybr3zefptzdZFzVgr6zhmL15

App 3.8.0
Android 11
Oneplus 7T pro mclaren edition
App force closes when trying to pair and in discovery mode.
