### ISSUE TITLE
Nothing happens on "add a Helium Miner"

### ISSUE THREAD

**Issue by tfspire** [helium/hotspot-app#1056]
**Describe the bug**

Not possible to do anything on Add a helium Miner menu

1. Click on hotspots dropdown menu
2. Click " + add hotspot". 
3. The Hotspots dropdown menu closes and nothing happens

The same behavior for info, search, Validators, etc. 

 Tried with a one plus 7T and a Samsung tablet s7 all on android 11 with the same behavior. Other users on discord reporting the same

**To Reproduce**

1. Click on hotspots dropdown menu
2. Click " + add hotspot". 

**Expected behavior**
Menu to add the hotspot would appear

**Screenshots**

**Smartphone (please complete the following information):**

- Device: one plus 7T
- OS: Android 11
- App Version 3.8.0

**Additional context**

**Comment by piodabro** [comment]
Just added the same issue: https://github.com/helium/hotspot-app/issues/1057
It seems that it is a pain not only for me :)

**Comment by cokes518** [comment]
@tfspire @piodabro can you drop your emails here so I can add you to a beta testers list?

**Comment by piodabro** [comment]
Actually i've just downloaded v3.7.1 and set-up the miner with older version app.
in v3.7.1 it worked fine.

**Comment by JGrayBKKGames** [comment]
Issues are also happening with Transferring Miners

**Comment by cokes518** [comment]
these issues are very likely related to the bug fix we're merging shortly. if you want to help test, please leave your email here and I'll add you to the beta testing group.

**Comment by maderamine77** [comment]
I just got my new miner today, and I  really looking forward to a fix.  Thanks for addressing this bug.

**Comment by tfspire** [comment]
Hey, sorry just saw this but at the end I followed the advice to downgrade the app and added it that way.

Nevertheless I can let my email and test if the menu works: pwerspire@gmail.com

**Comment by cokes518** [comment]
https://play.google.com/apps/testing/com.helium.wallet

**Comment by libnex** [comment]
nexzus.news@gmail.com

**Comment by paulmmancuso** [comment]
I have 4 miners that are useless because the app does not allow me to add them.  Please fix.

**Comment by paulmmancuso** [comment]
How is that helpful?

**Comment by cokes518** [comment]
> I have 4 miners that are useless because the app does not allow me to add them. Please fix.

we're reviewing a fix. please bear with us. you can join the beta app release if you'd like or downgrade to 3.7.1 to add your hotspot.

**Comment by paulmmancuso** [comment]
so 1) how do i join the beta release and 2) how do i install older app?

**Comment by cokes518** [comment]
please scroll up for beta instructions

**Comment by paulmmancuso** [comment]
![image](https://user-images.githubusercontent.com/93950672/140824492-0c842505-aaed-4638-bf23-9a26bdd08920.png)

**Comment by cokes518** [comment]
did you leave your email address for me to add to the list?

**Comment by paulmmancuso** [comment]
paulmmancuso@gmail.com

Or the link to the old software.

**Comment by cokes518** [comment]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/19331274/140825118-73b8fdbc-f703-4133-80f4-885a66b29a8f.png">

**Comment by maderamine77** [comment]
> did you leave your email address for me to add to the list?

maderamine@protonmail.com is my email.  I.have google play so I have no way to downgrade my version.  I am hoping for some kind of resolution.

**Comment by cokes518** [comment]
> > did you leave your email address for me to add to the list?
> 
> [maderamine@protonmail.com](mailto:maderamine@protonmail.com) is my email. I.have google play so I have no way to downgrade my version. I am hoping for some kind of resolution.

is that email correct? I can't see to add it to the list.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/19331274/140825439-e7df83b6-1aac-4f7e-9b03-11303dbb2503.png">

**Comment by cokes518** [comment]
https://install.appcenter.ms/orgs/helium/apps/hotspot-app-android/distribution_groups/public

for older versions of the android app

**Comment by maderamine77** [comment]
> > > did you leave your email address for me to add to the list?
> > 
> > 
> > [maderamine@protonmail.com](mailto:maderamine@protonmail.com) is my email. I.have google play so I have no way to downgrade my version. I am hoping for some kind of resolution.
> 
> is that email correct? I can't seem to add it to the list. <img alt="image" width="281" src="https://user-images.githubusercontent.com/19331274/140825439-e7df83b6-1aac-4f7e-9b03-11303dbb2503.png">

Yes it's correct maderamine@protonmail.com

**Comment by paulmmancuso** [comment]
3.8.1 does not fix/resolve the issue

**Comment by cokes518** [comment]
fix has not been merged yet.

**Comment by paulmmancuso** [comment]
well if 3.8.1 is the "beta" and that is what i was offered as a "fix" i am letting you know it did not work.

**Comment by cokes518** [comment]
your attitude is not appreciated. we never said the fix was merged and ready for testing.

**Comment by paulmmancuso** [comment]
First of all........You said, "you can join the beta app release if you'd like or downgrade to 3.7.1 to add your hotspot" which I read as an either or so sorry.  Secondly.  The app in the store functionally doesnt work at all......seems like it shouldnt have been released and the reviews show it has been having issues for a while.

**Comment by cokes518** [comment]
thanks for your feedback 👍

**Comment by maderamine77** [comment]
I got it to work by going to the older version it actually pretty easy.  Thanks cokes518

**Comment by cokes518** [comment]
beta build for 3.8.1 is now available

**Comment by NetMasterX** [comment]
I received a Reddit reply. 


level 1
Juulk9087
OP
·
24m
Plug them all in and port forward them. Give them about an hour to grab the update. Then Bluetooth should work. Even then you may have to keep trying to connect. I personally had to try to connect about 6 times before it recognized it.

**Comment by NetMasterX** [comment]
how do you download an older version?

**Comment by NetMasterX** [comment]
thanks @cokes518 i saw the link to older versions.

**Comment by Batfinks** [comment]
> @tfspire @piodabro can you drop your emails here so I can add you to a beta testers list?

Can you add me as well?  I just got my miner today and want to get started!  scottfink6923@gmail.com

**Comment by NetMasterX** [comment]
i too downgraded to 3.7.1 and got it on line, in pending mode.  @cokes518

**Comment by hellgihad** [comment]
Can you add my email to the test list please too mateusz.git@gmail.com
Just got my miner today, tried to add a hotspot on three different phones and started panicking a bit as google was oblivious of this issue :P

**Comment by adamvarhegyi** [comment]
Same issue.

Please add me as tester, thanks.

adamvarhegyi20@gmail.com

Xiaomi Mi A1
Android 10

**Comment by inetphantom** [comment]
# Workaround for all wanting to setup *now*

I was able to workaround by a combination of tapping, holding and sliding slightly on that button. - if someone want's to up their miners now and not as soon as the app is actually deployed to end users via google play

**Comment by cokes518** [comment]
# THE APP UPDATE IS RELEASED. PLEASE DOWNLOAD 3.8.1 FROM THE PLAYSTORE.

**Comment by cokes518** [comment]
I DO NOT NEED ANYMORE EMAILS. THX ALL!
