### ISSUE TITLE
I can't add miner

### ISSUE THREAD

**Issue by dulama** [helium/hotspot-app#1064]
Hi, 

There is a problem with buttons, I can't add my miner, please fix. I have tested on 3 devices, same problem.

Thanks,
Vlad

**Comment by cokes518** [comment]
hi there, the fix is in 3.8.1. Please update to that and join us in discord where we make regular announcements about bug fixes and improvements.

discord.gg/helium

**Comment by dulama** [comment]
Hi, the latest version in Playstore is 3.8.0

**Comment by dulama** [comment]
I encounter the same problem in v3.8.1, you can see on the file attach

https://user-images.githubusercontent.com/38689260/140978526-5b682985-19cf-4925-8627-cdb5614cbdb3.mp4

ed
