### ISSUE TITLE
Nothing happens on "add a Helium Miner" - Android VERSION 3.8.1 new

### ISSUE THREAD

**Issue by johnstoia** [helium/hotspot-app#1065]
Referencing this thread that has been closed

https://github.com/helium/hotspot-app/issues/1056

The issue is still happening where I cannot add my miner even after uninstalling/reinstalling and updating to version 3.8.1

1. Click on hotspots dropdown menu
2. Click " + add hotspot".
3. The Hotspots dropdown menu closes and nothing happens

Smartphone (please complete the following information):

Device: Samsung Galaxy S21+
OS: Android 11, One UI Version 3.1
App Version 3.8.1

**Comment by cokes518** [comment]
Thanks, we're looking into it. Does Samsung have an OS update available to Android 12 yet?

**Comment by johnstoia** [comment]
Not that I see

**Comment by cokes518** [comment]
> The Hotspots dropdown menu closes and nothing happens

there's no dropdown menu after pressing '+'. are you not able to select a Hotspot from the list?

**Comment by johnstoia** [comment]
I tried to screen reocord what was happening but it didn't work due to security policy.

I can't even get to that point. Here's the process flow

1. I get to the "Add a Helium Miner" page with the two drop downs.
2. I click "Hotspots"
3. The drop down menu opens
4. I click "+ Add Hotspot"
5. The dropdown menu closes

Repeats

**Comment by Tuzas666** [comment]
Same problem for me :/

**Comment by cokes518** [comment]
we found the problem! 
feel free to downgrade to 3.7.1 for the time being. https://install.appcenter.ms/orgs/helium/apps/hotspot-app-android/distribution_groups/public

**Comment by dulama** [comment]
same for me

https://user-images.githubusercontent.com/38689260/140979727-92612179-6883-47ba-9621-783cc87edbd6.mp4

**Comment by cokes518** [comment]
The work around is to:
1. go to search and follow a Hotspot (any Hotspot)
2. the Home Screen UI will change from the dropdown to a list view. 
3. tap the + icon in the top right

**Comment by matkap86** [comment]
I have still this problem why is t not fix yet

**Comment by cokes518** [comment]
It’s fixed in 3.8.2

**Comment by cokes518** [comment]
Closing the issue - the fix is in 3.8.2.
