### ISSUE TITLE
Pending Hotspot transfer status

### ISSUE THREAD

**Issue by hunet-hr** [helium/hotspot-app#1069]
The hotspot I have is ENERGETIC GRAPE CHIPMUNK, it works and I have full access, but still the transaction hotspot is pending.
It shows up in my wallet and is mining, only issue is pending transfer status. Can you clear the database record please ?

![IMG_4101](https://user-images.githubusercontent.com/93479324/141018246-5aef86b4-7781-43e3-b63a-a3971ff88380.jpg)

![IMG_4100](https://user-images.githubusercontent.com/93479324/141018181-f9587051-e7ed-42b8-b3ef-526a01cfcc2a.jpg)

**Comment by cokes518** [comment]
It's been cleared. check on your side?

**Comment by hunet-hr** [comment]
> It's been cleared. check on your side?

Great, it's okay now.
Thank you
