### ISSUE TITLE
Antenna Info reversion on position update

### ISSUE THREAD

**Issue by JohnMacrae** [helium/hotspot-app#1075]
**Describe the bug**
I updated my antenna info an hour ago. The update went through and showed in explorer. Then I updated the position which was slightly out and that went through OK as well. however the antenna info then reverted to what it was before.

**To Reproduce**

I have not attempted to reproduce this behaviour as its too expensive.
Actions: 
Update Custom antenna information and wait for that transaction to clear from 'pending'
Check that antenna info is correct in explorer (web - since cacheing on Android app means a very long wait)
Update hotspot position and pay. Wait for transaction to clear and check position,
Antenna data will have reverted.  (Possibly due to antenna data being sent and updated at the same time as position data and since old antenna data is still cached, it overwrites - just a guess)

**Expected behavior**
I expected the position data to be updated independently of the antenna data.

**Screenshots**
Didn't take screenshots. Affected hotspot Fantastic Chambray Bee

**Smartphone (please complete the following information):**

- POCO X3 Pro
- Android MIUI Global 12.5.3
- 3.8.1

**Comment by cokes518** [comment]
another regression. thanks for reporting.

**Comment by cokes518** [comment]
It's possible the root cause of this was due to the network outages around this time. If you see this again, please let us know.
