### ISSUE TITLE
Bluetooth connectivity hangs when API is down/struggling

### ISSUE THREAD

**Issue by radrob1** [helium/hotspot-app#1076]
**Describe the bug**
When trying to connect to a hotspot via bluetooth while the Helium API is having issues, the bluetooth screen hangs (see image).

**To Reproduce**
Wait for Helium API to have issues, then try to connect to a hotspot via bluetooth.

**Expected behavior**
Expected to be able to connect and run hotspot diagnostics.

**Screenshots**
![IMG_3426](https://user-images.githubusercontent.com/78358412/141351205-cd4541d2-d993-4634-9ac6-829843600253.jpg)

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: 14.8.1
- App Version: v3.8.0

**Additional context**
I was able to connect to the hotspot via the unofficial Helium hotspot app worked while the Helium API was having issues.

**Comment by cokes518** [comment]
@radrob1 we found the root caused and fixed it in 3.8.3

**Comment by cokes518** [comment]
it was because the app was checking the API for hotspot owner (as the code was reused from Hotspot pairing/onboarding). That check is no longer there so if the API goes down, pairing should still work.
