### ISSUE TITLE
Error constructing assert location transaction when asserting location for the first time

### ISSUE THREAD

**Issue by will-deng** [helium/hotspot-app#1077]
**Describe the bug**
Error constructing assert location transaction when asserting location for the first time. 

**To Reproduce**
In the Helium app, either on Android or iOS:
1. Find the hotspot that needs the location asserted
2. Tap the gears icon to enter Hotspot Settings
3. Tap Update Hotspot
4. Tap Update Location
5. Tap Change Location
6. Enter in address of hotspot and drag pin to fine tune if needed
7. Tap "I Confirm"
8. Hit submit

**Expected behavior**
Hotspot's location is asserted

**Screenshots**
Can't take screenshots due to security policy but the Error after hitting submit is as follows:

Error
There was an error constructing the Assert Location trnsaction. Please try again. 

**Smartphone (please complete the following information):**

- Device: Galaxy Fold 3, vivo Nex, iPad Pro
- OS: Android 11, Android 10, iOS 15.1
- App Version: v3.8.2 on Android, v3.8.0 on iOS 

**Additional context**
This was performed on a RAK hotspot v1.5. A user in discord said that their Bobcat was also exhibiting the same issue when trying to assert location for the first time. I was able to assert the location for a MNTD Goldspot miner recently but no luck on this device unfortunately. I have also tried changing from StakeJoy API to Helium API but that did not work either. 

Update: Cannot update antenna info either. Same error

**Comment by will-deng** [comment]
I have been able to workaround this issue by issuing location/antenna update commands through by using the CLI wallet

**Comment by cokes518** [comment]
what is your hotspot's name? I want to see if I can find some clues/hints even though you were able to submit the transaction via CLI.

**Comment by cokes518** [comment]
this is also a regression so we'll look into it regardless. thanks for reporting.

**Comment by will-deng** [comment]
Hotspot's name is Little Seaweed Crow. The problem still exists on my other hotspots (Damp Marigold Cottonmouth and Howling Peanut Halibut) that I haven't deployed yet.

**Comment by cokes518** [comment]
The error constructing transaction is still happening on those other Hotspots? Are they plugged into/synced to the chain yet?

**Comment by will-deng** [comment]
Yes, one of them is plugged in and completely synced, one of them is not. Has been going on for me at least for almost a month before I was suggested the CLI wallet route

**Comment by jselvanayagam** [comment]
Hi my hotspot name is Fast Syrup Goat, I cannot find the hotspot in the App nor in the helium map.  Please help

**Comment by jselvanayagam** [comment]
![Uploading 40BCD632-9189-40A7-A7F4-928CA04FE502.jpeg…]()

**Comment by jselvanayagam** [comment]
Could someone please let me know what is the next step to bring the RAK Minter V.2 to the helium network?

**Comment by tyler-whitman** [comment]
@will-deng are the other two hotspots RAK v1.5 as well?

**Comment by tyler-whitman** [comment]
@will-deng would you be able to give one of the two left another try?

**Comment by jselvanayagam** [comment]
Location Asserting error no longer there, it’s is online now but it is saying it’s been relayed, any help appreciate it.

**Comment by will-deng** [comment]
@tyler-whitman no luck, the other two hotspots are mntd goldspots so I think these are RAK v2s

**Comment by cokes518** [comment]
@will-deng looks like you were able to assert them - what changed?

**Comment by cokes518** [comment]
closing as this has gone stale and looks to be resolved.

**Comment by egzefer** [comment]
I'm having this issue now.

**Comment by krital** [comment]
> closing as this has gone stale and looks to be resolved.

Hi there, just got a brand new MNTD Gold miner, got this error on my very first attempt to register.. I have repeated the registration a few times now, every time it says registering and later on its not there.. Sometimes I get the above mentioned error message in a popup, sometimes I get it asynchronously in the IOS app notifications. Not sure how to proceed. Any hints? (remember the hotspot is not listed in the app for me to do any manual asserts)

**Comment by max-gpz** [comment]
I've recently faced this issue.

**Comment by max-gpz** [comment]
> 

Let me know if you found a resolution. I'm facing the same issue with a Midas-962. It does appear this has not been closed.

**Comment by max-gpz** [comment]
> > closing as this has gone stale and looks to be resolved.
> 
> Hi there, just got a brand new MNTD Gold miner, got this error on my very first attempt to register.. I have repeated the registration a few times now, every time it says registering and later on its not there.. Sometimes I get the above mentioned error message in a popup, sometimes I get it asynchronously in the IOS app notifications. Not sure how to proceed. Any hints? (remember the hotspot is not listed in the app for me to do any manual asserts)

Let me know if you found a resolution. I'm facing the same issue with a Midas-962. It does appear this has not been closed.

**Comment by livingaftermidnight** [comment]
> > > closing as this has gone stale and looks to be resolved.
> > 
> > 
> > Hi there, just got a brand new MNTD Gold miner, got this error on my very first attempt to register.. I have repeated the registration a few times now, every time it says registering and later on its not there.. Sometimes I get the above mentioned error message in a popup, sometimes I get it asynchronously in the IOS app notifications. Not sure how to proceed. Any hints? (remember the hotspot is not listed in the app for me to do any manual asserts)
> 
> Let me know if you found a resolution. I'm facing the same issue with a Midas-962. It does appear this has not been closed.

I'm having this issue with a brand new Midas-926 miner when registering for the first time.

**Comment by livingaftermidnight** [comment]
> > > > closing as this has gone stale and looks to be resolved.
> > > 
> > > 
> > > Hi there, just got a brand new MNTD Gold miner, got this error on my very first attempt to register.. I have repeated the registration a few times now, every time it says registering and later on its not there.. Sometimes I get the above mentioned error message in a popup, sometimes I get it asynchronously in the IOS app notifications. Not sure how to proceed. Any hints? (remember the hotspot is not listed in the app for me to do any manual asserts)
> > 
> > 
> > Let me know if you found a resolution. I'm facing the same issue with a Midas-962. It does appear this has not been closed.
> 
> I'm having this issue with a brand new Midas-926 miner when registering for the first time.

I updated my location a second time and it seems to have finally gone through. The phone app says "Updating location" still, but I can find my miner on the Helium Explorer site.

**Comment by Ryan-Goldstein** [comment]
If it's stuck showing 'Updating location', update the app to 4.1.0 if it's not already on that version, then sign out, then sign back in.

**Comment by livingaftermidnight** [comment]
> If it's stuck showing 'Updating location', update the app to 4.1.0 if it's not already on that version, then sign out, then sign back in.

Signing out and back in, worked to fix the Updating location issue. Thanks dude!

**Comment by Ryan-Goldstein** [comment]
> > If it's stuck showing 'Updating location', update the app to 4.1.0 if it's not already on that version, then sign out, then sign back in.
> 
> Signing out and back in, worked to fix the Updating location issue. Thanks dude!

No problem - I've already submitted an issue for it (#1312); hopefully it gets resolved soon!
