### ISSUE TITLE
Helium Hotspot App to check existing transmit scale in the HEX before onboarding new Hotspot

### ISSUE THREAD

**Issue by rjwelling2** [helium/hotspot-app#1085]
Feature request for the Helium Hotsapp to verify, before final onboarding of a new hotspot if transmit scale isn't severely impacted, If serverly impacted (< 0.9) refuse onboarding of new hotspot. A message should appear to inform the user about the situation.

**Comment by cokes518** [comment]
I responded to the same request here: https://github.com/helium/hotspot-app/issues/1180#issuecomment-1021590759
