### ISSUE TITLE
Unable to Import Account (Pixel 6 Pro Android 12)

### ISSUE THREAD

**Issue by NetScr1be** [helium/hotspot-app#1086]
**Describe the bug**
App does not move past entering 12-word recovery seed phrase

**To Reproduce**
Install: https://play.google.com/store/apps/details?id=com.helium.wallet
Launch app
Select "Import Existing Account"
Enter seed phrase (case insensitive)
Arrow key on keyboard does not respond
No other method to move forward  in UI

**Expected behavior**
Move to next screen after entering seed phrase

**Screenshots**
N/A (would reveal seed phrase)

**Smartphone (please complete the following information):**

- Device: Google Pixel Pro 6
- OS: Android 12
- App Version 3.8.2

**Additional context**
Existing install works on Pixel 3A XL (verified words against backup OK)

**Comment by NetScr1be** [comment]
This account was imported to the Pixel 3A XL at one point.

The account was initially created on another Pixel 3A XL (which was decommissioned)

**Comment by cokes518** [comment]
has the arrow key always worked? Just tried on a pixel 3 and pixel 6 and neither's arrow key advances you to the next word. 

The expected way to advance through the importing flow is to tap the word that appears below the text field (which does work).

**Comment by benstrum** [comment]
I can confirm the same issue with Google pixel 6.

**Comment by cokes518** [comment]
> I can confirm the same issue with Google pixel 6.

does it work if you tap the word (instead of pressing the arrow key)?

**Comment by benstrum** [comment]
No it does not do anything to tap on the word.

**Comment by cokes518** [comment]
@benstrum do you have a custom keyboard?

**Comment by benstrum** [comment]
No, just the one that came with it... The Google keyboard (Gboard).
