### ISSUE TITLE
Hotspot transfer pending bobcat 300 Helium miner

### ISSUE THREAD

**Issue by Hendrine96** [helium/hotspot-app#1087]
![0BBF43D5-E365-40AC-AB69-1C2B88A93FE1](https://user-images.githubusercontent.com/94402698/141848483-2fed58a2-a4f8-4046-8c3b-cea8160fd1ca.png)
![A9001CCB-CFDC-4DF7-8A9D-AA529E0BFCAF](https://user-images.githubusercontent.com/94402698/141848500-c1702c9e-540e-42b0-b207-93a66432ad13.png)

![448E03E9-D43C-4143-A623-7B4E46E36381](https://user-images.githubusercontent.com/94402698/141848505-9db82887-ce9d-4fb0-815b-9c80a0fcebe4.png)
![1497655E-7185-4DA0-8F5E-1BDE40D625E1](https://user-images.githubusercontent.com/94402698/141848510-60c839c9-3579-4b45-ad27-a0e44b2e1935.png)

hey guys! 

I bought a bobcat 300 5 days ago and set this up and installed everything. My internet is 400mbs, and everything is well functioning.

only issue is, it says “transfer hotspot pending” but the transfer went okay, I even paid for the transfer on the app with DC. 

Also its not sending beacons or accepting witnesses and 0 rewards. What should I do?

**Comment by BarisTonbul** [comment]
I got same problem. Can anybody reach me ???

**Comment by cokes518** [comment]
looks like this was cleared last week @Hendrine96 closing. please open another if it's still happening!

**Comment by maxx2111** [comment]
Hello guys,

Have exactly the same issue, can someone help me pls ?

Thanks!

**Comment by Eligijus996** [comment]
Hi I have same issue. Need help

**Comment by Eligijus996** [comment]
![Uploading Screenshot_20211218_154124_com.helium.wallet.jpg…]()
