### ISSUE TITLE
Award count different between 24h and 14d / 30d

### ISSUE THREAD

**Issue by woody5577** [helium/hotspot-app#1102]
In the app version 3.8.3 (I´m an android user) there is the following missmatch in the awards calculation which is very confusing:
- I think this is due to the missmatch of the timezones UTC used in the same app, so in the home button view and local time (+1h) in the miners view (24h, 14d, 30d)
- in the home overview you are using now the UTC time and count the awards there accordingly for the past day. So today I see e.g. 0,82 for the past day for my two miners
- but when I go to the miner e.g. 14d (and also in 30d) view there is the award sum of yesterday a different value which is 0,47 and 0,4 --> 0,87 in total

I would prefer the local time for sure also for the home view

Screenshot I cannot provide, sorry, this is not possible since the last app update

Samsung Galaxy S8 Model SM-G950F
Android version 9

**Comment by tyler-whitman** [comment]
Thanks for the report, we are looking into it.

**Comment by cokes518** [comment]
closing this issue as it's gone stale. please let us know if it's still happening.
