### ISSUE TITLE
pending transfer hotspot

### ISSUE THREAD

**Issue by honmmtc** [helium/hotspot-app#1104]
![IMG_20211113_123703](https://user-images.githubusercontent.com/94725256/142708053-d3eab556-3e7a-4922-8db2-aef165727bd2.jpg)
![IMG_20211113_123734](https://user-images.githubusercontent.com/94725256/142708060-fee7ecce-a194-4d9d-b520-5fc3f61a1d15.jpg)
My sensecap m1 show pending transfer hotspot from 2 weeks ago but actually already completed transfer. Can't transfer to new owner.

how to fix it.

**Comment by tyler-whitman** [comment]
Thanks for the report @honmmtc give it a try now, it should be resolved.
