### ISSUE TITLE
Hotspot app syncing and discovery bugged

### ISSUE THREAD

**Issue by justme99999** [helium/hotspot-app#1105]
**Describe the bug**
From about 3 weeks i can't use discovery on my senscap hotpot because the status is syncing (ios) and discovery telling me the hotspot has to be synced in order to run discovery. My hotspot is always synced but the app is saying 'syncing' I opened a ticket in senscap discord but they said is related with the hotspot app and they can't help me.
  My other hotspot helium hs1, i can run discovery but the results are most of the time 0 or only 4-5 hotspots when i should get around 300 hotspots in discovery

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone12
- App Version e.g. 3.8.3

**Additional context**

**Comment by cokes518** [comment]
going to close this issue for now. please reopen if this still occurs when we re-enable discovery mode in the future. My initial thoughts are that discovery mode was so popular that it overwhelmed the router instance and state channels, such that some users were unable to see consistent results.

we'll be revisiting the how we can make discovery mode available to users in a better, future-proof, and consistent manner.

On the sync issue: gossip times mean the app is unable to properly recognize a Hotspot is fully synced until gossip has told the app this. We'll also consider this when we revisit the feature.
