### ISSUE TITLE
Discovery mode without results

### ISSUE THREAD

**Issue by woody5577** [helium/hotspot-app#1106]
Since 3 days I do not get any result running the discovery mode. The discovery starts and runs for 5 min but the end result is that 0 hotspots do respond. But luckily this is not the truth because I do have daily rewards. I do have 2 hotspots and the result (zero respond) is same for both of them. Both are healthy and fully synched and online.

Screenshot I cannot provide, sorry, this is not possible since the last app update

Samsung Galaxy S8 Model SM-G950F
Android version 9

**Comment by cokes518** [comment]
going to close this issue for now. please reopen if this still occurs when we re-enable discovery mode in the future. My initial thoughts are that discovery mode was so popular that it overwhelmed the router instance and state channels, such that some users were unable to see consistent results.

we'll be revisiting the how we can make discovery mode available to users in a better, future-proof, and consistent manner.
