### ISSUE TITLE
Hellium Hotspot App Issues

### ISSUE THREAD

**Issue by toddeide** [helium/hotspot-app#1107]
I have connected my hotspot to my wallet and it says I own the hotspot but it does not show up in the app so i can place the miner in the home.

**Comment by cokes518** [comment]
is still this a problem?

**Comment by cokes518** [comment]
this looks to be a duplicate of #1108

**Comment by JonasHartig** [comment]
hi, i know this is a realy old thread but yeah.  At least for me.

**Comment by cokes518** [comment]
it's a different root cause.. but it will be fixed in the next app release. keep an eye out for 5.0.4.

**Comment by JonasHartig** [comment]
wow that was fast! massive thanks i will wait :)
