### ISSUE TITLE
Tapping on a hotspot pill in the sub nav sometimes takes you back to Home Screen

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#1110]
likely a sync issue with following a hotspot.
does not happen you tap on a hotspot form the Home Screen list.

**Comment by cokes518** [comment]
running suspicion is that Rihanna is behind this. when those improvements are merged, we'll revisit this to see if it's still reproducible.

**Comment by Hidalgo1414** [comment]
Have the same issue on 3.8.4 app version. I registered and synced my bobcat miner and have postponed setting location. 
Once the miner was visible on my nav list, I have tried to finish asserting location but as I tapped on the miner, I'm being returned to "Home". Any advice or workaround?

**Comment by cokes518** [comment]
there's a related fix coming out in 3.8.5. recommend you wait a few days. there's no other workaround.

**Comment by Hidalgo1414** [comment]
Cool, thanks for a quick response.

**Comment by cokes518** [comment]
3.8.5 is released, please update and let me know if it resolves the issue.
