### ISSUE TITLE
Helium HNT Payment trasnaction Cleard???

### ISSUE THREAD

**Issue by Natexo77** [helium/hotspot-app#1113]
Hello dear people,

can someone maybe tell me what i can do.

I have sent some Hnt transactions to my Crypto.com wallet and they just don't arrive.
The transaction has been cleared.... But with no result.
I've been waiting for a week and so far only the first transfer has worked.

I don't even know what to do anymore.

**Comment by elvicab** [comment]
Same thing is happening to me. I spoke with customer service and they said to basically wait. He said they were having delayed transactions

**Comment by Natexo77** [comment]
More than one week, it's this really normal?
Did you talking with crypt or helium services?

**Comment by Natexo77** [comment]
Binance is my second option. The first was really quickly there but my problems starts with the second transaction 🙈

**Comment by elvicab** [comment]
It’s been a week for me as well, ever since the blockchain started having issues

**Comment by elvicab** [comment]
I’m not sure what to do at this point, other than wait and hopefully it goes through. Don’t think there is a way to check the tx on the explorer

**Comment by Natexo77** [comment]
my hnt are here now

**Comment by Natexo77** [comment]
🙌🏾✌🏾

**Comment by cokes518** [comment]
thanks for reporting. looks like the issue is resolved.
