### ISSUE TITLE
Adding RAK Miner 2.0 - Error message

### ISSUE THREAD

**Issue by jselvanayagam** [helium/hotspot-app#1115]
I have added my first RAK minter V2 to Helium network but two days later I have received the following error on the helium app.

Failed Transaction
Unable to Assert Location for Fast Syrup Goat for reason {Invalid, Insufficient_balance}

Please help what should I do to correct this issue.

Thanks,
Jey

**Comment by cokes518** [comment]
This looks related to #1077 

thanks for filing. we're going to close this and track this in the other issue.

**Comment by tyler-whitman** [comment]
@jselvanayagam looks like you got the location asserted, did it end up working for you or was there a work around?

**Comment by jselvanayagam** [comment]
Yes sir, I have to open the TCP port on my firewall, thank you.

**Comment by jselvanayagam** [comment]
My rak hotspot is saying it’s being Relayed, how can I fix it.

**Comment by tyler-whitman** [comment]
@jselvanayagam https://docs.helium.com/troubleshooting/network-troubleshooting/ if you just forwarded TCP port 44158 it may take some time to update the relayed status

**Comment by jselvanayagam** [comment]
Thank you, if I need to install an antenna what I have to do? Do I to have pay?  Please advise

**Comment by EhsanKia** [comment]
Does anyone have any solutions for this?

I have a brand new Rak V2 hotspot, right out of the box. Trying to set it up. Every time I get "Unable to Add Hotspot Abundant Pewter Spider for reason: {invalid,insufficient_balance}" followed by "Unable to Assert Location for Abundant Pewter Spider for reason: {invalid,insufficient_balance}"

Tried 3 times, rebooting and power cycling. This is not second hand, straight from CalChip Connect.
