### ISSUE TITLE
Hotspot Transfer not working?? Shows as pending transfer to my wallet address, but it's already there?

### ISSUE THREAD

**Issue by heliumsupplies** [helium/hotspot-app#1119]
Hello,

I am trying to transfer a hotspot of mine to a friend, it shows that there is a 'transfer request pending click to cancel'.

I have tried cancelling this many many times to no avail, I deleted the app, redownloaded and logged back in and the message saying pending has gone, and shows transfer hotspot. I type the address of the receiver and click transfer and nothing happens still.

Please assist me with this, the hotspot name is Wonderful Oily Copperhead .

I can't do anything with this hotspot and nobody in the Discord can assist either.

Please help!

**Comment by heliumsupplies** [comment]
It also seems to be a bug with another hotspot of mine, both the hotspot names I will leave below.

Rough Arctic Cheetah
Wonderful Oily Copperhead

**Comment by heliumsupplies** [comment]
Rough Arctic Cheetah has now been transferred, Wonderful Oily Copperhead is still showing:
![IMG_B8D3955CB254-1](https://user-images.githubusercontent.com/95084212/143591188-4c024055-7295-4fd8-acf1-7005ca816445.jpeg)

**Comment by heliumsupplies** [comment]
Also adding evidence that the transfer to my address was completed 2 days ag
![IMG_6288](https://user-images.githubusercontent.com/95084212/143595620-554a1bbe-2999-4d0a-80a9-ed3036138a33.jpeg)
o.

**Comment by tyler-whitman** [comment]
@heliumsupplies there is a bug that will be resolved soon with transfer v2. Can you please try again, it should be fixed now.
