### ISSUE TITLE
Hotspot map/explorer freezes and performs atrociously on iPhone 6

### ISSUE THREAD

**Issue by DGKSK8LIFE** [helium/hotspot-app#112]
# Hardware

Currently on an **IPhone 6**, **IOS 12**

### When trying to access the helium global hotspot explorer, I often encounter these problems:

- *1. It does not open*
- *2. It takes 5-10 seconds to do things like opening/closing the hotspot search, loading the map, etc (making it unusable)*
- *3. It opens briefly then closes and returns to the `Hotspots` tab*
- *4. It causes the app to close entirely* 

## Extra information

I can provide screen recordings or send screenshots if necessary.

**Comment by cokes518** [comment]
new app version will not have the map. closing.
