### ISSUE TITLE
HNT transaction failure, invalid,bad_nonce

### ISSUE THREAD

**Issue by oplantis22** [helium/hotspot-app#1120]
Dear People

On 17th of November 2021,
From HNT Wallet, 13yE8KhiJUTBijd6Vkg5SkkpJYRFGDYZDbt4xUQEJZcgk7wtPYz
I sent 16 HNT  to my gate.io HNT account 13Ukx2RGH4SBtt3Txfvs5Hko2LdFfSy3DiTh3jD3fgmo5AcKyVF

Block number is 
1,101,020
.
Then I got a message uncompleted transaction due to invalid,bad_nonce.

Transaction appear as confirmed on explorer and Helium app,

What can I do? 
 #![20211120_004124](https://user-images.githubusercontent.com/95118807/143671454-bd21ec54-6f69-4230-8681-e85303a6f3ff.jpg)
![20211120_004131](https://user-images.githubusercontent.com/95118807/143671457-19d0fa1c-16d9-41d2-bf18-8f036fbcfcf0.jpg)

**Comment by cokes518** [comment]
if it went through, then the notification failure is stale. thanks for reporting though, our Notification Center is going through an overhaul and this is one of the reasons why.
