### ISSUE TITLE
Transferred miner pending 

### ISSUE THREAD

**Issue by DreamerTTT** [helium/hotspot-app#1135]
hi, i ve been waiting 24 days and is unable to cancel a duplicated hotspot transfer request. the original sender has tried and it is not working. if anyone has any ideas please help me. 
refined plum shetland miners name   
https://github.com/helium/hotspot-app/issues/967  same issue with link

**Comment by cokes518** [comment]
hotspot `11Zfi7MRcJ9cVFzbn8fYGVLxDvt4JxWRyBGM1sT3qqXnXtjyV4H`

**Comment by DreamerTTT** [comment]
Solved, thank you so much.
