### ISSUE TITLE
Height Status Not Available  and Sync Percentage Helium API Not Available

### ISSUE THREAD

**Issue by absiko** [helium/hotspot-app#1139]
**Describe the bug**

Height Status Not Available  
Sync Percentage Helium API Not Available
Firmware Version | 2021.11.22.0-1
Frequency | 868
Region Plan | EU868
Variant | Nebra Indoor Hotspot Gen 1

i think my nebra cant update the system

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [honor]
- OS: [android]

**Additional context**

**Comment by cokes518** [comment]
Hi, looks like this is a nebra issue and not related to the app. I'd recommend you reach out to them.
