### ISSUE TITLE
Discovery Mode Under Construction

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#1141]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/19331274/144330722-4196ee6e-af45-4975-b505-d9de0882dc7c.png">

a few changes:

1. Subtitle under "Discovery Mode" change to 
> Find out which Hotspots can hear you when you upgrade an antenna or change elevation.

2. Add a section above "Previous Sessions"
> Discovery Mode is undergoing a facelift after its impact on the Network outage on Nov 15. 
> This feature will be unavailable for the rest of 2021 and a reactivation date to be announced in 2022.

3. Remove "you're out of sessions for the day" at the bottom of the card.

**Comment by cokes518** [comment]
we will want to control this server side so we can update the message without an app release. 

other messaging can be what the new discovery mode limitations are as discussed in our meeting.

**Comment by PeterMain** [comment]
![Discovery mode](https://user-images.githubusercontent.com/3613880/144634004-30d7d962-b4b2-42fa-977b-8c923785e948.png)

may be too late, but i did a style pass on this.

**Comment by PeterMain** [comment]
![Discovery mode](https://user-images.githubusercontent.com/3613880/144635131-6ac2b245-80b3-41ca-8722-119903b1f5bb.png)

not sure if too late, but i did a style pass on this

**Comment by cokes518** [comment]
released in 3.8.5 with Pete's style pass
