### ISSUE TITLE
Hotspot transfer pending bobcat 300 miner

### ISSUE THREAD

**Issue by maxx2111** [helium/hotspot-app#1143]
Hello guys,

Got my Bobcat 300 miner for a few weeks now. Everything is working as it should. 
Only issue is that i still have my transfer from previous owner which is pending on the app. On his app everything is fine, nothing pending.

Can someone help me with this ?

Shallow Hemp Ram

Thanks in advance !!

![image0](https://user-images.githubusercontent.com/95405255/144379104-3f38814f-a6dc-44b1-aadb-7a0aac253d7d.jpeg)

![image1](https://user-images.githubusercontent.com/95405255/144379257-08fe0885-cee2-487e-b695-1bbb75a503c5.jpeg)

**Comment by cokes518** [comment]
is this resolved?
