### ISSUE TITLE
Unable to transfer hotspot to new owner due to lack of recent beacon or witness activity

### ISSUE THREAD

**Issue by edstewbob** [helium/hotspot-app#1150]
When trying to transfer ownership of a hotspot an error message can occur "Hotspot has not had Beacon or Witness activity in the last 1200 blocks" and the Send Transfer Request is grayed out.
If a hotspot has been sold and is not active for a while there is no way to transfer it to a new owner since the location will likely changed and beaconing or witnessing will not occur until the new location is asserted by the new owner. The new owner should have the ability to setup and update the location information similar to what is done for a new hotspot. This prevents the easy transfer of hotspots to new owners at new locations which can inhibit the growth of the Helium network.
![Screenshot 2021-12-02 at 9 10 26 PM](https://user-images.githubusercontent.com/14189782/144540236-c66727e9-fd48-4e85-8c84-c01207b40d27.jpeg)

**Comment by NetScr1be** [comment]
Same issue x 35 hotspots

**Comment by cokes518** [comment]
The buyer can plug it in and give it internet which will sync the Hotspot. Once it's fully synced, it will create a challenge, regardless of its asserted location. That's considered activity and you can transfer it then.

**Comment by RicardoCedeno10** [comment]
Hello, I am at that point but it still does not create any challenge and it is well located connected via ethernet at 20 m height, it still does not perform any activity nor can I change location since I bought it second hand, it has 6 days sync in the blockchain. What I can do?
