### ISSUE TITLE
Unable to send hnt with hotspot-app on android

### ISSUE THREAD

**Issue by mschrisran2** [helium/hotspot-app#1151]
Issue:
I'm unable to send hnt to another wallet through the hotspot app, press send, after a couple seconds receive error "There was an error submitting this transaction. Please try again"

Steps:
1) go to send HNT
2) Scan qr code with recipient address, amount, and memo
3) press send hnt
4) wait ~2 seconds
5) receive error "There was an error submitting this transaction. Please try again"

Expected:
Send HNT should confirm transaction and send to destination wallet.

**Screenshots**
Unable to screen shot due to new policy.

Android Phone
Samsung Galaxy s20+
v3.8.4 app

**Comment by cokes518** [comment]
Thanks for the report. We’re taking a look at the API

**Comment by cokes518** [comment]
API is fixed up. Payments work again.
