### ISSUE TITLE
failed to onboard the hotspot - {invalid,unknown_gateway}

### ISSUE THREAD

**Issue by Milesight-IoT** [helium/hotspot-app#1154]
we got some customers' feedback of failed to onboarding after several retrys.

Here are the transcation details

![image](https://user-images.githubusercontent.com/75722092/144994634-377a280f-92cb-4717-8ae2-12d21baad04c.png)

```
 "data": [
    {
      "updated_at": "2021-12-07T07:39:47.926727Z",
      "type": "assert_location_v2",
      "txn": {
        "type": "assert_location_v2",
        "staking_fee": 1000000,
        "payer": "13H6RpJojJjkqPRfzdrFBDbpYw4b3A6HyMxgGFRgXf31Nuwq4xJ",
        "owner": "14KUti5jv1A8om6YHp2tYQcCY8mrkGhTDx8n7vCax7yvCYKpF8W",
        "nonce": 1,
        "location": "8c43a1220a2d5ff",
        "hash": "HMRNeUV77HH5dvyIX5OUM44VZeyfvl99CStf2qLIZ3E",
        "gateway": "112u24LA2b7cpmJKpxU7BpsW8cXU9xPowajhqpi3ZUCwPeVNDaWg",
        "gain": 20,
        "fee": 55000,
        "elevation": 35
      },
      "status": "failed",
      "hash": "HMRNeUV77HH5dvyIX5OUM44VZeyfvl99CStf2qLIZ3E",
      "failed_reason": "{invalid,unknown_gateway}",
      "created_at": "2021-12-07T07:39:07.638922Z"
    },
    {
      "updated_at": "2021-12-07T07:39:46.198242Z",
      "type": "add_gateway_v1",
      "txn": {
        "type": "add_gateway_v1",
        "staking_fee": 1,
        "payer": "13H6RpJojJjkqPRfzdrFBDbpYw4b3A6HyMxgGFRgXf31Nuwq4xJ",
        "owner": "14KUti5jv1A8om6YHp2tYQcCY8mrkGhTDx8n7vCax7yvCYKpF8W",
        "hash": "GRkxC-6AwKOUpJJkna-7LcGiRctzfuZs17Gcr7_areE",
        "gateway": "112u24LA2b7cpmJKpxU7BpsW8cXU9xPowajhqpi3ZUCwPeVNDaWg",
        "fee": 0
      },
      "status": "failed",
      "hash": "GRkxC-6AwKOUpJJkna-7LcGiRctzfuZs17Gcr7_areE",
      "failed_reason": "{invalid,wrong_txn_fee}",
      "created_at": "2021-12-07T07:39:06.148594Z"
    },
```

This is the device's info in helium API. 
![image](https://user-images.githubusercontent.com/75722092/144994432-666c62de-846e-4f9c-a50b-e0e76130fc72.png)

From customer's app info, he get this:
![image](https://user-images.githubusercontent.com/75722092/144994818-e1cfe959-2f82-49f4-84a1-cb2500b50e8d.png)

Most of the reply in discord are invalid, and just recommend to wait and try again and again.
This customer has re-try 3 days, still not work. 

Can you offer a solution to fix this?

Miner version: 2021.12.06.0
Helium app version: IOS 3.8.4

**Comment by cokes518** [comment]
that hotspot is already onboarded. and we should discuss this in your internal maker channel on discord. no need to create issues on GitHub for this.
