### ISSUE TITLE
Endless loop onboarding miner with no asserted location error

### ISSUE THREAD

**Issue by Rekt-1337** [helium/hotspot-app#1159]
**Describe the bug**
My miner is onboarded with a ''no asserted location'' . Not sure why since i asserted it but that's not the problem i guess.

When i try to click the name of the miner inside the app, remove it and then assert it again. i cannot click on the miner.

Also onboarding it again by going through the initial bluetooth process, shows the landing of ''this miner has been already onboarded''

**To Reproduce**

1. Go to app
2. Click on miner

**Expected behavior**
Able to assert miner again by clicking on it and/or assert properly from the get go

**Screenshots**
https://gofile.io/d/dZ12Om
https://prnt.sc/22eo5i3
https://prnt.sc/22eo7qw

- Device: [Realme GT 5G]
- OS: [Android 11]
- App Version [ 3.8.4]

**Comment by RosenKaramanov** [comment]
I have exactly the same problem

**Comment by cokes518** [comment]
@Rekt-1337 can you update to 3.8.5 and try again?

**Comment by cokes518** [comment]
you don't need to pair with the Hotspot to update location.

**Comment by Rekt-1337** [comment]
@cokes518 yes it worked
