### ISSUE TITLE
transfer hotspot cancel problem (I request you to clean my board.)

### ISSUE THREAD

**Issue by zqrrq** [helium/hotspot-app#1161]
Hello, I wanted to make a transfer hotspot to the recipient's wallet. but a bug has occurred. Here is my own wallet address. and I can't cancel this action 'API ERROR'. I think you need to reset the whole board.

my wallet : 13aYPYMLfMR4dQoiZAjHgKPKJzTrvVeP4fnVkE24Fab9GUAt8j7
My hotspot address that I can't transfer: 112ihqKwTwLajDHSjYCwBzrgg8aguYsLrozhXQjQSoLxE5McjTRW
wallet address I want to send: 14PozXhjjeWJEd8Fr9jnqBURxxWNP2E9Nj9ZHYUQRad9pP4aEUg

![Screenshot_1](https://user-images.githubusercontent.com/78285232/145706988-8d4076ed-40c3-485b-9a74-7ee045ec1286.png)

**Comment by tyler-whitman** [comment]
@zqrrq can you give this another try.
