### ISSUE TITLE
Enhancement.. Hex check upon Assert hotspot

### ISSUE THREAD

**Issue by MagNaMan** [helium/hotspot-app#1166]
When someone asserts a hotspot it does a quick check in hex and pops up with message "This location my not be optimal installation, Can we help you find a better location?" or warn them like explorer does that it may be Suboptimal Transmit Scale

**Comment by cokes518** [comment]
I responded to the same request here: https://github.com/helium/hotspot-app/issues/1180#issuecomment-1021590759
