### ISSUE TITLE
[Feature] Implement multiple wallet functionality

### ISSUE THREAD

**Issue by andreiguzga** [helium/hotspot-app#1167]
Allow the App to generate/import multiple wallets and allow the user to set an active wallet. 

I already forked the repository and started working on it. You can assign this task to me. I added this in case someone may want to start working on something like this and having it as an issue here people will know that an implementation was started in this direction.

Thanks

**Comment by andreiguzga** [comment]
I was thinking of adding a separate section under the Settings page. A section that will allow users to Manage/Create/Import additional wallets.

From the manage section, a user will select his active wallet. This will replace the mnemonic, address, keypair in the secretStore with the ones for the newly selected wallet.

Also, for storing additional wallets, I added a new secretStore key "wallets" which will store all wallets info. I think a limit on the number of wallets that you can have will be needed so that the secretStore won't get filled up.

If anyone has suggestions about this implementation please let me know.

**Comment by cokes518** [comment]
We're actually working on something similar to this and it may not be worth your time and effort. apologies on the delay on this.

**Comment by cokes518** [comment]
even as a thought exercise, once you have multiple accounts and wallets, you'd need to properly and safely switch between accounts, decide how you want to display seed phrases, which account will sign transactions, how do you log out of one account and not another, how to handle notifications as those can go to specific accounts. 

just wanted to put that out there as it's not as straight forward as it may seem.

**Comment by andreiguzga** [comment]
Yeah. After diving a bit more into the code I realised it's quite a bit of work to make it fully functional.
