### ISSUE TITLE
Hotspot transfer pending - cannot transfer - previously described 

### ISSUE THREAD

**Issue by Babapat** [helium/hotspot-app#1173]
Hotspot was successfully transferred from previous wallet and shows in new wallet.
Cannot transfer hostspot it says “transfer pending. Tap to cancel” 

when tapped it says “cancel hotspot transfer l, there is a pending hostspot transfer to ‘address’ for hostspot name”

when tap on cancel it says “unable to cancel transfer, no respond from API”

hotspot name: harsh sage lobster

**Comment by Babapat** [comment]
Similar bug issue as tickets #1161

**Comment by Babapat** [comment]
@tyler-whitman sorry, I hope you can help me out as previous users.

**Comment by Babapat** [comment]
@cokes518 hope you can help as there is another person waiting for transfer.

**Comment by Babapat** [comment]
@matthewcarlreetz

**Comment by Babapat** [comment]
![image](https://user-images.githubusercontent.com/96460196/146994305-8d228cf9-40e8-4065-8187-c112d0913f91.jpg)
![image](https://user-images.githubusercontent.com/96460196/146994354-06b68704-7f3b-41d1-9d5c-9e590c8d9062.jpg)

**Comment by cokes518** [comment]
This has been cleared.
________________________________
