### ISSUE TITLE
Manually Enter Wi-Fi Connection (hidden networks) 

### ISSUE THREAD

**Issue by vmipfdr** [helium/hotspot-app#1179]
When adding hotspots to your Helium Wallet, as you progess through the hotspot onboarding process, there is no way to manually enter a Wi-Fi network for the Hotspot to connect to.  The world is full of bad people, and a large portion of our community is focused on security.  However, one vulnerability in the onboarding process is the inability for users to add a hotspot to a hidden network.  In the app's current state (Build v.3.8.5) a user would either have to connect to the network via a hard connection, or by un-hiding a Wi-Fi network, adding the hotspot, then re-hiding the network.  

![image](https://user-images.githubusercontent.com/59590726/147166052-489f2d20-7f71-4b94-ba76-5c219afcd3fe.png)

**To Reproduce**

1. Go to add a hotspot
2. Proceed through the modal
3. Scroll through the available networks
4. See no ability for user to manually add network

**Expected behavior**
Add an option at the bottom (or top) of the network list where a user can manually enter network data to connect the hotspot to the network.

**Comment by vmipfdr** [comment]
actually an ER, not a bug.

**Comment by cokes518** [comment]
A few people have requested this enhancement in the past but we're unable to do this. The app only returns what the Hotspot (raspberry pi) can see. In the future, when hotspot makers introduce their own apps, it may be something they can accommodate.
