### ISSUE TITLE
Helium (Hotspot) does not work,  but Hotspot Utility works fine

### ISSUE THREAD

**Issue by shivad108** [helium/hotspot-app#1183]
hey guys,
the main issue is that the Helium (Hotspot) app will not work. it did when i setup my Bobcat 300, but now it just asks me to "create an account/import existing account". if i go to import existing account and put in my 12 pass phrase nothing happens, the app just sits there. for a few days after i setup the Bobcat initially it would work and ask for my 6 digit pin. but now all i get is the  "create/import" options. last week it came back to asking me for my 6 digit pin and when i went in and went through all the prompts it told me my miner was owned by someone else. wtf? but now it's back to only offering me "create/import" options when i open the app.

HOWEVER, the hotspot utility app works fine and does it's diagnosis. 

very weird. 

i don't get it. any suggestions?

**Comment by cokes518** [comment]
did you enter your 12 words correctly, in the exact order when you created your account? the utility app is just there for diagnosis. it's not a wallet.

it sounds like to me that you're having issues logging into your wallet with the 12 word seed phrase.

read through this and try again. https://docs.helium.com/wallets/app-wallet/twelve-words/ but this isn't a bug with the app so I'll have to close this issue.

**Comment by shivad108** [comment]
whowa! thanks for the quick response cokes. ya i understand the diff between the two. that's y this is so important, i can't get into my wallet. 

knowing about the correct spelling, yes, i've tried many, many, many, (keep counting) times. but like i said, i put in the 12 words and the app just sit's there. does nothing! nada, zip, zero. every time. 

but let me go to your link and see what it says. 

we'll chat again, thanks

**Comment by shivad108** [comment]
just read your link. nope, i'm sure!

**Comment by cokes518** [comment]
What app version are you using? What device? Second, find your bobcat on explorer and check the owner address and compare that with the address that you see in the app when logged into the 12 words. Do they match?
________________________________

**Comment by shivad108** [comment]
ahhhh... i just downloaded it again on my phone this morning (after doing a complete reset on my phone over weeks of doing this). so it should be the latest. (google play store doesn't have the version number but says it was last updated 12/07/2021). i am using a Motorola One 5G ace (it's like a google version of the orig Moto phone). but i don't think that's the problem cause my Hotspot Utility app connects right up and does it's diags thing. i can open the bobcat explorer and diagnoser, but i never wrote down the wallet address or anything about the wallet when i first set it up so have nothing to compare it with since I CANNOT OPEN HELIUM HOTSPOT except to get the create/import options.

**Comment by cokes518** [comment]
On the helium app, press import account and enter your 12 words. What happens after that?
________________________________

**Comment by shivad108** [comment]
repeated twice abouve: NOTHING, NADA ZIP.  i put in the 12 words and the app just sits there doing nothing.

**Comment by cokes518** [comment]
Then those 12 words do not generate a valid address on the helium network. You have a mistyped word somewhere.
________________________________

**Comment by shivad108** [comment]
btw, the diagnoser shows the public key (all it gives me) and the Hotspot explorer give's me the same pub key

**Comment by shivad108** [comment]
WHOA, WHOA, WHOA!!!
while we've been doing this i got my mentor on all this on the phone. after a big discussion, he told me about putting in the 12 words AND THEN HITTING THE WORD THAT APPEARS BELOW THE INPUT LINE. never did that. so i did now and BAM opens right up (put in my 6 digits, etc.)

thanks so much for trying and putting up with this idiot.

u can close this now.
