### ISSUE TITLE
No transactions in activity list despite mining activity and payment

### ISSUE THREAD

**Issue by Free118USA** [helium/hotspot-app#1187]
my helium app shows zero earning in home screen but shows the hotspot and when i go in the "my wallet" tab shows earning but there's no transaction history or anything i have  tried to move fund about 0.45 HNT first time went to pending and failed the reason was invalid, insufficient_balance. tried again and after getting check mark doesn't do anything but after 5 minutes it showed in notification that failed and one try cleared and went through one still no history though . i have updated my antenna and it went through very well. just scared maybe i lose my access to everything. please advise thanks

**Comment by cokes518** [comment]
did you get your Hotspot from emrit? can you show a screenshot of the Hotspot page and let us know your wallet address?

**Comment by Free118USA** [comment]
13qtycJ5d9DhTH3n7VUeZwVTTbxyUtPUr88CU21upgu1kgSFHtn
![22D64CF7-844A-4B81-B1CB-3209AFEDCBFA](https://user-images.githubusercontent.com/97179879/148258371-7b1ea1b3-d6ac-48a8-bc54-d557831c8fa3.jpeg)
![250C4C38-D36B-48BE-AE24-39C419C56047](https://user-images.githubusercontent.com/97179879/148258379-495e2411-d555-40fc-92e0-efbeb017e1ce.png)

**Comment by cokes518** [comment]
you sent HNT to this account. 136uonwTv7h4JHvHDYUsJwp2HAopLk7LmMYki7me2MD8VnmPGFK
https://explorer.helium.com/accounts/136uonwTv7h4JHvHDYUsJwp2HAopLk7LmMYki7me2MD8VnmPGFK

the payment went through. there's no issue here?

**Comment by Free118USA** [comment]
problem is it doesn't show anything in home screen that how much earned and also there's no history of transactions!

**Comment by tyler-whitman** [comment]
@Free118USA can you give this another try? We made some fixes on the backend that may have helped. If you still don't see activity, can you try logging out and back into the app (make sure to have your 12 words written down in the correct order).

**Comment by Free118USA** [comment]
Signing out and backing in resolved the problem. Thanks
