### ISSUE TITLE
Enhancment - Add an “open all” on explorer button to the app home page

### ISSUE THREAD

**Issue by rafael-leal-mccormack** [helium/hotspot-app#1203]
Hey everyone, I have a couple miners and it's a little annoying to go through each miner to open on the helium explorer in the browser. Would it be possible to add a button or overflow menu that opens a drop down with the option to "open all in explorer" on the main page that shows all miners?

**Comment by cokes518** [comment]
initiated from the app? I'm not sure what you'd get from this.
