### ISSUE TITLE
Cant transfer my hotspot. Cant cancel pending transfer

### ISSUE THREAD

**Issue by kingmax1999** [helium/hotspot-app#1218]
Hotspot was successfully transferred from previous wallet and shows in new wallet.
Cannot transfer hostspot it says “transfer pending. Tap to cancel”

when tapped it says “cancel hotspot transfer l, there is a pending hostspot transfer to ‘address’ for hostspot name”

when tap on cancel it says “unable to cancel transfer, no respond from API”

hotspot name: Flat Brick Moth

Thanks a lot.

**Comment by cokes518** [comment]
this has been cleared. you should be able to transfer again.
