### ISSUE TITLE
add hostspot error  read Characteristics

### ISSUE THREAD

**Issue by tuannt1531** [helium/hotspot-app#1219]
**Describe the bug**
 I have a issue with add and scan hostspot to helium app. I have install gateway-config packet and start it on my raspberry pi, i can turn on advertise and scan my raspi on helium app. But when I touch to connect with hostspost, it's have issue "Characteristics 7731de63 read false", 
- i tried changing the wifi name to no non-ascii characters or turning off the wifi connection on the pi completely but all failed, i tried using the app NRF connect to connect and read this characteristic, it still reads, but helium app error. can someone help me see where the error is? thanks!
**Screenshots**
![image](https://user-images.githubusercontent.com/14306221/150628795-d5143183-af06-4d89-9998-00806acbdf36.png)
![image](https://user-images.githubusercontent.com/14306221/150628802-2a7dc76f-93c3-4f17-b84f-9411d8243a87.png)

[Update]
i solved this error, it was because my gateway-config package had error, however, i got another error: onboarding error, invalid_onboarding_addres.
![29387](https://user-images.githubusercontent.com/14306221/151087846-73fa25a8-a89a-4eb6-be6b-b9fc4f7c6d23.jpg)

**Comment by cokes518** [comment]
what's the name of your wi-fi network?

**Comment by tuannt1531** [comment]
- My wifi is: abc
- i solved this error, it was because my gateway-config package had error, however, i got another error: onboarding error, invalid_onboarding_addres.
![29387](https://user-images.githubusercontent.com/14306221/151087656-0838212b-4942-4471-921d-098c44d669e4.jpg)
s

**Comment by cokes518** [comment]
is this a DIY Hotspot?

**Comment by tuannt1531** [comment]
yes, we use SX1302 LoRaWAN Gateway HAT + raspberry Pi 4, Can you help me pinpoint which packet on the hotspot is the problem for me to check?

**Comment by cokes518** [comment]
you're trying to onboard a hotspot that's not on the onboarding server. only approved hip-19 makers can add hotspots to the onboarding server.

if you're adding a data-only hotspot, you cannot add it via the app. this is CLI only. 

if you're a pending hip-19 maker, please talk to Christina.

**Comment by tuannt1531** [comment]
yes, thanks @cokes518
