### ISSUE TITLE
No response from api .

### ISSUE THREAD

**Issue by ch1oru** [helium/hotspot-app#1225]
My hotspot is in a pending transfer , and when i want to cancel is says no response from api , i never want to make a transfer, i dont know why it have that mesage , is say tap to cancel and when i do that it says no response from api , please help me. 
https://explorer.helium.com/hotspots/112wV2ng9eDKBfrso8LCaRcro4QwWeireREm5b41o3jt5jBh5GFS , this is my hotspot : Tart Pewter Alligator .

**Comment by cokes518** [comment]
we've cleared the pending transaction.
