### ISSUE TITLE
Acces account keystore file

### ISSUE THREAD

**Issue by cheloneee** [helium/hotspot-app#1226]
Hello
can someone help me?
Is it possible to enter the wallet with keystore files?
I have all the words to enter the account but do not let me. He says there is no account for these words.
I found the keystore.json file
Is it possible to log in with him?

**Comment by cokes518** [comment]
That's not possible. the keystore file is encrypted. you need your 12 words in the correct order to access your account. If there's no account for the 12 words you entered, it means those words are invalid and you've got the wrong words.
