### ISSUE TITLE
Hotspot transfer pending - cannot transfer

### ISSUE THREAD

**Issue by ETLin** [helium/hotspot-app#1231]
**Describe the bug**
Hotspot was successfully transferred from previous wallet and shows in new wallet.
Cannot transfer hostspot it says “transfer pending. Tap to cancel”

when tapped it says “cancel hotspot transfer l, there is a pending hostspot transfer to ‘address’ for hostspot name”

when tap on cancel it says “unable to cancel transfer, no respond from API”

hotspot name: Eager Coconut Fish

112BAm4aVav8dNk9tSXVdLEfzHLpV6BeWwNS5hY6nDrnsdmRrsE9
![unnamed (1)](https://user-images.githubusercontent.com/4660939/151742285-c93379a5-e8d7-4cb0-93f0-05a404c6278f.jpg)
![unnamed (2)](https://user-images.githubusercontent.com/4660939/151742302-feae5b6f-4b5a-464c-9a7d-f79bb53c4ebc.jpg)

BTW there is the payment not create by myself. i afraid had been robbed. 
payment id: AGOz5wBxBYH0RY3EoXYbfNeTmdd4oJJZi7-GPmN8LJc

**Comment by ETLin** [comment]
![unnamed (3)](https://user-images.githubusercontent.com/4660939/151742574-42ebdb10-9b50-497f-90a7-51c00f492abe.jpg)

**Comment by cokes518** [comment]
this has been cleared. you should be able to transfer again.

**Comment by aradtat** [comment]
Hi . What can i do ?? 
![5961C1D4-26D8-4834-BA4A-A9BF531A4260](https://user-images.githubusercontent.com/60825287/162603505-04878d88-5cce-4962-ac4a-097f515fa12b.png)
Please help me

**Comment by aradtat** [comment]
![2BBB0E42-33A5-49F7-9FB9-C0D9B8A709D3](https://user-images.githubusercontent.com/60825287/162604318-10dc9b2d-2851-4924-9444-01a605031232.png)

please help me?
