### ISSUE TITLE
Multi-entering for 1 Confirmation word

### ISSUE THREAD

**Issue by MykhailoMashchenko** [helium/hotspot-app#1232]
**Describe the bug**
Multi-entering for 1 Confirmation word

**To Reproduce**

1. User opens app
2. Tap to the Import Existing Wallet button
3. Enter 12 valid Confirm words
4. Tap to the specific word on the Confirmation list
5. Enter one word in all fields
6. Submit Seed phrase with the one word in all fields

**Expected behavior**
User should be able to enter unique words for Confirmation action only 

**Actual behavior**
There is possibility to enter the same Word 12 times and Submit it

**Screenshots**

**Smartphone (please complete the following information):**

- Devices: Any iphone or android evice

**Comment by cokes518** [comment]
I'm not understanding the problem here. if you enter the same 12 words, go ahead?

**Comment by cokes518** [comment]
closing as not an issue.

**Comment by MykhailoMashchenko** [comment]
Is it possible that there is account with same 12 words created (FIX entered 12 times), or does sign up behaves not as expected when we enter SAME pass word 12 times ?
