### ISSUE TITLE
Deep link from Maker app not working on Android 12 devices

### ISSUE THREAD

**Issue by lxie123** [helium/hotspot-app#1237]
**Describe the bug**
on Android 12 devices, when linking to helium app with our maker app, it opens chrome instead and we get a 404. With android 11 devices, things seem okay. It seems like helium app is not setting itself as default for opening these kind of links on Android 12.

**To Reproduce**
1. Launch maker app on android 12 devices
2.  link wallet
3. No prompt to open with helium
4. Chrome opens with 404

**Expected behavior**
Helium app should open with request to link wallet

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Pixel 5
- OS: android 12
- App Version: V3.9.0

**Additional context**

**Comment by lxie123** [comment]
the  supported links is missing on Android 12
Android 12 screenshot:
![image](https://user-images.githubusercontent.com/3496888/152454488-790cd13e-0a98-4b1a-8771-e887ec84b87f.png)

Android 11 screenshot:
![image](https://user-images.githubusercontent.com/3496888/152454510-7a0d3ccb-9a66-4fd3-b6e8-497f1b8632b6.png)

**Comment by leadtekjun** [comment]
same for me, any solution?

**Comment by leadtekjun** [comment]
the default link for maker app to login is: https://www.helium.com/link_wallet?appName=Maker%20App&callbackUrl=makerappscheme%3A%2F%2F&requestAppId=com.maker.makerapp
do we need to change some params in the link?

**Comment by leadtekjun** [comment]
oh, seems like the latest commit fixed this, waiting for the release.

**Comment by browanofficial** [comment]
Has the bug been fixed?
I use Samsung S21 FE  Android 12. 
I have this problem also.

**Comment by ChunChiehKung** [comment]
Hi Sir,
I still can see this issue.
Is there any updates for it?
Thanks a lot.

**Comment by adisaro** [comment]
guys, this bug is preventing people with android 12 to use the maker app, are you aware of this?

**Comment by tyler-whitman** [comment]
> guys, this bug is preventing people with android 12 to use the maker app, are you aware of this?

We found the issue and it will be resolved soon, auto verification of our app links was failing. In the meantime users are able to manually verify the app link until the auto verification is working properly.

![ezgif-4-6d076143f7](https://user-images.githubusercontent.com/6345962/164815236-3ddcb887-6c1c-4036-a391-7fd814af3dbd.gif)

**Comment by tyler-whitman** [comment]
This is now resolved, the verified link is working properly on install. If you are still having issues please check the deeplink settings shown above and add helium.com as a link or reinstall the helium app which will check the verified links again and enable helium.com.
