### ISSUE TITLE
Helium miner was highjacked while I was setting up the SenseCap M1 via the app

### ISSUE THREAD

**Issue by edenation** [helium/hotspot-app#1239]
**Describe the bug**
Helium miner was highjacked while I was setting up the SenseCap M1 via the app

**To Reproduce**
1) Created an account on iPhone in Jan 2022
2) Saved all the seed word phrases in sequence
3) Received SenseCap M1 Miner and tried setting up 29 Jan 2022
4) Faced the issue in the screenshot and contacted SenseCap for help
![Hotspot issue](https://user-images.githubusercontent.com/99061760/152627950-70b0819c-6566-4e31-9af3-379e4e37fbce.PNG)
5) Saw the following failed transactions in the app:
![Failed Transaction 1](https://user-images.githubusercontent.com/99061760/152627801-25877165-ed83-4449-8e83-453115be030b.png)
![Failed Transaction 2](https://user-images.githubusercontent.com/99061760/152627802-0ce0d0de-db02-4b74-90b6-22b2af5a69c8.png)
6) Subsequently, the Hotspot was created with the name "Sour Syrup Hare"
7) Opened the SenseCap dashboard
8) Realized that the Hotspot owner wallet address is 12xAQm9xHgqdZkQL8yAsngrzCTcqNgaAoeG5punU7Bia5ZHWyNn
9) The Hotspot owner wallet address is not mine
10) Double checked and my Helium App wallet address is 139pimh5tdHv6kHpKisN659PdyqtLtD7ZLf7Ed2xRvrwVPV62Zp
11) The person requested transfer of ownership of the Hotspot, which was rightfully mine, demanding 100 HNT
 ![Demand 100 HNT](https://user-images.githubusercontent.com/99061760/152627992-4e29658c-5d5f-487c-938d-018139eb70ca.png)
12) I switched off the miner to prevent further mining
13) Please help me in any way possible

**Expected behavior**
The setup should face no failed transactions. It seems that my miner was "highjacked" while I was setting up and now the person is demanding 100 HNT to transfer the ownership back to me.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [iPhone X]
- OS: [iOS 15.2.1]
- App Version [3.9.0]

**Additional context**
I did not share my 12 words with anyone and have done the set up process correctly, however now my Hotspot has been highjacked and that person is demanding 100 HNT from me to transfer back the ownership of the hotspot to me. Please help as I am feeling really helpless.

**Comment by cokes518** [comment]
I'm sorry this happened to you, but this is not an app bug. I would recommend you reach out to SenseCap to understand if you received a resold Hotspot. 

According to explorer history, the listed owner of this Hotspot (12xAQm9xHgqdZkQL8yAsngrzCTcqNgaAoeG5punU7Bia5ZHWyNn) originally added this Hotspot to the chain and asserted it in Singapore on Jan 29. Looks like the wallet address 12xAQ... is the rightful owner of this Hotspot as it was added and asserted to the chain with their private key. https://explorer.helium.com/hotspots/112d7yxCSH1FAaDn29MiFMmmXBXY7sNbm2vvDRzdn1wASDMhjHeV/activity

<img width="513" alt="image" src="https://user-images.githubusercontent.com/19331274/152628441-3e7e6483-3097-4a12-8cc5-9f8aca872547.png">

You say you don't know who 12xAQ is.. are you sure? you received HNT from this address 26 hours ago. https://explorer.helium.com/txns/vAwOWJP6Zi2NtNN1IL3wcibEmpotNurIXxF0mQueXYc

Either way, this is not an app issue. Hopefully you can resolve this.
