### ISSUE TITLE
Hotspot transfer pending - stuck 

### ISSUE THREAD

**Issue by cosmindut** [helium/hotspot-app#1245]
![IMG-20220211-WA0002](https://user-images.githubusercontent.com/99751517/154110516-f19606ac-21c4-4ec4-a2f8-7ce4d009ed42.jpg)
![IMG-20220211-WA0001](https://user-images.githubusercontent.com/99751517/154110525-79847a99-4223-4778-bbf2-bb421fc7f4af.jpg)
![IMG-20220211-WA0000](https://user-images.githubusercontent.com/99751517/154110529-d28f2f91-7355-40b2-b1fd-aa058bf70188.jpg)

Hello. I have a problem transferring a hotspot and is stuck, I can't do nothing over two weeks. Thank you 🙏

**Comment by tyler-whitman** [comment]
@cosmindut this should work now, also if you update your app to the latest there is a simplified transfer process that no longer requires the buyer's acceptance. The transfer will complete instantly from the sellers side.
