### ISSUE TITLE
User isn't able to see transactions in Payment transactions tab which are available in All transactions tab

### ISSUE THREAD

**Issue by MykhailoMashchenko** [helium/hotspot-app#1246]
Pre-conditions:
android and ios applications

**Steps to reproduce:**
1) Go to the Wallet
2) Pay attention to the All Activity tab
3) Pay attention to the Payment transactions tab

**Actual result:**
1) User is able to see Received transactions in the tab ALL Activity for current day but can’t see it transactions in the Payment transactions tab

**Expected result**
User should be able to see the same Payment transactions in the tabs All Activity and Payment transactions
All Activity response
`{
"cursor": "",
"data": [{
"fee": 35000,
"hash": "lv8vNTYeCNbI5MCkllRYbuMN-tuYMiLbMdIwVISjK2s",
"height": 1207333,
"nonce": 14,
"payer": "14RWXwQ1WTusaoVGud2oApPnqzLCzBxyqFiUArmtFDbqkFsxW81",
"payments": [{
"amount": 7,
"memo": "MSBmZWIAAAA=",
"payee": "13BQRpMXJEUvN8CahBesSGVAEBKmc2aTepcWmJceo8AZB7du48Y"
}],
"time": 1643705667,
"type": "payment_v2"
}, {
"fee": 35000,
"hash": "LInpt_OLO5ZhvbHkNi5T97CpO-GP_gNI8UXRQApOD2I",
"height": 1207354,
"nonce": 15,
"payer": "14RWXwQ1WTusaoVGud2oApPnqzLCzBxyqFiUArmtFDbqkFsxW81",
"payments": [{
"amount": 8,
"memo": "OAAAAAAAAAA=",
"payee": "13BQRpMXJEUvN8CahBesSGVAEBKmc2aTepcWmJceo8AZB7du48Y"
}],
"time": 1643706955,
"type": "payment_v2"
}, {
"fee": 35000,
"hash": "zGRfGBXIAsGJs5jaSHzCDhl341IPcZKv9zEE-1dSglU",
"height": 1207375,
"nonce": 16,
"payer": "14RWXwQ1WTusaoVGud2oApPnqzLCzBxyqFiUArmtFDbqkFsxW81",
"payments": [{
"amount": 90000,
"memo": "MDEgZmViAAA=",
"payee": "13BQRpMXJEUvN8CahBesSGVAEBKmc2aTepcWmJceo8AZB7du48Y"
}],
"time": 1643708279,
"type": "payment_v2"
}]
}
 `

Payment Transactions response
`{
"cursor": "",
"data": [{
"fee": 35000,
"hash": "X2A8GRHdEKbyk3KCPyh3EtYUxsyMBtbK2bDwaoODu0w",
"height": 1206312,
"nonce": 13,
"payer": "14RWXwQ1WTusaoVGud2oApPnqzLCzBxyqFiUArmtFDbqkFsxW81",
"payments": [{
"amount": 4000,
"memo": "NAAAAAAAAAA=",
"payee": "13BQRpMXJEUvN8CahBesSGVAEBKmc2aTepcWmJceo8AZB7du48Y"
}],
"time": 1643638138,
"type": "payment_v2"
}]`

**Comment by cokes518** [comment]
is this still an issue?

**Comment by cokes518** [comment]
closing as submitter has not responded. please file a new issue if it's still a problem.
