### ISSUE TITLE
Transaction Details > View on Block issue

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#125]
Steps to repro:
1. open a transaction
2. tap view on block
3. opens web page that results in 500.

This is because there is a comma in the block number.
https://explorer.helium.com/blocks/693,577
![IMG_74ADF855B0F3-1](https://user-images.githubusercontent.com/19331274/106342424-bb5b5800-6255-11eb-836b-d6118d0d858a.jpeg)

**Comment by tyler-whitman** [comment]
Ill fix this one
