### ISSUE TITLE
App stops after selecting a hotspot from list

### ISSUE THREAD

**Issue by zl3ag** [helium/hotspot-app#1251]
**Describe the bug**
App stops on selection of a hotspot from list.

**To Reproduce**

1. Go to 'Home Screen'
2. Click on any hotspot on list.
3. screen clears then reports "Unfortunately, Helium has stopped.", with an offer to send a report to the phone manufacturer. "view summary" option requires the user to agree to a legal agreement with Google. So that's a non-starter.

**Expected behavior**
Not sure, it always crashes.

**Smartphone (please complete the following information):**

- Device: Mi 
- OS: Android
- App Version v3.10.0

**Additional context**

**Comment by cokes518** [comment]
please update to 3.11 and let us know if it's reproducible. thanks

**Comment by heman268** [comment]
Hi any fix both of my devices have the same problem (3.11)

**Comment by cokes518** [comment]
closing, no further response from original submitted. please open a new issue if this is still happening.
