### ISSUE TITLE
Incorrect earning values for default selected time range

### ISSUE THREAD

**Issue by snip** [helium/hotspot-app#1254]
**Describe the bug**
For a selected hotspot default selected time range is 14 days, but earning values displayed for this hotspot or network average are the one for 7 days.

**To Reproduce**

1. Open the app
2. Select an hotspot
3. Scroll down to see earnings
4. By default selected time range is 14D. Note "Your Earnings" and "Network avg" values.
5. Select 7D timerange. Values are not changing.
6. Select back 14D timerange. We now can see normal 14D time range values.

**Expected behavior**
14D is the default time range, so displayed earnings should also be the ones from 14D time range.

**Screenshots**
Not possible as application prevent this.

**Smartphone (please complete the following information):**

- Device: Poco F3
- OS: Android 11
- App Version: 3.10.0

**Additional context**
This behaviour seems not occuring if i switch from one of the hotspot to another one.
So to reproduce this we need to have the app not running at the begining.

**Comment by tyler-whitman** [comment]
Thanks for the report! This will be fixed in next release, app version 3.11.0.
