### ISSUE TITLE
Unable to transfer ownership if the hotspot has not been online for the last day

### ISSUE THREAD

**Issue by eiskop** [helium/hotspot-app#1259]
When trying to transfer ownership of a hotspot an error message can occur "Hotspot has not had Beacon or Witness activity in the last 1200 blocks" and the Send Transfer Request is grayed out.

If a hotspot has been sold and is not active for a while there is no way to transfer it to a new owner since the location will likely changed and beaconing or witnessing will not occur until the new location is asserted by the new owner. 

The new owner should have the ability to setup and update the location information similar to what is done for a new hotspot. 

Current sopluition prevents the easy transfer of hotspots to new owners at new locations which can inhibit the growth of the Helium network.

**Comment by cokes518** [comment]
you need to plug it in to prove that it has participated in proof of coverage. connect it to internet and wait. closing since this is not an app bug.
