### ISSUE TITLE
Hotspot ownership transfer

### ISSUE THREAD

**Issue by rickriis** [helium/hotspot-app#1260]
I bought a helium hotspot from a previous owner and now he is having an issue transferring to me.  If he is getting the message "Hotspot has not participated in proof of coverage in the last 1200 blocks. Unable to proceed with transfer", do I need to ship it back to him?  I have it plugged in at my location, but not sure if it will continue trying to participate and work this out.  The unit was originally in Hawaii and now is in Texas.

**Comment by Skrtatzylords** [comment]
I have the same problem. Any solutions?

**Comment by rickriis** [comment]
> I have the same problem. Any solutions?

So for me, the used bobcat that I bought I ended up sending it back to the person that sold it to me.  I did read a thread where someone basically faked out the helium app, but changing the address to be the previous address and was able to somehow change the owner.  I don't trust doing things like that though, it just seems risky to me.  In terms of buying a used hotspot, if the previous owner doesn't have experience transferring, I wouldn't purchase it.

**Comment by Skrtatzylords** [comment]
We solved it! The owner just run the Miner. Then it generated new entries in the blockchain. After that, I as the seller, could transfere the Miner via the Helium Wallet App.

**Comment by rickriis** [comment]
> We solved it! The owner just run the Miner. Then it generated new entries in the blockchain. After that, I as the seller, could transfere the Miner via the Helium Wallet App.
> […](#)
> Am 04.03.2022 um 16:48 schrieb rickriis ***@***.***>: ﻿ I have the same problem. Any solutions? So for me, the used bobcat that I bought I ended up sending it back to the person that sold it to me. I did read a thread where someone basically faked out the helium app, but changing the address to be the previous address and was able to somehow change the owner. I don't trust doing things like that though, it just seems risky to me. In terms of buying a used hotspot, if the previous owner doesn't have experience transferring, I wouldn't purchase it. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

That's great man.  I ended up purchasing a Rak V2 (used) from another person (ebay), but this guy knows about the transfer of ownership.  The other good part for me, is the bobcat I bought was about $900, but this Rak sold for much less ($540).  Good luck to you

**Comment by cokes518** [comment]
looks like it's resolved. closing
