### ISSUE TITLE
Require Entering 12 Words to Sign Out

### ISSUE THREAD

**Issue by Ryan-Goldstein** [helium/hotspot-app#1278]
We've seen numerous instances recently of users signing out of the app, confident that they have their 12 word seed phrase correct and in the right order, but when they attempt to sign back in, it's apparent that they did not save them properly.

The improvement suggestion is to require entering the 12 word seed phrase before being able to successfully sign out. If it's entered incorrectly, the user should be directed to Settings > Reveal Words.

An exception would be if the app is in Deploy Mode; the user should probably be permitted to sign out immediately in that case.

**Comment by Ryan-Goldstein** [comment]
Looks like #1281 will resolve this.

**Comment by cokes518** [comment]
to be released for 4.0.1 (currently in app store review). thanks for suggesting again!
