### ISSUE TITLE
Missing antenna options. 

### ISSUE THREAD

**Issue by acessford101** [helium/hotspot-app#1279]
**Describe the bug**
When using the helium app on Android, when viewing your hotspot you cannot update the antenna settings when pressing the gear. 

**To Reproduce**

1. Go to 'gear button:

**Expected behavior**
Expected to have the normal options to update location, antenna settings, transfer hotspot. 

**Screenshots**
App does not allow screenshot, only pair option is available. 

**Smartphone (please complete the following information):**

- Device: [e.g. fold 3
- OS: [e.g. android 11
- App Version [ 3.11.0

**Additional context**

**Comment by dobrevg** [comment]
@acessford101 
Do you have access to your wallet and your earnings? Is the wallet address the same as the linked one in the hotspot?

**Comment by acessford101** [comment]
Hello, yes. I uninstalled and reinstalled the app and the options are now
their and I was able to update my antenna information.

Thank you.
Adam.

**Comment by bysoclose** [comment]
{invalid,insufficient_balance} I get the error and the antenna is not updating 1 hnt in my wallet
