### ISSUE TITLE
"Hotspots Witnessed" section is reporting for the last 3 days but text is telling 5-days

### ISSUE THREAD

**Issue by riobah** [helium/hotspot-app#1285]
**Describe the bug**

`blockchain-http` module is updated to report the last 3 days witnessed counts, instead of 5 days with release 1.2.121 https://github.com/helium/blockchain-http/releases/tag/1.2.121

"Hotspots Witnessed" section is telling "over the last 5 days", but the value is actually for the last 3 days.

**To Reproduce**

Just check a random hotspot on Explorer. 

Explorer: https://explorer.helium.com/hotspots/11wu65LGrmmSsAMwoGtzDg2xTjs4iPZfNvuXQJrGb41e5AVRVDT
API server: https://api.helium.io/v1/hotspots/11wu65LGrmmSsAMwoGtzDg2xTjs4iPZfNvuXQJrGb41e5AVRVDT/witnessed

HTTP API change: https://github.com/helium/blockchain-http/commit/49ee76c5602a6271526bc0ce0582f8a208890a0a#diff-d8093e0584440e6498640985e7b519129691d9e4df4a2d8db197332208142170L394

**Expected behavior**
"Hotspots Witnessed" section should show "over the last 3 days"

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Irrelevant, happening for all devices
- OS: Irrelevant, happening for all devices
- App Version Verified on 4.0.1 

**Additional context**

**Comment by cokes518** [comment]
updated copy. closing.
