### ISSUE TITLE
"Confirm words on sign out" feature tedious for managing multiple accounts

### ISSUE THREAD

**Issue by deasydoesit** [helium/hotspot-app#1301]
re: PR #1281 

This addition makes it tedious to manage multiple accounts on the mobile app. 

Also, the interface for word entry is different than that for restoring an account and is more inefficient for data entry as you have to hunt and peck your words out of the blocks, rather than being able to explicitly type the words in.

Can we please either (1) roll this back, (2) allow for an opt out setting, or at the very least (3) allow for typed data entry similar to the restoration interface? 

Ty!

**Comment by deasydoesit** [comment]
Circling back here. I cannot emphasize enough how tedious this is.

**Comment by deasydoesit** [comment]
That sounds very promising! 

Is it available for iOS via the App Store yet?

**Comment by Ryan-Goldstein** [comment]
It's not on the App Store yet, but it's currently in an open beta and available through TestFlight: https://testflight.apple.com/join/SsAjbJEi

(Source: https://github.com/helium/wallet-issues-tracker)

**Comment by cokes518** [comment]
wallet app is now live.
