### ISSUE TITLE
Erori

### ISSUE THREAD

**Issue by Crisatian** [helium/hotspot-app#1303]
Hello, I also have a problem with the Bobcat 300 Swift Vinyl Badger

ObBobcat￼

15 dBi

⁇

38 m

￼112WdFa ... mYjWqQC￼13ZffnR ...

⁇

StatisticsActivityWitnessedNearby

It is broadcast on explorer and in the bober app and I don't know dc ??

**Comment by cokes518** [comment]
i don't understand your question. what's the problem?

**Comment by Crisatian** [comment]
why not remove hospices from hexagons that have not been active for months
or maybe even 1 year are offline. I have 2 hospices a year that are hex,
they are still active for 5.6 months, I repeat why don't you take them off
the map.

mar., 21 iun. 2022, 19:07 Coco Tang ***@***.***> a scris:

**Comment by Ryan-Goldstein** [comment]
Hotspots will always appear on the map, but they no longer affect transmit scale or anything else once they've been offline for more than about 2.5 days.
