### ISSUE TITLE
Update Antenna Details fails

### ISSUE THREAD

**Issue by FiSHonAUT** [helium/hotspot-app#1306]
I wanted to Update my Antenna Details like this:
![image](https://user-images.githubusercontent.com/73907969/168313871-0edc0382-f289-4d7d-bb9d-8928cdc31c89.png)
I only want to update the antenna details, not the location. Next step is to confirm:
![image](https://user-images.githubusercontent.com/73907969/168314019-32573c1e-3dd3-4973-8d24-26eacfed70d9.png)
After submitting it tries to update antenna details, but fails with this message:
![image](https://user-images.githubusercontent.com/73907969/168314648-0cafcc92-fb95-4804-800b-6299f66bb98f.png)
So it seems the app wants to update the Location and not the Antenna details...

**Smartphone**
Samsung Galaxy S10
Android 12
Helium App v4.0.1

**Comment by tyler-whitman** [comment]
@FiSHonAUT thanks for the report, would you mind sharing the hotspot name? Assert Location V2 is the correct transaction, it handles both location and the hotspot antenna data.

If you provide the hotspot name or transaction hash I can take a look at what went wrong, I would suggest trying the transaction again as well and see if you run into the same problem.

**Comment by FiSHonAUT** [comment]
@tyler-whitman thanks a lot! The hotspot name is Delightful Iron Fish.

**Comment by cokes518** [comment]
Did you try again? The attempt on May 13 should have gone through. It looks like the only thing you changed was the antenna gain.

**Comment by cokes518** [comment]
closing as issue has gone inactive. please reopen a new issue if it's still a problem.
