### ISSUE TITLE
No response from API - so can’t transfer miner 

### ISSUE THREAD

**Issue by MarkyMark80** [helium/hotspot-app#1311]
Trying to transfer ownership to new owner 
App states no API response 
![F19D088B-0F55-4FC9-B875-759DF70176A1](https://user-images.githubusercontent.com/46262389/169701502-ff34d9af-add9-4e13-82dc-97ccdf5fdb61.png)

address ending mgz is mine 
And want to transfer ownership to this address; 131TeCVr2NdSf6nHSX4zYvxsfDAijvUk3tTQyKr7nuEfrEv27M9

miner on explorer is here: 

https://explorer.helium.com/hotspots/112RFtUuURZzPeKDSgNugypGUi3KD753RJ7x5tMD9P7N9Jko7N3w

please can you help? Thanks 🙏

**Comment by MarkyMark80** [comment]
Hi - any chance can clear this for me?

**Comment by cokes518** [comment]
this is cleared. please update the app and try again.
