### ISSUE TITLE
Reveal Words button in app not showing the 12 phrases

### ISSUE THREAD

**Issue by zak53** [helium/hotspot-app#1313]
Hello,

The Reveal Words not showing any words, and i lost the paper, please help
![image](https://user-images.githubusercontent.com/5646724/171512470-d5ccf9ce-719d-46e0-b6b0-4e86935438d3.png)

Is it possible to retrieve the seeds from my data user file ?

**Comment by zak53** [comment]
> 

I have Xiaomi MI 9T Android 10 and i use app version v4.1.0

thank you in advance

**Comment by zak53** [comment]
The strange thing is even if I try to transfer hnt to my binance account, I have an error message "there was an error submitting this transaction. Please try again"

**Comment by cokes518** [comment]
It looks like the private key data was deleted from your phone somehow (maybe in a secure store location) and is now unrecoverable.

This makes sense because you're unable to send payment transactions because you do not have the private key (the file) to sign transactions.

unfortunately there is nothing we can do to recover this.

**Comment by zak53** [comment]
> It looks like the private key data was deleted from your phone somehow (maybe in a secure store location) and is now unrecoverable.
> 
> This makes sense because you're unable to send payment transactions because you do not have the private key (the file) to sign transactions.
> 
> unfortunately there is nothing we can do to recover this

Even with a backup of the phone ?

**Comment by cokes518** [comment]
you can try to restore the phone and see if that works. I'm not an android user so I cannot tell you if it will work.

**Comment by zak53** [comment]
can someone please tell me where the app store the private.key, because i am still login to the app but can't see the words of my wallet

**Comment by zak53** [comment]
Any developer ?
