### ISSUE TITLE
Transactions remain pending on blockchain

### ISSUE THREAD

**Issue by SkyDeBruce** [helium/hotspot-app#1314]
**Describe the bug**
All transactions linked to a specific hotspot remains pending even after close to 30 days, yet the hotspot is operating. The impact is that the hotspot's location, transfer or other related changes cannot be completed and will remain pending.

**To Reproduce**
See the following blockchains
upbpsbqOxOkX51L0_hXxBVN2SWTZtR2Q7zgnAkod_WQ
(Hotspot added to blockchain pending)

4f1LgeuIOzzjExPHF_0IdKeGQNeVBvYxE2KzpIUzHj8
(Hotspot change pending)

PI7xmzW-SRrx0oqPR43_oRoZBiO4bR09BGMw3vkNOv8
(Hotspot change pending)

BkqdpMRShSyvKe4rlm-PmMftrK0qH2y_a9pFImYsraQ
(Hotspot change pending)

**Expected behavior**
All pending transactions should be removed or completed and the hotspot fully registered to the blockchain

**Screenshots**
![Update location pending](https://user-images.githubusercontent.com/106956207/172125287-1e9b7231-eb9d-41ac-bc8d-b41eac5551ec.jpg)
![Update location pending](https://user-images.githubusercontent.com/106956207/172125311-522b7917-686c-4274-b3dc-284ba866d37d.jpg)

**Smartphone (please complete the following information):**
Latest OS and image loaded on hotspot, numerous restarts and status is unchanged. Other hotspot did register successfully with no issues .

**Comment by Ryan-Goldstein** [comment]
You're likely experiencing https://github.com/helium/hotspot-app/issues/1312, the solution for which is signing out and back in. If that does fix it, please give my issue a thumbs up and/or comment there to raise visibility.
