### ISSUE TITLE
Transfer Data Only hotspot not possible

### ISSUE THREAD

**Issue by EdBallou** [helium/hotspot-app#1315]
**Describe the bug**
Current requirements for transfer require proof of coverage participation. For Data Only hotspots, this is impossible.

**To Reproduce**

1. Onboard data only hotspot to wallet A
2. (Optional) Wait for successful data transfer
3. Attempt transfer to wallet B
4. Error message pops up that a hotspot can't be transferred without participating once in proof of coverage

**Expected behavior**
The transfer should work successfully. It is debatable on if successful data transfer should be required.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: latest
- App Version: latest

**Additional context**
Willing to test out whenever a fix is issued.

**Comment by tyler-whitman** [comment]
Hey @EdBallou thanks for the report. We have code in place that should allow data only hotspots to skip the activity check. Would you mind providing your data only hotspots name? I know you mentioned you are on the latest app version, but can you double check that you are on v4.1.0 (you can see the version at the bottom of the settings tab).

**Comment by EdBallou** [comment]
It is v4.1.0. I was getting a zero HNT fee for the transfer so I uninstalled the app, rebooted the phone, then installed the app again and got an actual fee for it. However it still says "Hotspot has not participated in Proof-of-Coverage in the last 1200 blocks. Unable to proceed with transfer" with the Transfer Hotspot button grayed out.  Is there a secure way I could send you the hotspot name? Perhaps on discord? EdB-charlietango#0336

**Comment by cokes518** [comment]
Ed - the Hotspot you asked us to look is a full Hotspot from Seed. I checked the onboarding server myself. If it can only do packet transfer, then something might be up and only Seed can help with troubleshooting. 

As for the transfer Hotspot, we're adding a `state_channel_close_v1` check to account for packet transfer as a valid on-chain activity.

**Comment by EdBallou** [comment]
During onboarding, Bluetooth was unable to find the hotspot as a data only hotspot. Searching was able to produce a result on a full gateway. It did not work on a newer iPhone so I was able to onboard it on another, older iPhone as a full gateway. I was advised to try an android and sideload a special build of the app on android which I thought was odd and didn't do.
