### ISSUE TITLE
Unable to withdraw HNT from Helium wallet

### ISSUE THREAD

**Issue by Mitchell6694** [helium/hotspot-app#1320]
I’m trying to withdrawal my HNT into my crypto.com HNT wallet but the send button stays grayed out no matter what I do. I’ve sent to my crypto.com wallet multiple times in the past so I’m not sure why it’s not working now.

**Comment by Ryan-Goldstein** [comment]
If the recipient address starts with 0x, that's not a valid Helium address. You need to select Helium (not Cronos, which I believe is now the default in crypto.com).
