### ISSUE TITLE
i open my helium wallet,i don't see my hotspot or accumulated HNT, I logged out and logged in again, but the wallet is empty and not increased with the hotspot, otherwise I didn't make a new wallet, recovered the old one.  tried to connect the hotspot again, but the wallet rejected it, it said it belonged to another wallet, and I did not open a new account, they constantly say whether 12 words are entered correctly, yes, how to solve this nonsense

### ISSUE THREAD

**Issue by MorskiPas80** [helium/hotspot-app#1321]
i open my helium wallet,i don't see my hotspot or accumulated HNT, I logged out and logged in again, but the wallet is empty and not increased with the hotspot, otherwise I didn't make a new wallet, recovered the old one.  tried to connect the hotspot again, but the wallet rejected it, it said it belonged to another wallet, and I did not open a new account, they constantly say whether 12 words are entered correctly, yes, how to solve this nonsense

**Comment by Ryan-Goldstein** [comment]
Try deleting the app and redownloading it. If that doesn’t work, then you definitely didn’t enter your 12 words correctly. There are plenty of words on the valid word list that are similar to each other, like claw/clay, cook/cool, oven/over, snack/snake, use/used, etc.

I’d suggest going through the word list at https://github.com/helium/helium-wallet-rs/blob/master/src/mnemonic/wordlists/english.txt and comparing each word you wrote down with other words on that list you might have confused it with.

**Comment by MorskiPas80** [comment]
thanks for the advice, that's exactly what I'm doing, but I wrote 100
percent well 12 words, I know they are similar, I checked 3 times,
something is wrong with the wallet app, one day I had helium and hotspot,
tomorrow empty wallet, when I refreshed wallet empty again
