### ISSUE TITLE
Lost 12 words of Helium app. How to resolve ?

### ISSUE THREAD

**Issue by freedomforyou** [helium/hotspot-app#1325]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

**Additional context**

**Comment by freedomforyou** [comment]
There are 2 Helium miners on that address. How can I get then to the new account ?

**Comment by Ryan-Goldstein** [comment]
Sorry, without the 12 word phrase, there’s no way to recover those hotspots.

**Comment by Ryan-Goldstein** [comment]
Correct. Onboarding a hotspot associates it on the blockchain with the wallet that onboarded it. The blockchain is immutable, so from that point on, only the owner of that wallet can transfer the hotspot to another wallet. If you’re no longer logged into that wallet on any device and have lost your 12 words, those hotspots are unfortunately lost forever.
