### ISSUE TITLE
I would like this feature.

### ISSUE THREAD

**Issue by chris10an2022** [helium/hotspot-app#1328]
I would like this feature.
Payload JoinRequest is empty ... but must contain DevNonce (and AppEUI, DevEUI)

![image](https://user-images.githubusercontent.com/80596341/137803051-826cdea6-7a4e-4aca-a873-5a87d78c9dfd.png)

_Originally posted by @Synthex-Moon in https://github.com/helium/console/issues/473#issuecomment-946146196_

**Comment by cokes518** [comment]
This is a console feature and the Hotspot app is to manage Hotspots. We won't be doing this, but thanks for your comments.
