### ISSUE TITLE
About the wallet access problem.

### ISSUE THREAD

**Issue by manipayment** [helium/hotspot-app#1337]
Update : I have accessed my account, the problem is caused by me. I entered a word incorrectly.

**Comment by Ryan-Goldstein** [comment]
There have been 50+ people who have reported the same thing on the Helium Discord, that they are 100% sure they have the correct words in the correct order and that there must be an app bug. In every case of which I'm aware, they eventually were able to access their wallet, after realizing they were entering one of the words incorrectly or in the wrong order.

What I'd recommend doing is looking at the list of valid words at https://github.com/helium/helium-wallet-rs/blob/master/src/mnemonic/wordlists/english.txt, comparing each word you think is the correct one with the words on that list, finding similar ones, and swapping those.

For instance, some similar words that can be easily confused, and if swapped will land you in the wrong wallet as you described in your initial post, are:

- claw / clay
- cook / cool
- keen / keep
- maid / mail / main
- obscure / observe
- oven / over
- pond / pony
- price / pride / prize
- pull / pulp
- rail / rain
- rare / rate
- rice / rich
- roof / room
- salmon / salon
- sea / seat
- shoe / shop
- side / size
- ski / skin
- slab / slam / slim
- snack / snake
- soul / soup
- space / spare
- spice / spike
- sport / spot
- step / step
- swamp / swap
- talk / tank
- ten / tent / test / text
- tide / time
- trap / tray
- trim / trip
- use / used
- walk / wall
- wash / wasp
- wide / wife
- wine / wing / wink
- winner / winter
- wood / wool

**Comment by manipayment** [comment]
Update : I have accessed my account, the problem is caused by me. I entered a word incorrectly.

**Comment by Ryan-Goldstein** [comment]
> Update : I have accessed my account, the problem is caused by me. I entered a word incorrectly.

Good to hear, and thanks for letting us know you were able to regain access to your wallet.

**Comment by witee-star** [comment]
https://cyberbump.net/how-i-recovered-469000-hnt-helium-wallet-12-recovery-words/
It will help you
