### ISSUE TITLE
Cant cancel pending transfer

### ISSUE THREAD

**Issue by kirksmacdonald1** [helium/hotspot-app#1338]
sold hotspot

there is a stuck pending transfer from when i purchased this item

Long Rainbow fly

**Comment by OneOfThePetes** [comment]
I wonder if this is the same issue that @cokes518 has fixed before in this thread:

https://github.com/helium/hotspot-app/issues/967#issuecomment-956416370 

I'll see if I can get some help on discord.

**Comment by kirksmacdonald1** [comment]
i believe so

this actually happened around December the person i brought this device sent two transfer requests to the same address one went through and the other just stayed pending as the device did transfer to me i never thought anything of it

then as i just sold the miner i cant undo the original transfer which was to my same wallet which is been pending since december

**Comment by cokes518** [comment]
the pending transfer has been cleared.

**Comment by OneOfThePetes** [comment]
Thanks @cokes518, appreciated :)
