### ISSUE TITLE
One of words from my 12 word pass phrase does not exist in the app

### ISSUE THREAD

**Issue by Szpaqn** [helium/hotspot-app#1354]
Hi, 
I have my pass phrase written.
I used it a year ago or so, and it worked.
Now when I try to import my wallet to a new phone one of the words is not available on the list.
So now all my HNT are locked.
From the issues here I can see I am not the only one.
Can you please bring back missing words?

**Comment by Perronef5** [comment]
Hi @Szpaqn the words have not changed. Please refer to this list for the words https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by Szpaqn** [comment]
I checked again. It was a typo on my side.
Don't know how, but I have written one of the words with a typo.
Very sorry.
Luckily I have an old phone where I was still logged in.
