### ISSUE TITLE
Cannot add new hotspots

### ISSUE THREAD

**Issue by Aleksej7734** [helium/hotspot-app#1363]
I have linxdot miners, I connect via bluetooth with helium app try to add a hotspot to blockchain and it says pending for for 10-20-30seconds and then it just disappears. I have 2  hotspots that are set up  which were added with ease but now I just can't add more. Neither from helium app or linxdot app. While the transaction is pending I click on it and go to view info on explorer but it gives me 404 error. What the hell is going on with this, does anyone know? I have the latest app version and I can't seem to figure this out, it must be some bug with the app or the helium network itself...

**Comment by Ryan-Goldstein** [comment]
Linxdot's [maker account](https://explorer.helium.com/accounts/14eUfY1GsjK4WH6uZYoeagnFtigBKdvPruAXLmc5UsUMEDj3yib) is depleted:

![image](https://user-images.githubusercontent.com/8300089/199058882-e2986eb3-8510-4470-bde2-849d15c6e34f.png)

They will need to top up their account before any Linxdots can be onboarded. I'd recommend contacting their support about this. It's not an app issue that can be resolved here.

**Comment by Aleksej7734** [comment]
Oh I didn't know that you have a limit . Thanks a lot for the reply man, I've at this for hours and my head started to hurt. I've send them an email so I guess nothing to do until they resolve this.
