### ISSUE TITLE
Money (SOL) disappeared in the transfer process

### ISSUE THREAD

**Issue by Berkmf** [helium/hotspot-app#1380]
I wanted to transfer some SOL in my wallet to another account.
Both wallet addresses are correct!
The operation appears to have been successful. But about $150 was gone. It disappeared !

https://explorer.solana.com/tx/2Ndj1LVugUXEiRTKteQW2SeA7oJ9a7CDWz2nXEytVnNVZCfqfiG2Tey7DTHL77LTYZA8zBHdEyPucFyvw45uxTrm?cluster=mainnet-beta

How will I trust this system?
There is already very little profit being made. The money earned in this way also disappears

SENDING ACCOUNT
[sRbSU7mdE8f33bFKwXrrUbLzH3dJyUyiPtj4iGgJrwC](https://explorer.solana.com/address/sRbSU7mdE8f33bFKwXrrUbLzH3dJyUyiPtj4iGgJrwC?cluster=mainnet-beta)

SENT ACCOUNT
[DpoPNxDXqpvUp6rWQAVD4oi7KgUtz3dWU94827YunpUv](https://explorer.solana.com/address/DpoPNxDXqpvUp6rWQAVD4oi7KgUtz3dWU94827YunpUv?cluster=mainnet-beta)

I HAVE ACCESS TO BOTH ACCOUNTS, NO MONEY (SOL) IN BOTH

**Comment by Perronef5** [comment]
Hi @Berkmf 👋🏼 The hotspot app does not allow you to transfer SOL. Looking at the transaction on the explorer and it says that you transferred 0.1 SOL.  Are you sure you transferred the correct amount?

<img width="1154" alt="Screen Shot 2023-05-04 at 12 19 29 PM" src="https://user-images.githubusercontent.com/19807431/236281112-9c6a40cc-f256-46a8-8be5-7a1d02476085.png">

**Comment by Berkmf** [comment]
I just waited. SOL of about $150 came back a day later.
