### ISSUE TITLE
Helium Wallet: Recovery Word not accepted

### ISSUE THREAD

**Issue by kenoc1** [helium/hotspot-app#1382]
**Describe the bug**
I can't type in my 12 recovery words because "TABACCO" is not accepted.

**To Reproduce**

1. Open App
2. Click on 'Restore wallet with 12-24 words'

**Expected behavior**
Accept the word input. 

**Screenshots**
![IMG_0626](https://github.com/helium/hotspot-app/assets/47333651/690295be-56ee-44c0-8a7d-ba31e3697c5d)
![IMG_0628](https://github.com/helium/hotspot-app/assets/47333651/a92be419-9aa7-4227-ba43-35d1fbec5159)

**Smartphone (please complete the following information):**

- Device: iPhone 13 mini
- OS: iOS 17

**Additional context**

**Comment by Ryan-Goldstein** [comment]
`TABACCO` is not a valid seed phrase word; you likely meant to enter `TOBACCO`, which is a valid word.

**Comment by kenoc1** [comment]
> `TABACCO` is not a valid seed phrase word; you likely meant to enter `TOBACCO`, which is a valid word.

Thanks a lot, it worked! What a typo :(
