### ISSUE TITLE
After account recovery, do not immediately prompt user to add hotspot.

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#144]
There is inherently some uncertainty when setting up the app from seed words. The first screen I saw after the post-seed-word entry "Recovering" spinner screen was the "Add Hotspot" screen (attached), which led me to initially think I'd entered my seed words incorrectly and a new wallet had been created.

Ideally I would be taken directly to the "Your Hotspots" screen where I would see that my hotspots had been imported. Even better would be a nice confirmation that my account had been imported successfully.

<kbd><img src="https://user-images.githubusercontent.com/1965053/106672704-552c4900-6565-11eb-9f90-3dbb074247d3.PNG" height="400"></kbd>

**Comment by cokes518** [comment]
Interesting idea. To me, the main problem here is the app doesn't provide feedback that the words have been accepted. I think sending them to the account tab might be better, since you're more likely to have a balance than have Hotspots.
