### ISSUE TITLE
Homescreen map shows incorrect/confusing location.

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#145]
Map centers to show me somewhere in between Palo Alto and Mountain View. My actual location is Downtown Oakland.
<kbd><img src="https://user-images.githubusercontent.com/1965053/106673667-ccaea800-6566-11eb-8759-75650ca31729.png" height="400"></kbd>

**Comment by cokes518** [comment]
that blue dot is a hotspot - do you have one in the MV area?

**Comment by jthiller** [comment]
Oh, yep that is absolutely mine.

**Comment by cokes518** [comment]
we randomly show the map of one of your hotspots, hence why we flew you to MV.

**Comment by cokes518** [comment]
is there anything we can do better here? in terms of discovery or helping you understand better?

**Comment by jthiller** [comment]
Two initial ideas would be to:
- zoom the map to contain all hotspots
- reposition the map to center on each hotspot as the list is scrolled (would require rework of card UI). Currently tapping in on the hotspot provides this functionality.
- Allow reordering/favoriting of hotspots directly in this view. Presumably a favorited hotspot would appear at the top of the list, but I haven't been able to do that (will file in separate bug)

**Comment by jthiller** [comment]
Fitting all the hotspots on the map looks pretty neat in my case. 

I feel like this matches the idea that this first screen is an overview. The drill down animation into the specific hotspot works well on a single hotspot view.
<kbd><img src="https://user-images.githubusercontent.com/1965053/106686084-9da43080-657e-11eb-9d3c-20316a278166.jpg" height="400"></kbd>

**Comment by cokes518** [comment]
Cool, noted and added to backlog. love the suggestion of doing an overview map.
