### ISSUE TITLE
Share button obscured on iPhone 12

### ISSUE THREAD

**Issue by jas-williams** [helium/hotspot-app#148]
See the screenshot ![image](https://user-images.githubusercontent.com/73598288/106676933-b6790a00-65af-11eb-89ea-b516389ce1a0.png)

**Comment by cokes518** [comment]
11 pro also obscures the share button a bit. 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/19331274/106677091-fec30880-656c-11eb-9b4b-097a3730ed73.png">
