### ISSUE TITLE
Chart in wallet should use relevant timescale labels.

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#150]
The 14D/12W/12M chart currently only shows days of the week (MTWTHSS) as time labels. 

* **14D:**
  * Use days of week as-is.
* **12W:** 
  * Label using months, dates (10/7, 10/14), or weeks (1 week ago, 2 weeks ago).
* **12M:**
  * Label using months.

![chart](https://user-images.githubusercontent.com/1965053/106787083-1f8a6d00-6604-11eb-8829-54cd4408d73b.gif)

**Comment by cokes518** [comment]
This will be addressed as part of #88
