### ISSUE TITLE
Hotspot Map: don't use location of a Hotspot without a location

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#154]
I've got a Hotspot (future-goldenrod-bat) with no location asserted. The map logic should exclude hotspots without a location. 

![IMG_1818](https://user-images.githubusercontent.com/19331274/106821781-ac4c1f80-6632-11eb-94fd-fa66954e2d8b.jpg)

**Comment by allenan** [comment]
with the new design of that screen, this is no longer an issue
