### ISSUE TITLE
UI for Hotspots without location asserted

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#156]
We're missing designs for Hotspots that have no location. Needs to be implemented.

**Comment by cokes518** [comment]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/19331274/107057896-c8fa6b80-6788-11eb-9f51-a55a2fee4e8b.png">


Design also in Hotspot tab in Figma.

When a user presses "Assert Location" button, open the Hotspot Settings.
<img width="252" alt="image" src="https://user-images.githubusercontent.com/19331274/107057737-9f414480-6788-11eb-9e11-bfa986d2c69d.png">

**Comment by DGKSK8LIFE** [comment]
Love it!
