### ISSUE TITLE
Activity List = purple hell

### ISSUE THREAD

**Issue by PeterMain** [helium/hotspot-app#160]
I've noticed that the account activity list invariably becomes a long list of mining activity, given those events outnumber others, if you have hotspots.

**Comment by PeterMain** [comment]
<img width="847" alt="Screenshot 2021-02-04 at 17 42 27" src="https://user-images.githubusercontent.com/3613880/106933038-5c438a80-6710-11eb-92fd-92b5507c839c.png">

Proposal would be to gather up all like items per day, which can be expanded for a complete list of granular events

**Comment by allenan** [comment]
Maybe this is an "Activity Summary" filter? So you'd see "View **Activity Summary**" by default, but maybe "All Activity" is still a filter that shows how it is today?

**Comment by PeterMain** [comment]
what do you think about the expanded view being default? so we'd present it in app as 'compact vs detailed'

**Comment by PeterMain** [comment]
<img width="811" alt="Screenshot 2021-02-18 at 16 03 37" src="https://user-images.githubusercontent.com/3613880/108384770-f6bcc700-7202-11eb-9588-0ddd491a9b66.png">

Updated designs on 'Account page and send flows' page

**Comment by PeterMain** [comment]
<img width="774" alt="Screenshot 2021-02-25 at 07 25 34" src="https://user-images.githubusercontent.com/3613880/109118569-65d27800-773b-11eb-8afa-fae181cb94cc.png">

Icons attached!
[Archive.zip](https://github.com/helium/hotspot-app/files/6041213/Archive.zip)

**Comment by matthewcarlreetz** [comment]
Decided to put this task on the backburner as the design is a WIP and the scale of the dev implementation is large. There's an intensive grouping and sorting that needs to happen in order to facilitate the new design, which by nature React Native is not well equipped for. Most likely the arranging of the data should get moved to the backend.

**Comment by matthewcarlreetz** [comment]
Current progess is here `feature/160_purple-hell`
