### ISSUE TITLE
In my wallet payment transactions you cannot copy wallet addresses

### ISSUE THREAD

**Issue by jas-williams** [helium/hotspot-app#164]
On the previous version the from and to addresses could be copied to allow easy sending of HNT especially as the addresses are truncated in the view![image](https://user-images.githubusercontent.com/73598288/107024443-f868a280-679f-11eb-8408-cad163afeb4f.png)

**Comment by cokes518** [comment]
Allow users to press and hold on any wallet address to copy to clipboard.

App should respond with "Copied" when saved to clipboard.

**Comment by cokes518** [comment]
@jas-williams this is fixed if you want to pull the latest test build from Android Play Store (or TestFlight)
