### ISSUE TITLE
UI Elements Cut off on iPhone 8 when display is set to zoomed.

### ISSUE THREAD

**Issue by ryanteck** [helium/hotspot-app#170]
When trying to setup a wallet on iPhone 8 the button doesn't seem to be clickable,

As well as not being clickable, the words are half cut off.

![IMG_0007](https://user-images.githubusercontent.com/1104745/107260919-92e21380-6a36-11eb-8743-f284edbd65fd.PNG)

On some other screens buttons are also cropped off.

![IMG_0009](https://user-images.githubusercontent.com/1104745/107261230-fc622200-6a36-11eb-920d-095f9817843b.PNG)

As I was writing this issue I found it's because I had my display set to Zoomed and was causing the issue.

**Comment by cokes518** [comment]
We've made several changes to how we handle small screen sizes. Closing this, but let us know if it continues to happen.
