### ISSUE TITLE
Create Hotspot SVGs for Nebra

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#171]
Nebra has an open PR for app integration and will need help creating Hotspot SVGs for the onboarding process. 

There will be 2 Hotspots: the Indoor edition and Outdoor edition. 

https://github.com/NebraLtd/hotspot-app/tree/nebra-hotspots

**Comment by PeterMain** [comment]
[Nebra Icons.zip](https://github.com/helium/hotspot-app/files/6003855/Nebra.Icons.zip)
