### ISSUE TITLE
Android: Settings > Require PIN clipped

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#180]
Its supposed to say "immediately" but looks like the string is clipped.

android v24, pixel 3.
![IMG_1830](https://user-images.githubusercontent.com/19331274/107426594-4b5e9480-6ad5-11eb-8430-8ebeb21b94d4.jpg)

**Comment by matthewcarlreetz** [comment]
@cokes518 I tested on a Pixel 3a and a Samsung S6 and wasn't able to replicate. Can you confirm it's still an issue?

**Comment by cokes518** [comment]
tis not reproducible. closing!
