### ISSUE TITLE
Use fitBound + padding for witness zoom calculation

### ISSUE THREAD

**Issue by allenan** [helium/hotspot-app#184]
We should investigate using the Camera.fitBounds function with a bottom padding offset for the witness zoom calculation. Right now the map centers on the screen, but the card is covering most of it

https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md#fitboundsnortheastcoordinates-southwestcoordinates-padding-animationduration

**Comment by cokes518** [comment]
Related to #315 ?
