### ISSUE TITLE
Android: Unable to Take Screenshots

### ISSUE THREAD

**Issue by ryanteck** [helium/hotspot-app#187]
Since release 28 on android, it is no longer possible to take screenshots in the app.

This is similar to my banking apps but not sure if it's a bug as on iPhone I'm still able to take screenshots.

I do see in the changelog android security flags were changed.

**Comment by cokes518** [comment]
We should allow the app to take screenshots. We ran into this problem in the old hotspot app.

**Comment by cokes518** [comment]
If we allow screenshots, the security screen when switching apps will not work. This seems like a binary action, we'll investigate further.
