### ISSUE TITLE
Account flow PIN/notifications issue

### ISSUE THREAD

**Issue by allenan** [helium/hotspot-app#190]
During the account onboarding flow, after setting your PIN, we prompt you for notification permissions.

1) we probably don't want to pop that without asking first?
2) regardless, because you've set a PIN, when the system modal pops, it puts the app into background triggering PIN reauth right after you've set it which feels odd.

Is there a way to prevent auth from triggering on those system notification pops?

**Comment by matthewcarlreetz** [comment]
I'm also wondering if we want to make the pin optional during onboarding?

**Comment by cokes518** [comment]
Pin should be required.

________________________________
