### ISSUE TITLE
Hotspot Onboarding - Update how a device type/name is determined

### ISSUE THREAD

**Issue by matthewcarlreetz** [helium/hotspot-app#200]
Currently we are using this bit of logic to determine a device type

`const getHotspotType = (onboardingAddress: string): HotspotType =>
    validator.isUUID(addUuidDashes(onboardingAddress)) ? 'RAK' : 'Helium'`

This needs to be updated to handle more makers.

**Comment by tyler-whitman** [comment]
I was looking at this and I think that type is not even used its just something left over from the old app. So we might be able to delete it. If it is used we should get the data from the staking server

**Comment by matthewcarlreetz** [comment]
I think it would be useful to have the hotspot type in the sentry logging, so we can see if errors are specific to device types.
