### ISSUE TITLE
Remove card handle tab background

### ISSUE THREAD

**Issue by PeterMain** [helium/hotspot-app#214]
<img width="585" alt="Screenshot 2021-02-18 at 15 34 15" src="https://user-images.githubusercontent.com/3613880/108380509-d12dbe80-71fe-11eb-8a34-40aa0b953674.png">

Ideally during card scrolls the top 'padding' that houses the card handle should be blank, not white.

The handle can stay fixed to the top of the card, and should always be the highest z-index UI element in the card, so that it remains interactive.

**Comment by matthewcarlreetz** [comment]
The bottom sheet library we are using doesn't have a built-in solution for this. I tried a few hacks, but all caused the usability to suffer. Going to punt on this for now.

**Comment by allenan** [comment]
adjusted label and milestone accordingly
