### ISSUE TITLE
Chart widgets respond a bit too eagerly when scrolling Hotspot details page

### ISSUE THREAD

**Issue by PeterMain** [helium/hotspot-app#215]
<img width="531" alt="Screenshot 2021-02-18 at 15 51 36" src="https://user-images.githubusercontent.com/3613880/108382902-371b4580-7201-11eb-89f4-bce5e676b449.png">

I've noticed a few times, the 'active' chart state kicks in on various widgets while scrolling - suggest some sort of millisecond delay, or potentially even removing the interaction - I don't think it adds much.

Also noticed the charts can get 'stuck' in their 'active' state - not sure what causes this exactly.

**Comment by allenan** [comment]
this is currently tracked with: https://github.com/helium/hotspot-app/issues/188

will reference in that issue
