### ISSUE TITLE
Custom picker component

### ISSUE THREAD

**Issue by allenan** [helium/hotspot-app#218]
Currently our picker element mimics the iOS scroll wheel picker:
![image](https://user-images.githubusercontent.com/792845/108389338-6eb7cc80-71c4-11eb-9372-e532af0afe11.png)

This is a little annoying to use because it requires multiple interactions to select a new option: open picker, scroll to the option you want (can only see a few at a time), press done or outside the picker to close.

We could create a custom sheet element for these instances. For example, here's Reddit's picker when choosing a new comment sort order:
![image](https://user-images.githubusercontent.com/792845/108389200-49c35980-71c4-11eb-917a-64d7cce4165b.png)

This only requires 2 interactions to use and you can see all your options at a glance

**Comment by cokes518** [comment]
Pete put together an action sheet style in figma:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/19331274/110664391-34ff3380-817c-11eb-86ba-38d75d2cf21b.png">
