### ISSUE TITLE
Label when hovering over hotspot charts

### ISSUE THREAD

**Issue by allenan** [helium/hotspot-app#229]
Currently we display a label at the bottom of the chart, but that was throwing off the chart alignment so it was removed in https://github.com/helium/hotspot-app/pull/225. Maybe there's a better place to display this info @PeterMain?

![image](https://user-images.githubusercontent.com/792845/108447281-756e3000-7214-11eb-962b-55cb8e1af365.png)

**Comment by PeterMain** [comment]
Could it go under the stat on the left? Under the finger isn't great anyway.

**Comment by cokes518** [comment]
@PeterMain we moved it under the stat on the left. Closing as done.
