### ISSUE TITLE
Android: Scrolling not working on Hotspot Checklist

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#248]
When viewing the hotspot checklist on Andriod 11 on a pixel 4, you cannot scroll left and right to see completed tasks.

**Comment by cokes518** [comment]
Reproducible on Pixel 3.

**Comment by cokes518** [comment]
The fix for this is not working as expected, will need further debugging today. Also noted that the interim fix is to switch from carousel to BottomSheetFlatlist, which does not accept opacity with svgs. The second interim fix here is to use solid svgs, then regenerate opacities with pngs.
