### ISSUE TITLE
Unable to view 12 words from settings.

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#249]
iPhone 12 Pro
iOS 14.4

To replicate:
- Open settings
- Tap 'reveal words' from Security section
- Validate with Face ID

<img src="https://user-images.githubusercontent.com/1965053/108605620-289c6d80-736a-11eb-8a1b-ba72b3bc50f5.png" width="360">

**Comment by cokes518** [comment]
Reproducible oh iPhone 12 Pro. Not reproducible on Android pixel 3.
