### ISSUE TITLE
Open hotspot detail with card expanded.

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#251]
Since the physical location of the hotspot is generally unchanging, I feel it makes sense to open hotspots with the full detail view expanded for easy viewing of stats.

[Figma](https://www.figma.com/file/ZgcLuizxLDNExuBuF7htj8/?node-id=5%3A5)

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/1965053/108606211-9dbd7200-736d-11eb-8b1b-cb04136d2fcf.png">

**Comment by cokes518** [comment]
Great suggestion Joey. Agree with this. The map is generally useful to distinguish between Hotspots (especially if you have them deployed in different locations) but it's usually not the first thing people wish to see when looking at hotspot details.
