### ISSUE TITLE
Android: Hotspot Time Fame drop down defaulting to "ys" on first load

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#252]
On my Pixel 4 Andriod 11 phone, when viewing a hotspot the dropdown default option for selecting the time period is showing "ys"

**Comment by cokes518** [comment]
I was able to reproduce this on my pixel 3.

**Comment by matthewcarlreetz** [comment]
I think that modalPicker just needs a minimum width. I can fix later today cc: @cokes518

**Comment by cokes518** [comment]
🙏
