### ISSUE TITLE
Homescreen selecting offline hotspots

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#253]
When on the home screen and  selecting your "offline hotspots" the list doesn't empty making it look like it's saying all of my hotspots are offline

**Comment by jthiller** [comment]
Adding my experience here: with an offline hotspot, the offline hotspot appears at the top of the list but all other hotspots also appear. 

Online and offline hotspots also appear the same visually.

**Comment by cokes518** [comment]
Can do something like this. Agree with Joey that if there are no offline hotspots, we let the user know, then display the online hotspots. Would like feedback from @PeterMain as well.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/19331274/108633392-de2df600-7428-11eb-8404-e7637dac7b2e.png">

**Comment by jthiller** [comment]
I was thinking to just fill the space with a friendly blank state, “all your hotspots are online”
I wasn’t going to show online hotspots. I see how this kinda changes the model though

-Joey Hiller
707.456.7374

**Comment by PeterMain** [comment]
Yeah this seems sensible. I don’t know if a list of offline hotspots makes sense, since you could also have ‘out of sync’. 

I think the original proposal was to have a ‘hotspot status’ menu and then use the smaller text/sub list to indicate status, a bit like you proposed. We’d float ‘higher priority’ status to the top of that status list.

**Comment by cokes518** [comment]
definitely improvements to be made here that we'll address immediately after launch.

**Comment by cokes518** [comment]
We can track improvements in the larger enhancement request here: https://github.com/helium/hotspot-app/issues/260

**Comment by cokes518** [comment]
@BFGNeil give this a try in the latest android test build
