### ISSUE TITLE
Hotspot homescreen cutting off the N when selecting your "Nearest hotspots"

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#254]
When selecting the nearest hotspots from the home screen, the first N of "Nearest hotspots" is cut off

**Comment by PeterMain** [comment]
@BFGNeil Got any device details?

**Comment by BFGNeil** [comment]
Android, Pixel 4 XL

**Comment by cokes518** [comment]
is this still happening @BFGNeil ?

**Comment by BFGNeil** [comment]
This has now been fixed.
