### ISSUE TITLE
Homepage hotspot filter remembering state but clearing filter

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#262]
When filtering hotspots by "top-performing hotspots" and then minimising the app and then coming back to it, the list is filtered by newest, but the previous selection "top-performing hotspots" is still chosen.

**Comment by jthiller** [comment]
Seeing same behavior on iPhone 12

**Comment by cokes518** [comment]
![IMG_C37E6F82A148-1](https://user-images.githubusercontent.com/19331274/108648305-c037b400-746f-11eb-9e08-8ed2788c1d92.jpeg)

Confirmed and reproducible.

expected behavior: remember previously set filter and sort hotspots accordingly.

**Comment by cokes518** [comment]
@BFGNeil give this a try in the latest playstore test build.
