### ISSUE TITLE
Change Hotspot Selection to List View (onboarding)

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#263]
The scroll container for adding hotspots should extend to the bottom of the viewport with some internal bottom padding so users can bring the bottom choices above the task bar. 

![image](https://user-images.githubusercontent.com/1965053/108634172-3535ca00-742d-11eb-916e-24eb81a13974.png)

**Comment by PeterMain** [comment]
@cokes518 what do you think about reducing size of these options? 3-wide? or 1 row each? 

I think our scrolling container should probably have a slightly lighter background colour, either initially, or transitioned to on overflow, to help with that top 'invisible edge'

**Comment by PeterMain** [comment]
![1](https://user-images.githubusercontent.com/3613880/109129071-22cad180-7748-11eb-95f4-1f586229ff40.png)
![2](https://user-images.githubusercontent.com/3613880/109129079-25c5c200-7748-11eb-803b-0c841592a7a5.png)

**Comment by jthiller** [comment]
Your list item approach in that first mock feels like the most reliable direction to me. The hotspot names are already feeling a bit tight on the second one (as it looks like you experimented with for the Nebra Outdoor).

Feel free to ping me for some SVG cleanup down the road here.
