### ISSUE TITLE
Infinite load of hnt income graphs on my wallet page

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#270]
The first load of the app, The My Wallet tabs income graphs show the loading symbol infinitely. 

If you select 12W it will load instantly, and if you then click 14D it will also load.

**Comment by cokes518** [comment]
hm unable to reproduce. can you try an uninstall and reinstall?

**Comment by cokes518** [comment]
is this still happening @BFGNeil ?

**Comment by BFGNeil** [comment]
This has been fixed.
