### ISSUE TITLE
[Android] Send HNT leads to a black screen after sending

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#285]
Steps to reproduce:

1. Empty a wallet account by sending it somewhere else
2. confirm the transaction
3. see send animation
4. screen goes black except for navbar

HNT never transfers.
![IMG_2133](https://user-images.githubusercontent.com/19331274/108873213-cdf45300-75af-11eb-8a48-2a22073aabca.jpg)

**Comment by cokes518** [comment]
Correction:

HNT HAS MOVED ACCOUNTS
The account with 0 balance with the issue reported in #284 is resolved. pending transactions appear as expected.
![IMG_EF80EBC15E4D-1](https://user-images.githubusercontent.com/19331274/108873514-0d22a400-75b0-11eb-8015-9f3516327f17.jpeg)

**Comment by cokes518** [comment]
black screen resolves when you close and reopen the app

**Comment by allenan** [comment]
It's specific to android and not limited to "send max", it happens after any send transaction
