### ISSUE TITLE
Menu Nav overlay issue on iPhone 12 Pro Max

### ISSUE THREAD

**Issue by mattsilv** [helium/hotspot-app#29]
On iPhone 12 Pro max, latest version of Helium iOS app, the system white bar overlaps the navigation labels on the 4 key navigation elements:
![image0](https://user-images.githubusercontent.com/156176/99992893-f0928800-2d84-11eb-83a7-ab21f78fd52a.png)

**Comment by cokes518** [comment]
This is fixed in 2.7.0
