### ISSUE TITLE
Strange firmware update required message

### ISSUE THREAD

**Issue by ccrisan** [helium/hotspot-app#300]
The SyncroB.it hotspot firmware uses the semver format for versioning and we're currently at `1.0.0-beta.16`.

When I try to add my SyncroB.it hotspot on the Helium app, it complains that "Your Hotspot needs a firmware update before you can continue". The app correctly detects my firmware version but indicates that required version be `2019.11.06.0`. That's a very specific firmware version! Could it be a leftover from when only one model of hotspots was supported?

I tried removing the beta part, leaving it as stable (e.g. `1.0.0`), but to no avail.

![helium-error](https://user-images.githubusercontent.com/76639/109063495-dfde0f00-76f1-11eb-8dff-978a7f65d89c.jpeg)

Any help would be appreciated.

**Comment by cokes518** [comment]
did you find a way around this? this is legacy code and there are still OG hotspots being onboarded from 2019 that require this message.

**Comment by ccrisan** [comment]
> did you find a way around this? this is legacy code and there are still OG hotspots being onboarded from 2019 that require this message.

My workaround was to switch to a versioning scheme that's compatible with the app, meaning that it should start with year, month and day.

**Comment by shenukaf69** [comment]
I got it now what can i do here![image](https://github.com/helium/hotspot-app/assets/45993226/aca211f4-3c94-453b-b23e-eac9901cb265)

**Comment by Dmoss1976** [comment]
Did anyone get this resolved?

**Comment by demariafederico95** [comment]
Any news?

**Comment by demariafederico95** [comment]
How do you onboard? Helium app or helium Wallet app??

**Comment by DeanWronowski** [comment]
Did anyone manage to fix this?

**Comment by grgfo** [comment]
personne ? :)

**Comment by Ryan-Goldstein** [comment]
This is not the right place to get support; you need to contact your hotspot's manufacturer.
