### ISSUE TITLE
Mock pending transaction for transfer hotspot is empty/incorrect

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#303]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/19331274/109079756-40e6f200-76b4-11eb-8987-2ba911f49a48.png">

Notice that the Hotspot name is wrong.. buyer and seller are empty. 

Once the transfer confirms, it looks correct.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/19331274/109079902-7ee41600-76b4-11eb-81b9-dfab9b202d15.png">

**Comment by PeterMain** [comment]
• Why big space after dark bar on 2nd shot?

• Grey pods should be attached to one another.
<img width="617" alt="Screenshot 2021-02-25 at 07 16 05" src="https://user-images.githubusercontent.com/3613880/109117056-64a04b80-7739-11eb-8822-716139f88c18.png">



• Tinted background should be blurred (and if unable to, made even more opaque)
