### ISSUE TITLE
Unable to drop a pin or enter an address on assert page

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#307]
A few users have reported that they were unable to enter an address in the address field or drop a pin by panning around on the map. This is during the add hotspot flow.

This is happening on iOS and android, wallet address and physical address used in the discord message: https://discord.com/channels/404106811252408320/733699201887764511/814547381373894707

**Comment by timtamothee** [comment]
This issue may be only for specific Hotspots. I found I'm not able to assert the Hotspot in any location because the wheel doesn't stop spinning to load. The Hotspot ID is 4C:E2.

**Comment by allenan** [comment]
@timtamothee which wheel is this? would you be able to dm me a video showing this behavior?

**Comment by cokes518** [comment]
Update: Hotspots not on the onboarding server will encounter this issue. 

We'll update the error message to be more meaningful and communicate next steps.

"Unable to find Hotspot in the Onboarding Server. Please contact the Hotspot manufacturer for next steps."
