### ISSUE TITLE
New designs for account onboarding flow

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#31]
Same flow as existing app, but new look and feel to match new designs.

**Comment by cokes518** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/19331274/100649183-e9c0c380-32f6-11eb-9d7f-d377d674576f.png">

ready for implementation

**Comment by matthewcarlreetz** [comment]
@PeterMain @cokes518 Will we doing account import as a separate issue?
