### ISSUE TITLE
Unable to update Wi-Fi for a Hotspot

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#310]
Several users in Discord are reporting they're unable to update the Wi-Fi of their Hotspot.

Steps to repro:
1. pair with the hotspot
2. tap update wi-fi
3. tap the new network you want to connect to
4. see popup "forget wi-fi"
5. tap "forget" to confirm
6. dialog dismisses, not offered to enter new network's password. if you try to select the new network again, you're stuck in the same loop.
effectively, the wi-fi network is never "forgotten".

User 1.
Iphone 10x, RAK v1 Hotspot

User 2
iPhone 8, RAK v1 Hotspot

Coco's testing notes:
Tested on Android and iOS on RAK Hotspot (EU). I was able to proceed past step 5 but if you reconnect to the hotspot, it displays the old network I had tried to forget.

**Comment by cokes518** [comment]
Users have been able to use the Hotspot Utility app to update their wi-fi, so it's definitely our implementation of "forget" that is messing things up.

**Comment by cokes518** [comment]
Current investigation leads us to believe that if the current configured network isn't available, you can't forget it.

This is why I cannot reproduce, since both networks are available for me to switch between.

**Comment by Sleepyforages** [comment]
> Current investigation leads us to believe that if the current configured network isn't available, you can't forget it.
> 
> This is why I cannot reproduce, since both networks are available for me to switch between.

Tried to replicate the same network (both name and password) but with different router. Didn't work. Hotspot still don't want to forget it. In couple of hours will try to get back to the old/current network and will report as it goes.

**Comment by pendorelf** [comment]
I was able to get through the steps successfully, by turning on the old wifi hotspot
1) unplug Rak hotspot
2) turn on old wifi hotspot
3) plug Rak hotspot back in
4) run through hotspot setup
5) change wifi network
6) select new wifi network and select 'forget' button on popup.
7) turn off old wifi hotspot

I did have to do this 3 times for it to finally take.
