### ISSUE TITLE
App shows Hotspot (that I don't own) when tapping "My Hotspots" card

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#314]
This is likely an edge case.

iOS, TF139
Steps to reproduce:
1. Go to any Hotspot you own
2. tap and explore a Hotspot (that is not yours) on the hotspot map
3. go back to hotspot tab
4. tap "My Hotspot" card
5. see the hotspot from step 2.

Expected results:
See my Hotspots.

**Comment by PeterMain** [comment]
for me it actually takes me back to my default owned hotspot. I don't return to the hotspot I had selected somewhere else

iOS TF139

**Comment by tyler-whitman** [comment]
This should be going back to your first owned hotspot when you tap the "My Hotspots" button. If you swipe the card down it will go back to the one you previously selected in the app. 

I made some fixes for this in https://github.com/helium/hotspot-app/issues/337
