### ISSUE TITLE
Add widget

### ISSUE THREAD

**Issue by teamrobhogg** [helium/hotspot-app#319]
![53A1DA68-7A13-4376-B53C-95E169FEC9E7](https://user-images.githubusercontent.com/71191584/109325725-4400f000-7824-11eb-93f8-e1c1dfb7276c.jpeg)

**Comment by cokes518** [comment]
To clarify, this is to add an iOS or Android-supported widget so it can be added to the user's OS phone screen.

**Comment by NathanLawrence** [comment]
I know things are a little chaotic right now, but I've done this for myself with the API already; happy to take on this task for iOS when we're ready for it.

**Comment by cokes518** [comment]
@NathanLawrence take it away!

**Comment by cokes518** [comment]
@NathanLawrence checking in to see if you need any help?

**Comment by Yamanipanuchi** [comment]
Did this idea get any legs? Or possibly any alternatives?

**Comment by Perronef5** [comment]
Hi everyone I would like to add this enhancement if it is still up for grabs 👀

**Comment by Perronef5** [comment]
@cokes518 ^^

**Comment by Perronef5** [comment]
@cokes518 Bumping one more time. Is this still up for grabs?

**Comment by cokes518** [comment]
all yours!

**Comment by Perronef5** [comment]
@cokes518 Can we move this to in progress?

**Comment by cokes518** [comment]
can you link a WIP PR?

**Comment by Perronef5** [comment]
@cokes518 I am getting permission denied when trying to push into my branch

**Comment by Perronef5** [comment]
I see now y'all are merging via forks. Will make the changes then PR

**Comment by Perronef5** [comment]
@cokes518 PR is ready https://github.com/helium/hotspot-app/pull/1220

**Comment by Perronef5** [comment]
@cokes518 @matthewcarlreetz PR is ready to be reviewed again 🙏
