### ISSUE TITLE
Swipe left/right for next hotspot card

### ISSUE THREAD

**Issue by radrob1** [helium/hotspot-app#327]
When trying to view all my hotspot details, I find it slightly painful to have to swipe a hotspot card down, hit Back, then choose another hotspot to get to the next hotspot details. Would be easier if I could swipe left/right to go from one hotspot card to the next.

**Comment by cokes518** [comment]
@PeterMain any design feedback? I remember we had arrows in the top next to the settings cog but that's going to be cluttered.

**Comment by cokes518** [comment]
let's do arrow left and right on the hotspot details page, and move the hamburger out into a share button elsewhere (kebab next to hotspot name?)

**Comment by PeterMain** [comment]
<img width="946" alt="Screenshot 2021-04-20 at 18 21 56" src="https://user-images.githubusercontent.com/3613880/115438505-62bcab00-a205-11eb-9db0-667db7e70b1e.png">

I had been working on something but it turned into a larger revision. The goal was to provide better navigation closer to the base of the app.
