### ISSUE TITLE
Export Private Key Functionality

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#33]
Give users the option to export their private key as an encrypted file to backup elsewhere. An example entry point would be in More > Reveal 12 Words > Export Private Key Instead

Then the user would be prompted to save the file elsewhere.

**Comment by Perronef5** [comment]
Instead of exporting a file could we just allow the user to copy the private key? Similar to how it works on the wallet app today

**Comment by cokes518** [comment]
i like it
