### ISSUE TITLE
Notifcations by day order is incorrect

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#330]
Looking at older notifications which are sorted by day, every time I've had a hotspot down and come back up the order of notifications is wrong in my history.

For example, Looking at an issue yesterday, 3 days ago and 15 days ago the order of the notifications is as such:

Hotspot is online
Hotspot needs attention

In that order, which looks like it just needs reversing.

**Comment by cokes518** [comment]
Reproducible.
