### ISSUE TITLE
No Next button on android page when trying to scan for RAK miner

### ISSUE THREAD

**Issue by heliumredbeard** [helium/hotspot-app#332]
<img width="1792" alt="Screen_Shot_2021-02-28_at_10 51 40_AM" src="https://user-images.githubusercontent.com/56279372/109556700-02727e00-7a8c-11eb-8004-39552c84566f.png">

**Comment by cokes518** [comment]
There seems to be two issues:

1. The copy "press next to scan" is incorrect. We want the user to press "Scan for my Hotspot". That can be easily fixed.
2. Does pressing "Scan for my Hotspot" do anything @heliumredbeard

**Comment by heliumredbeard** [comment]
Negative, pressing the text does nothing.  Only way for them to move on is to step back and add it as a Helium Hotspot, which does work

**Comment by heliumredbeard** [comment]
One more, App 3.0.0 using a Google Pixel 4 XL with Android 11 can't onboard as a RAK.  will have him onboard as Hotspot

**Comment by cokes518** [comment]
This is reproducible if you set font size to largest, and display size to larger.

workaround would be to reset font and display to default on these two settings to proceed, or add as helium hotspot.
