### ISSUE TITLE
Duplicate Month on account date filter (12M)

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#339]
On the account page, toggle to 12M filter. You'll see January is repeated twice.

![IMG_922672D1A6F5-1](https://user-images.githubusercontent.com/19331274/109718572-5e0c3c80-7b5c-11eb-9c88-cb71f2c7eeaf.jpeg)

**Comment by matthewcarlreetz** [comment]
I'm not seeing it. Are there any additional steps needed to reproduce?

![Simulator Screen Shot - iPhone 11 - 2021-03-04 at 15 47 09](https://user-images.githubusercontent.com/1760821/110035161-e9263780-7d00-11eb-8225-dbce57ec7c1b.png)

**Comment by cokes518** [comment]
I think it has to do with the beginning of the month rolling over and because we’re on day 4, it’s no longer reproducible.

________________________________

**Comment by matthewcarlreetz** [comment]
Ok. I moved the system clock back to last month, but that didn't seem to do it. I'll try playing with the day of the week.

**Comment by matthewcarlreetz** [comment]
https://github.com/helium/wallet-api/pull/19

**Comment by cokes518** [comment]
for completeness, we decided not to add a month filter and instead use 30 days. On hover, we will show the 30 day date-range, i.e.

Feb 02 2021 - Mar 01 2021.
