### ISSUE TITLE
Issue while onboarding "Got error code d2FpdA== from add_gw"

### ISSUE THREAD

**Issue by jigs611989** [helium/hotspot-app#345]
I notice this error while provisioning RAK miner.

**Steps**

- Powered on the RAK miner
- Skip through intro screens
- Scan devices
- Connect to RAK
- Confirm the location

Console Log
**[Error: Got wait from hotspot: parsedValue = wait]**
**[Error: Got error code d2FpdA== from add_gw]**

look like we have to wait for sometime after power-up. 

Right now it just stops the adding gateway flow, Can we retry after some delay?

![IMG_20210302_174414](https://user-images.githubusercontent.com/12206811/109869766-4a152780-7c8f-11eb-9b16-3c7005b62cc8.jpg)

**Comment by cokes518** [comment]
Hi, yes that's correct. the error code `d2FpdA==` is base64 encoded, which translates to "wait". We have a fix where the error message is more clear that the miner is busy, and that the user should try again in a few minutes.

In the past, that error appeared when the RAK Hotspot was freshly powered up and the ECC hasn't had a chance to fully spin up, so it generates that error message.

**Comment by jigs611989** [comment]
@cokes518 I did fix it by decoding 64 before comparing it with the text "wait" in `HotspotTxnsProgressScreen`

I also tried adding "Try Again" button in the popup. Basically, `sleep(1000)` & `submitOnboardingTxns` again.

It did work, not sure if any downside to doing that.

let me know if this make sense, I can raise PR.
