### ISSUE TITLE
Reduce unnecessary white space on some androids

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#353]
Screenshots are from a community member in discord:

On an android, it appears that there is too much white space all around (or we don't optimize for it). we can do better on this so more useful information is displayed without scrolling.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/19331274/110051955-969e4880-7d0b-11eb-984f-dd7334efb35e.png">
<img width="261" alt="image" src="https://user-images.githubusercontent.com/19331274/110051967-9bfb9300-7d0b-11eb-932e-73954b1cf1fe.png">

**Comment by tyler-whitman** [comment]
@PeterMain what do we want to do here? Just less padding?
