### ISSUE TITLE
Firmware Characteristic Service Not Suitable To Be Used (?)

### ISSUE THREAD

**Issue by ryanteck** [helium/hotspot-app#354]
Today in preparation of getting our hotspots ready to be programmed I done some last steps of updating our base OS software to the latest version which brought a breaking bug for us. However the issue could manifest in the future as others update as well.

While we are using our own BTLE implementation, this same issue is re-producable with the gateway_config tool provided here on github due to the nature of the issue.

Currently for the firmware version the GATT characteristic `2A26` is used under the Device Information Service `180A`, however in version 5.55 of Bluez and above a service is provided by bluetoothd on 180A which causes a conflict as the app searches for the 2A26 characteristic under the service provided by bluez and fails.

Upon contacting the maintainers of Bluez so far the response is that it doesn't seem to be recommended that a user's app provides this service:

```
> However as our software creates a service on 0x180A it causes a
> conflict, as the application we are making our software with reads
> from the first service available which is the one generated by BlueZ.

You should probably stop doing that and just use main.conf to set the
values you want to be published, we should actually blacklist DIS to
be registered by applications since that is defined by the platform
having the application to override may actually cause problems.
```

The above also hints that they may block the service from being registered at all in the future.

In a brief discussion with @madninja one suggestion was to pin the bluez version to an earlier one (5.53 was working on our older software, however as the Base OS that provides Blue Z isn't under our control with the OTA mangement platform we're using, we're currently unable to do this). 

However I could see the above becoming an issue over time as pinning to an older version of software isn't going to be possible in the long run.

The best solution that I can think of is to just move the firmware request characteristic to the custom service everything else is under as this would then future proof the code, however it does mean existing hotspots would need updating with this change.  However the code change in gateway_config does look fairly trivial to do. 

Or possibly if it fails the check with the characteristic in the device info service, that it then requests it from a second one to then provide good backwards compatibility.

**Comment by ryanteck** [comment]
Just wanted to add that the conversation with the BlueZ devs is at https://marc.info/?l=linux-bluetooth&m=161496092020034&w=2

So far it's looking like the patch I've submitted is the most likely route to go as in the current main versions of Blue Z it doesn't look possible to disable the DIS they create, and that in the future it's most likely it'll not be possible to create your own.

Pinning BlueZ to an older version (Such as 5.53) isn't really a solution to this issue.

**Comment by tyler-whitman** [comment]
@madninja Ryan has a fix for this in the app to now read from `SOFTWARE_VERSION_UUID = 'c0b64050-697d-463a-a33f-70c4825731f8'` and check the device firmware version there in the case it fails to read from `FIRMWAREVERSION_UUID = '00002a26-0000-1000-8000-00805f9b34fb'` do we need to make this change in our bluetooth code as well?

**Comment by ryanteck** [comment]
Should no longer be required.
