### ISSUE TITLE
Logout of account doesn't clear state + update location permissions

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#370]
While testing "view hotspots around me" (as an account with no hotspots), it remembered the last Hotspot I viewed in a previous account so it didn't really show hotspots around my device.

Update this popup to include "view hotspots around me". 
"Allow "Helium" to use your location?"
"Allow Helium to use your location to add your Helium Hotspots to the network and explore Hotspots around you."

**Comment by tyler-whitman** [comment]
Ah we cant change that popup, we can only change the text. I guess it has to be general for both depending where they hit the first permission request. Maybe we can make it "Allow Helium to use your location to view hotspots around you and add hotspots to the network"?

**Comment by tyler-whitman** [comment]
Oh just saw your line, that works. Unfortunately we can add anything else to the popup. It comes from the native iOS permission dialog.
