### ISSUE TITLE
Burning small amount into DCs results amount to be converted to integer

### ISSUE THREAD

**Issue by dpetrov** [helium/hotspot-app#377]
I am trying to burn a small amount of HNT into DC. It seems, that currently the amount is always convert into Int. So for example: if I try to burn 0.00250 HNT, that is automatically converted to 250 HNT.

**Comment by PharkMillups** [comment]
Thanks for reporting this. We're taking a look.

**Comment by tyler-whitman** [comment]
@dpetrov where did you see the value being incorrect? On the activity screen or when submitting the burn transaction?

**Comment by dpetrov** [comment]
@tyler-whitman it's on the burn transaction screen. Steps to reproduce:

1. Go to console.helium.com
2. Select Burn HNT and choose a small amount of DC (for example: 0.00125 HNT)
3. Scan the QR code - that is automatically converted to 125 HNT on the app

**Comment by tyler-whitman** [comment]
> @tyler-whitman it's on the burn transaction screen. Steps to reproduce:
> 
> 1. Go to console.helium.com
> 2. Select Burn HNT and choose a small amount of DC (for example: 0.00125 HNT)
> 3. Scan the QR code - that is automatically converted to 125 HNT on the app

Under the `AMOUNT (HNT)` item it shows it incorrectly? Sorry I am not seeing this happen on my device.

**Comment by cokes518** [comment]
@dpetrov can you show a screenshot of the incorrect value and the QR code from console?

**Comment by dpetrov** [comment]
Sure:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/82677/110833733-6fb0bb00-82a5-11eb-8295-e31b6793121b.png">

![IMG_5803](https://user-images.githubusercontent.com/82677/110834049-bf8f8200-82a5-11eb-94b9-a1fadb22469c.jpg)

Version is 3.0.1

**Comment by tyler-whitman** [comment]
Ah ok, I see the problem. Thanks we will get it fixed.

**Comment by dpetrov** [comment]
@tyler-whitman do you have a roughly idea, when the 3.0.3 will be released? Thanks

**Comment by tyler-whitman** [comment]
We are planning on Monday.

If you need this fix before then you can sign up for one of the beta
builds. The links are in the projects readme!

**Comment by dpetrov** [comment]
Thanks Tyler, much appreciate the quick response. The background is, that we at heliumhosts.com use DC burning as part of the users verification. Does that issue affect only the burning or as well sending small amounts? Monday is around the corner, so it should be good ;)
