### ISSUE TITLE
Android: Assert Location Issues

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#379]
Android Xiaomi mi 10t pro
OS: Android 10
Wallet: 1332WCuHM6LCGimBsUyYBomihs1mNehYDjj2AB2RirQNnE3fRgH

Host reports intermittent crashing when clicking search for hotspots. 

When it does work, the map is not clickable when re-asserting location and the button is greyed out. 

When asserting a hotspot, the host couldn't click the map either, assuming the pin drop was all he could do and wrongly asserted it at his house.

The host also reports the app version of 3.0.2 but the price is not clickable.

He's attempting to join the beta to see if it makes a difference, I will follow up tomorrow with a video.

**Comment by BFGNeil** [comment]
Followup:

1) host was using the cog to assert location on a new hotspot - would it be possible if they start the assert location of a hotspot via the cog on a hotspot that hasn't been added to the blockchain they are redirected to the onboarding process instead?

2) the button to "change location" after clicking assert location was greyed out. this to him (and me) applies the pin needs to be set first and the map is not clickable - suggestion: I've already clicked assert location, why show this page? the cost of the assert is shown after as well so this just seems like an extra button click. but if you decide to keep it, the issue most are facing is just the button being coloured wrong in grey instead of blue, clicking it works.

**Comment by cokes518** [comment]
Hosts cannot assert location, we have a related bug to remove the assert button for non-owners.
