### ISSUE TITLE
Assert Location Transaction - Show who paid for the assert

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#383]
Similar to Add #382 , add a "Paid by" field below "Location", and show the address that paid for the transaction.

If it was a Maker, show the maker name below the address. If it was the owner, display "Owner".

<img width="635" alt="image" src="https://user-images.githubusercontent.com/19331274/111012558-49485980-8351-11eb-83be-dd23875f6d6c.png">

**Comment by tyler-whitman** [comment]
What about something like this?

![Screen Shot 2021-03-12 at 6 30 53 PM](https://user-images.githubusercontent.com/6345962/111016196-4ce3dc80-8361-11eb-9302-b2e4723aa315.png)

**Comment by cokes518** [comment]
I don’t hate it but it’s busy there now. Maybe more spacing between lines or shorten the maker name. It looks overwhelming.

________________________________
