### ISSUE TITLE
Graphics glitch

### ISSUE THREAD

**Issue by PeterMain** [helium/hotspot-app#409]
Steps to recreate

• on hotspot home page, hit settings
• when the modal is active, dismiss the modal
• on the nav bar hit 'accounts'

the hotspot > account transition glitches a little

iOS 14.5

**Comment by tyler-whitman** [comment]
Yeah I noticed this too, I think it has something to do with a combination of modal and bottom sheet and one of the views is causing a flash when you change tabs
