### ISSUE TITLE
Map Improvements

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#437]
New Layers

New Hotspots around me (last 7 days)
HIP 17 reward scale numbers
red 0-0.2
orange 0.21-?
Yellow
Green
Online/Offline Hotspots
- green/orange for online/offline

**Comment by PeterMain** [comment]
At the risk of condensing too much information into one layer, I was curious what people's thoughts were on this? I'm not sure honestly you could push it much further than this, but I think it would be interesting to see. Being 'red' on a map, would certainly push users to diagnose (would still like hex here though)

<img width="1048" alt="Screenshot 2021-04-02 at 15 32 00" src="https://user-images.githubusercontent.com/3613880/113424902-d1f26c80-93c8-11eb-9459-11fe02119763.png">

**Comment by cokes518** [comment]
to be implemented in res8 work
