### ISSUE TITLE
Push Notification Deep Links

### ISSUE THREAD

**Issue by tyler-whitman** [helium/hotspot-app#442]
We should support deep linking into the app from push notifications. Right now when you tap a notification it only opens the app to the default screen.

For example if you tap a transfer notification it should open the notification tab so you see the new transfer request.

**Comment by anthonyra** [comment]
Could this also be opened up to other potential requests? Like to request a payment? I've been looking around to see how current partial transactions are handled.. and honestly TypeScript is so close to JavaScript that I think it makes sense and then I realize I'm just lost... 

My thoughts are to allow for away for third party applications to send the txn as a string (hash) or JSON to be signed by the party receiving the request. If in JSON format it could simply be loaded into the the post QR screen with the pre-filled fields being none editable... Upon accepting they post to the API to be submitted to the blockchain.

**Comment by tyler-whitman** [comment]
> Could this also be opened up to other potential requests? Like to request a payment? I've been looking around to see how current partial transactions are handled.. and honestly TypeScript is so close to JavaScript that I think it makes sense and then I realize I'm just lost...
> 
> My thoughts are to allow for away that third party applications could send the txn as a string (hash) or JSON to be signed by the party receiving the request. If in JSON format it could simply be loaded into the the post QR screen with the pre-filled fields being none editable... Upon accepting they post to the API to be submitted to the blockchain. That way they just need to open the notification and accept the transaction and skip the picture part of the QR code

Thanks for the ideas and feedback, for this specific payment flow would you mind filing a separate github issue. We are using this issue as general improvements when tapping on notifications. I like your idea though around alternatives to QR for payment requests. Let's continue discussion in a new issue.
