### ISSUE TITLE
Earned rewards Not available or 0.00 HNT on Wallet

### ISSUE THREAD

**Issue by sam80s** [helium/hotspot-app#443]
I have hotspots earning HNT but the wallet (Helium wallet) does not reflect any earned HNT. wondering if this is common and i have had the hotspot for two weeks now.

**Comment by cokes518** [comment]
This is related to the API issue we found in the app. If you update to 3.0.5, it will be fixed. closing.

**Comment by sam80s** [comment]
I actually have the updated version 3.0.5. It is not the old one.

**Comment by robotron3k** [comment]
I just started my miners and currently have the latest version of Helium wallet and have this same issue issue. Today the wallet part disappeared that states O funds.

Please advise.  Thanks DR


![Screenshot_20210621-135345_Helium](https://user-images.githubusercontent.com/65085820/122806379-3e7a5a80-d298-11eb-98f4-30a97fa739d3.jpg)
![Screenshot_20210621-135335_Helium](https://user-images.githubusercontent.com/65085820/122806400-44703b80-d298-11eb-87c1-1fbb52e0cbb5.jpg)

**Comment by AlfieDarko** [comment]
I have the exact same issue

**Comment by Rivesito** [comment]
I have the exact same issue... Someone can help me, PLEASE!!!

**Comment by Ryan-Goldstein** [comment]
Update the app to 4.1.0 if it's not already, then sign out, then sign back in.

**Comment by Rivesito** [comment]
> 

I did... Many times... Says Zero Balance yet
![IMG_3397](https://user-images.githubusercontent.com/55040888/170988592-36b3dec0-bea5-4dd0-b3bd-6c7b922dfa61.jpg)
![IMG_3396](https://user-images.githubusercontent.com/55040888/170988593-e6fc2596-223e-45bc-a077-2e346523379e.jpg)
