### ISSUE TITLE
iOS screen design assumes too large a screen - Elements covered up and can't be scrolled

### ISSUE THREAD

**Issue by Gonzo-XIII** [helium/hotspot-app#457]
The developer of the iOS app has made an assumption that everyone owns an iPhone X or larger. The attached screen is from a brand new, current model iPhone SE2. It has a screen the size of the older 6, 7 and 8.

As you can see, it’s not possible to see what is in the “Chart your account” buttons as they are covered by the Wallet Address slider. And you can't get rid of the slider completely, and you can't scroll the underlying screen up to see those assets.

Suggestion to fix could be moving the title of “My Wallet” to the blank space beside the icon and maybe making the description text smaller. This should give you the room to show the currently hidden assets. ** (PS. Looking at the screen again, you already have "My Wallet" at the top, so the title under the icon is superfluous. I'd just remove it.) **

![Helium Wallet IOS](https://user-images.githubusercontent.com/13119623/113970888-0eb3dd00-987b-11eb-874f-d45e691a0d4a.png)

**Comment by cokes518** [comment]
Hi, thanks for reporting. Do you happen to have font scaling enabled on your device?

**Comment by Gonzo-XIII** [comment]
Yes, I do have font scaling on. With it off on my SE2 (same screen size as 6/7/8) the text is too tiny for my old eyes. I have it on the 3rd tick up.

**Comment by cokes518** [comment]
this screen has been updated, feel free to file another bug if it's still happening.
