### ISSUE TITLE
Weekly Earnings Report figure wrong

### ISSUE THREAD

**Issue by BFGNeil** [helium/hotspot-app#468]
weekly earnings on explorer: 851.52 hnt

Weekly earnings report on app:

![Screenshot_20210413-123947](https://user-images.githubusercontent.com/79230094/114548529-ccfaac00-9c57-11eb-81b7-c4ba1c2867ed.png)

**Comment by cokes518** [comment]
fix is merged, but missed the Tuesday 10am reporting window. Next week's earnings report will be updated.
