### ISSUE TITLE
Change 'Elevation' label to 'Height'

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#478]
'Update Hotspot' view:
This issue considers changing the label "Elevation" to "Height". The tooltip information can stay the same.

Problem: 
Without tapping on the tooltip, I expect a decent number of folks would enter their 'GPS' elevation, or "elevation from sea level". This would lead to 'elevations' well above the height of any structures in some situations.

Solution: 
I feel labeling the form as 'Height" more accurately represents the intended value without getting into more [technical terms](https://en.wikipedia.org/wiki/Height_above_ground_level).

Reference:
<img src="https://user-images.githubusercontent.com/1965053/115133488-770e6700-9fbd-11eb-9879-2e4aa5b67c07.jpeg" alt="Screenshot of Update Hotspot screen" height="450">

**Comment by cokes518** [comment]
You're right Joey - after doing more research, the antenna community tend to refer to height wrt to the physical distance from ground level that the antenna is placed, and elevation refers to the angle of the antenna.

**Comment by jthiller** [comment]
> elevation refers to the angle of the antenna
Well I didn't know that, but glad the issue sparked some more insight
