### ISSUE TITLE
Represent USD value of a wallet's HNT in-app.

### ISSUE THREAD

**Issue by jthiller** [helium/hotspot-app#48]
**User story:** One of the most common actions I take is to check the overall balance of my HNT in the wallet app and copy it to Blockfolio to get a sense of my 'portfolio' value. It would save me time and be more convenient to reference the wallet value only in the hotspot app. This would help the broader app user base as many users are unlikely to know that Blockfolio is available for this type of calculation, and furthermore there are a set of users that are unlikely to know where to find the market value of HNT at all.

**Proposed solution:** It would be nice to be able to toggle HNT balance in the app, backed by something like CMC, Oracle Price, or another source. I feel the source should be represented to the user in some manner so they can continue their exploration outside of the app, reinforcing that the USD value isn't just made up.
Depending on the layout of the new app UI, the USD value could be included as parenthetical to the HNT balance, noted in some sort of tooltip, or toggled on a tap like the price representations in the Robinhood app. 

As an extension of this though, I would be careful around making the dollar value the most prominent aspect of the balance. The USD value of HNT fluctuates wildly, as does the rest of the crypto market. I think significant drops are likely to create a bit of anxiety and more "Why are my earnings down".

**Comment by cokes518** [comment]
great idea @jthiller I think we can make this happen.

**Comment by cokes518** [comment]
We'll use CoinGecko for this, and in addition to displaying the dollar value in the balance, we can also convert all HNT values to dollar throughout the app, to keep the experience consistent. 

There will be 2 entry points. Tap the wallet balance to toggle through HNT and USD, and a toggle in Settings that will perform the same function. The default will be HNT.
