### ISSUE TITLE
Hotspot Details UI Tweaks

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#502]
1. tapping on the background should dismiss the sheet
<img width="249" alt="image" src="https://user-images.githubusercontent.com/19331274/115619057-4a519c80-a2a8-11eb-8b43-467681a98c1d.png">

2. in map view, we should see the name and pills, top padding needs to shrink
![image0-2](https://user-images.githubusercontent.com/19331274/115619222-7836e100-a2a8-11eb-953b-b77f336f5094.png)

**Comment by PeterMain** [comment]
<img width="595" alt="Screenshot 2021-04-22 at 14 27 16" src="https://user-images.githubusercontent.com/3613880/115722400-dcc07180-a376-11eb-98a5-0d1f88e817f8.png">

Map has no location string

**Comment by PeterMain** [comment]
![IMG_FEDCC3150F42-1](https://user-images.githubusercontent.com/3613880/115722440-e944ca00-a376-11eb-84e5-13decc3e6682.jpeg)

tabs have unequal left/right padding
