### ISSUE TITLE
Custom antenna info does not save

### ISSUE THREAD

**Issue by dantheman5606** [helium/hotspot-app#507]
Updating Hotspot antenna and height does not take correct custom antenna info. If I set to custom, set dBi to 8 and height to 5 and click the Update Antenna button it shows all of the info as 1dBi and 0 Height.

**Comment by dantheman5606** [comment]
https://user-images.githubusercontent.com/7485237/115740494-18921180-a34c-11eb-82e9-df26248c50b3.mp4

**Comment by cokes518** [comment]
thanks for reporting. it will be fixed with this PR that's in review: https://github.com/helium/hotspot-app/pull/496

**Comment by tyler-whitman** [comment]
@dantheman5606 The bug with the code here is that you have to hit done on the keyboard for it to register the new data. This will be fixed in the next app update but a temporary solution is to hit done on the keyboard after changing the values.
