### ISSUE TITLE
make apps usable for screen readers and other assistive technology

### ISSUE THREAD

**Issue by jnurthen** [helium/hotspot-app#512]
The app is unusable when running with Voiceover & likely Talkback on android too (although I have not tested this). It looks like accessibility has not been considered during development. Folks who are blind or use other assistive technologies should to be able to  use the app.
React native accessibility information can be found at https://reactnative.dev/docs/accessibility - I've never implemented react native accessibility support myself but can help with many accessibility questions if you ping me.

To reproduce open the app, turn on voiceover then try to navigate around the page by swiping left and right. 

- Many controls also will not activate with a double tap (for example the switch controls in settings)
- Much of the UI is unreachable
- There are unlabeled controls
- Nothing has role information available

**Comment by cokes518** [comment]
Hi @jnurthen - thanks for filing this issue. We've had a start on adding accessibility to the app and will release what we've done thus far but it will not be fully featured until we get more help from the open source community. We're a small team, hope you understand.

**Comment by jnurthen** [comment]
@cokes518 should this have been closed? It doesn't look like it has been resolved.
