### ISSUE TITLE
Handle null onboarding key when adding hotspot

### ISSUE THREAD

**Issue by matthewcarlreetz** [helium/hotspot-app#529]
There occasionally seems to be a timing issue when onboarding hotspots where the onboarding key is null. Currently, the app will log the error `Hotspot connect failed: no onboardingKey` and [navigate](https://github.com/helium/hotspot-app/blob/main/src/features/hotspots/setup/HotspotSetupConnectingScreen.tsx#L46) to an Error screen. It seems we could have a better UX where the app will wait and retry or we could give the user the ability to manually retry?

**Comment by cokes518** [comment]
allow the user to retry.
