### ISSUE TITLE
Assert location issue

### ISSUE THREAD

**Issue by gurjeetseh** [helium/hotspot-app#530]
Recently I was learning about the helium app and looking into the update location but I didn’t completed the transaction for updating my miner location and just updated the antenna parameters. Now it is showing as assert location under activity(attached pics) and not participating in network. Please let me know what I can do to resolve the issue. The miner and antenna location is exact same as before and I have no intention to move it.

I even tried to pay and resolve the issue for location and antenna parameter update but nothing happened. I have also emailed Helium support but have not received any reply. Currently miner is not showing any activity and completely synced with blockchain.  

![Capture](https://user-images.githubusercontent.com/28228956/116740532-021e3280-a9aa-11eb-9f2d-eaa78e945208.PNG)

![IMG_7465](https://user-images.githubusercontent.com/28228956/116740149-773d3800-a9a9-11eb-91fd-f7942d497765.jpg)
![IMG_7466](https://user-images.githubusercontent.com/28228956/116740989-97b9c200-a9aa-11eb-953f-a97baff8798e.jpg)
![unnamed](https://user-images.githubusercontent.com/28228956/116740151-77d5ce80-a9a9-11eb-9c80-dbdacdb7d5e4.jpg)

**Comment by cokes518** [comment]
hi @gurjeetseh is this still happening?
