### ISSUE TITLE
List of antennas is cut at "RAK Antenna", no way to select anything below it

### ISSUE THREAD

**Issue by leppa** [helium/hotspot-app#531]
I was surprised to find out recently that, when updating antenna info, the list should have a custom antenna option. I have Sony Xperia XZ1 and the list ends on "RAK Antenna" for me (see the screenshot). There's no way to scroll down and select any item below the "RAK Antenna".

![Screenshot_20210502-205921](https://user-images.githubusercontent.com/857627/116824470-bd052680-ab8a-11eb-9a1d-c0b9e328c194.png)

**Comment by cokes518** [comment]
can confirm this happens on android if you set the font and display scale to a larger value than default.

**Comment by cokes518** [comment]
need to add a scroll bar.

**Comment by leppa** [comment]
> can confirm this happens on android if you set the font and display scale to a larger value than default.

Mine are on default, actually. If I set the display size to large, I can't even see the "Syncrob.it (EU 868)" option. On small I can see the "Custom Antenna", so works as a workaround for me. Thanks for the (indirect) suggestion.
