### ISSUE TITLE
Allow disco mode for unasserted Hotspots

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#540]
It'd be great if users can initiate discovery mode on an unasserted Hotspot, as a common use case is identifying ideal hotspot placement before setting a location and using up their free assert.

Without a hotspot location, we won't know what to show on the map. If we assume that the phone's location is where the Hotspot is, we can request location permissions and use the phone as proxy for the Hotspot and continue with disco mode.

User taps Disco Mode on an unasserted Hotspot > Begin Session
Show popup:
"Hotspot Does Not Have A Location"
"To visualize Hotspots that respond, we will use your phone's location as a placeholder for the Hotspot."
"Cancel | Continue"

When they hit Continue, request location permissions if we don't have them. If we have their location permission, continue with DM session and use their phone's location as the central point in the map.

**Comment by dioleev** [comment]
“To visualize Hotspots that respond, we will use your phone's location as a placeholder for the Hotspot.”

May I suggest to use layman’s terms like “To test connection with other hotspots [ACTION STEPS END-USER HAS TO TAKE]”. I believe this to be more user-friendly than tech jargon.
