### ISSUE TITLE
Disco Mode: Other error catches

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#545]
In addition to the router returning error = 1 (unable to dial hotspot), we should also preemptively want users that disco mode will not work if their hotspot is:

- [x] syncing
- [x] unasserted
- [x] offline
- [ ] freshly booted (packet forwarder has not had enough time to run)
- [x] relayed

On the syncing, we can probably query its block height. For Hotspots that are not synced, show a popup after they press **Discovery Mode**:

"Unable to initiate Discovery Mode"
"Hotspot must be fully synced, please try again later."
"OK"

Unasserted Hotspots - see other GH issue

Freshly Booted: not sure what we do to predict this, but if they get no responses, they can probably just try again.

Relayed - use the same logic that the Explorer has (check with DCJ). For Hotspots that are relayed, show a popup after they press **Discovery Mode**:

"Hotspot is Relayed"
"Relayed Hotspots running Discovery Mode may not receive responses from neighboring Hotspots. To take a Hotspot out of Relay, please visit the troubleshooting guide. https://intercom.help/heliumnetwork/en/articles/3207912-troubleshooting-network-connection-issues"
"Cancel | Continue"

If they press Continue, let them begin a DM session.

**Comment by matthewcarlreetz** [comment]
@allenan @tyler-whitman Any ideas how we can detect if a device is freshly booted (without a ble connect)?

**Comment by cokes518** [comment]
I'm not sure if that's something we can detect at all, which is why I left the comment above. This will likely need to be an education piece in a support article.
