### ISSUE TITLE
Hotspot diagnostic report for relayed status

### ISSUE THREAD

**Issue by niallkennedy** [helium/hotspot-app#553]
A hotspot owner should be able to diagnose possible issues causing the hotspot to be relayed from within the diagnostic report.

Currently a hotspot that displays as relayed in Explorer may show no issues with Outbound or Inbound Peer-to-Peer connections in the hotspot owner's Diagnostic Report. A report enhancement could display the most likely reasons a hotspot might be relayed, such as communication over specific ports, and the status of each possible relay reason.

A diagnostic report might show the hotspot was unable to send requests over TCP port 44158 for example, impacting hotspot health.

**Comment by cokes518** [comment]
While a good idea in theory, this feature request is more complicated than one would think. For now, we've opted to add a relayed button on Hotspots and that opens up the troubleshooting article to open ports. 

With the upcoming light hotspots, relayed Hotspots will no longer be a thing, and thus this work will be for naught.
