### ISSUE TITLE
Delayed Disco Mode session responder count

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#570]
A mod with disco mode reported that after running discovery mode, the responder count in his session history incremented. perhaps there were late responders from console/router?

just want to confirm that it's not a bug.

Can send hotspot name and wallet address over discord.

**Comment by matthewcarlreetz** [comment]
My guess is that there were late responders. There's nothing to stop responses after the 1 minute we display the map. Definitely send me any info you have and I'll dig into it.

**Comment by cokes518** [comment]
sounds like the fix will be a combo between router accepting delayed packets (up to 8s vs 400ms now), deployed today, and session duration will increase to 90s to capture late packets.
