### ISSUE TITLE
iOS app crashing when setting location

### ISSUE THREAD

**Issue by big-s-k-y** [helium/hotspot-app#576]
on iOs 14.5.1, app v3.1.3
-open app>add hotspot (+)>rak hotspot miner>skip for now>i understand>i'm powered up>scan>use ethernet instead>add location>set location>CRASH

**Comment by cokes518** [comment]
confirmed reproducible on iOS.

**Comment by cokes518** [comment]
also crashes on android 3.2.0

**Comment by cokes518** [comment]
The workaround for this is to Skip setting a location, and doing it after the onboarding flow.
