### ISSUE TITLE
Improved UX/UI for moving for asserting locations

### ISSUE THREAD

**Issue by maartenvanderhoef** [helium/hotspot-app#580]
Hi Team,
With multiple hotspots in a wallet, the bluetooth pair is not necesarily the current hotspot selected. This can lead to the issue that when moving the hotspot, it is not the paired hotspot but the selected one.  Although this is a 100% user error this can be prevented by a simple measure:
- Display Hotspot name in assert location screen and the final submit screen
- Display OLD and New Location in final screen ( not sure how this can fit on mobile though )
Thanks!

**Comment by cokes518** [comment]
pairing over bluetooth is not required to assert location, so users take an explicit action on a Hotspot they select, not one that is broadcasting over bluetooth.
