### ISSUE TITLE
Unable to pair with Hotspot - Onboarding Server Error message

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#593]
Many users are reporting that when trying to pair with the OG Hotspot or a RAK Hotspot, the app throws a message that says the Hotspot cannot be found in the Onboarding Server.

This check is not needed as all we want to do is talk to gateway-config and run diagnostics or update Wi-Fi.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/19331274/118870620-9c7fe080-b89b-11eb-97cf-fbebdcda0e4e.png">

**Comment by Ashtonpotter** [comment]
I get the same message as well. I started receiving it yesterday.
![IMG_3408](https://user-images.githubusercontent.com/16788074/118891944-fd67e280-b8b4-11eb-8463-2bdf9c0584df.PNG)

**Comment by tyler-whitman** [comment]
After investigation this is a blanket error catch when the hotspot fails to connect. Hotspots are failing to connect with the ongoing hotspot / mine issues and once those are resolved this should clear up.

I am updating the error message to better fit the case:
title: "Hotspot Pairing Failed"
message: "Hotspot Miner is unable to respond to requests. Please reboot the Hotspot and try again later."
