### ISSUE TITLE
Can't view details on non owned hotspots in helium app

### ISSUE THREAD

**Issue by techman05** [helium/hotspot-app#611]
I tried to select a white dot on the map and it didn't pull up the details like it does with my owned hotspots.

It got bigger to show I had selected it and the show witnesses seemed to work but no details.

Note was primarely doing this to check if any were relaying and to literaly see who the new fish in my area were.

**Comment by cokes518** [comment]
What app version and device are you using? I'm unable to reproduce.

screenshots?

**Comment by techman05** [comment]
3.2.1 on android. Is happening enough to annoy me. Next time I see the issue I'll take a screen shot.

**Comment by cokes518** [comment]
Checking in on this issue as well. Is it reproducible on 3.2.2?

**Comment by techman05** [comment]
I think you fixed something since it feels like its working better. I am trying to center the hotspot dots more in the center of the screen instead of where they are visibly on the map.
