### ISSUE TITLE
Cannot proceed past word generation when creating account

### ISSUE THREAD

**Issue by thecardcheat** [helium/hotspot-app#613]
After generating the 12 words, "I have written these down" is never enabled, so I cannot proceed.

Pixel 4a
Android 11

- Restarting the app has no effect
- Reinstalling the app has no effect

**Comment by cokes518** [comment]
Have you paused (count to 2 Mississippi) on every word before swiping to the next?

**Comment by thecardcheat** [comment]
@cokes518 I counted to 3 Mississippi and that did the trick. I guess I was recording them too quickly. Thanks for the tip.
