### ISSUE TITLE
Process for adding 3rd party gateways

### ISSUE THREAD

**Issue by shawaj** [helium/hotspot-app#62]
With the approval of HIP19 there is now a mechanism for new third party vendors of hotspots.

I wonder if we should either document the process for getting new manufacturers onboarded to the app, or perhaps cleaner/better would be to modify the RAKwireless one to be more generic for 3rd party gateways - that way we don't need to make changes to the app each time a new manufacturer is approved.

What do you think?

**Comment by shawaj** [comment]
cc @ryanteck @georgica

**Comment by cokes518** [comment]
We have the process outlined and looks like we're well on our way. closing this!
