### ISSUE TITLE
App converts 1,000 HNT and above to 1 HNT for transfers out of app

### ISSUE THREAD

**Issue by Axslinger75** [helium/hotspot-app#620]
App version 3.2.2 - Android 
Locale = USA

Steps to Reproduce : 
- Initiate a HNT transfer of 1,000 or more tokens
- Confirm the transfer

Expected Result : 
- HNT in the amount you entered is transferred successfully

Actual Result : 
- The app sends 1 HNT

Reproduced this twice on app version 3.2.2 sending HNT to bilaxy.

**Comment by tyler-whitman** [comment]
Thanks for the report, this was fixed with https://github.com/helium/hotspot-app/pull/616 and will be out in the next app release.

**Comment by Entaum** [comment]
Got the same issue here... but this also happens on Iphone App as well.

**Comment by cokes518** [comment]
fixed in 3.2.3
