### ISSUE TITLE
show elevation and gain

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#653]
for each hotspot, show the elevation and gain in the hotspot data object

**Comment by PeterMain** [comment]
<img width="874" alt="Screenshot 2021-06-18 at 09 06 18" src="https://user-images.githubusercontent.com/3613880/122528637-75403e80-d014-11eb-9c4f-49acde159690.png">

Would like to reserve pills for dynamic status, if possible. height/gain are info like location
