### ISSUE TITLE
Identify a Hotspot onboarded via QR code to hide bluetooth pairing menu

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#654]

**Comment by cokes518** [comment]
maybe update the copy in the bluetooth menu to say "some hotspot models not supported"

**Comment by shawaj** [comment]
Just wondering if there's a use case for a Bluetooth enabled hotspot to also use QR onboarding.

For example, we plan to have our dashboard / local diagnostics expose an onboarding QR but also still have BT so people have options.

So maybe this flag could be on the device itself or something attached to the model of the hotspot itself.

**Comment by cokes518** [comment]
Ideally the app makes none of the decisions and leave it up to the user to figure out what they want, which aligns with your comment.

Once they tap on a maker, the screen can be "pair via bluetooth or use the QR code", at which point they continue with the desired onboarding ux.

Once the Hotspot is onboarded, the Bluetooth pairing setting will always be there, but will state that not all Hotspot models are supported.
