### ISSUE TITLE
Unable to compile on Linux for Android

### ISSUE THREAD

**Issue by BenoitDuffez** [helium/hotspot-app#673]
I have copied the repo and checked out the feature branch `feature/498-qr_add_hotspot`.
I did `yarn install; yarn android` and obtained the following:

```
hotspot-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:55: error: package org.libsodium.rn does not exist
import org.libsodium.rn.RCTSodiumPackage;
                       ^
hotspot-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:123: error: cannot find symbol
      new RCTSodiumPackage(),
          ^
  symbol:   class RCTSodiumPackage
  location: class PackageList
```

This fails on Linux (Elementary OS, Ubuntu 18). The same works fine on a MacBook.

This is possibly a client issue, but I'm not sure what I did wrong? All the SDKs are up to date in Android Studio (same config for both the Linux laptop and the Mac laptop).
Is there any troubleshooting command that could help with it?

I did notice that the Mac build invoked CMake at some point, I'm assuming to build libsodium. I did not see any CMake invocation on Linux. I'm guessing that this is the root cause.

**Comment by BenoitDuffez** [comment]
What's the solution?

**Comment by a396901990** [comment]
same for me, any idea?
