### ISSUE TITLE
work through most common crashes on android

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#676]
https://play.google.com/console/u/1/developers/5847528771323009147/app/4972382363216562931/vitals/crashes?installedFrom=PLAY_STORE&days=30

specifically the bluetooth crashes that affects user onboarding.

**Comment by cascading-jox** [comment]
I can consistently crash the android app if I press the pair button on a hotspot and press "scan again" 5 times in a row. I'm on a pixel 2. Maybe it could be related to these bluetooth crashes?
