### ISSUE TITLE
Import existing seed phrase (new design)

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#69]

**Comment by cokes518** [comment]
@PeterMain dropping a note for you here as well. we need designs for importing the seed phrase.

**Comment by PeterMain** [comment]
any details for this @cokes518 ? I didn't see any info in Figma

**Comment by cokes518** [comment]
If you can replicate the existing flow in the old app with the new design, that’s all we need.

________________________________

**Comment by allenan** [comment]
If you go through importing a seed phrase in the new app, you'll see it uses some of the older design components

**Comment by matthewcarlreetz** [comment]
@PeterMain Any updates on this one?

**Comment by PeterMain** [comment]
I just went through the process, it seemed fine other that some styling - is that all we need @matthewcarlreetz or are we looking to change how it works? I'm not clear what the ask is

**Comment by PeterMain** [comment]
Got it. Will get something ready for tomorrow, but in the mean time getting all fonts -> Inter and sorting out colors to match app palette will get us 90% of the way there.

**Comment by PeterMain** [comment]
see 'import seed phrase' page in Figma
