### ISSUE TITLE
Cannot pay HNT to burn DC in Console from app running locale Dutch

### ISSUE THREAD

**Issue by pe1mew** [helium/hotspot-app#712]
**Describe the bug**
I cannot pay HNT to console to convert to DC to pay for data. I use the app V3,3,1 on Android

**To Reproduce**
Use App version V3.3.1 with Android and locale Dutch.

1. In Console follow the process to "purchase Data Credits",
2. enter the amount: eg. 1000000 DC
3. click "Burn to DC"
4. scan the QR-code
5. in App amount shows: "0,8097660: 
6. in app "Burn HNT" button is not highlighted and action cannot be finalized.  <- ERROR

**Expected behaviour**
I can burn HNT to my console account

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/11438883/122684184-438dca00-d204-11eb-80be-7d4dd70de63f.png)

![afbeelding](https://user-images.githubusercontent.com/11438883/122684172-2fe26380-d204-11eb-8894-5a64209213fb.png)

**Smartphone (please complete the following information):**

- Device: Samsung S7
- OS: Android 8.0.0
- App Version 3.3.1

**Additional context**
This error was reported earlier in relation to QR-codes

**Comment by cokes518** [comment]
hi @pe1mew this was actually an issue with the memo field and not i18n. this is fixed in app version 3.3.2.
