### ISSUE TITLE
Earned rewards screen Not available or 0.00 HNT on Wallet

### ISSUE THREAD

**Issue by robotron3k** [helium/hotspot-app#713]
Hi guys, I just set up my Rak miner, I have the latest software 3.3.1, Android Samsung S9.

I'm currently earning hnt and says so on the First tab, but Earnings tab says 0, and today the Earnings tab vanish completely. 

Please let me know how to correct. 

THANKS!

FYI, ALSO sent this through the support@helium.com 

![Screenshot_20210621-135345_Helium](https://user-images.githubusercontent.com/65085820/122809205-c877f280-d29b-11eb-8598-3f1923e48678.jpg)
![Screenshot_20210621-135335_Helium](https://user-images.githubusercontent.com/65085820/122809218-cb72e300-d29b-11eb-814a-086320831fe0.jpg)

**Comment by abhay** [comment]
Thanks for this report here, @robotron3k. We'll close the support email ticket since that's only for hardware support for original Helium Hotsots.

**Comment by cokes518** [comment]
hi @robotron3k are you the owner of the RAK Hotspot(i.e. purchased directly from calchip), or did you receive it from Emrit?

**Comment by robotron3k** [comment]
> hi @robotron3k are you the owner of the RAK Hotspot(i.e. purchased directly from calchip), or did you receive it from Emrit?

Hi Cokes518, I received the RAK from Emirit directly. what do you recommend?

**Comment by robotron3k** [comment]
> Thanks for this report here, @robotron3k. We'll close the support email ticket since that's only for hardware support for original Helium Hotsots.

Hello abhay, thanks for the reply. I understand. Do you have any recommendations for me for the Rak from Emirit?

**Comment by abhay** [comment]
> Hello abhay, thanks for the reply. I understand. Do you have any recommendations for me for the Rak from Emirit?

You'll have to talk to Emrit directly for support.
