### ISSUE TITLE
Disco Mode: Let users know that the only responder is themselves

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#723]
We made a decision earlier on to show "unable to initiate session" even if the only responder is the Hotspot itself. This creating some confusion so we should let them know that everything worked, but no one else heard them.

So instead of showing the error, we should show them the result with the Hotspot as a responder.

**Comment by matthewcarlreetz** [comment]
Currently, the only time the app shows "unable to initiate session" is when router throws an error. If the only responder is the hotspot itself, the app will just show "0 Responses".

Do we want to allow "self" as a responder for all hotspots?

**Comment by cokes518** [comment]
> Do we want to allow "self" as a responder for all hotspots?
yes
