### ISSUE TITLE
Unable to burn HNT

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#725]
Unable to scan QR code from console to burn HNT. The burn button is greyed out and not selectable.

Reproducible by community on 3.3.1 and me (on 3.3.2)

![IMG_CCC068EC78A3-1](https://user-images.githubusercontent.com/19331274/123304157-76b9ad00-d4d3-11eb-8739-343b450c14f4.jpeg)

**Comment by matthewcarlreetz** [comment]
@cokes518 It looks like the memo in the QR code is 4 characters too long to pass validation in the app.
