### ISSUE TITLE
"Share Results" button (discovery mode) unresponsive

### ISSUE THREAD

**Issue by JeremyCottontail** [helium/hotspot-app#738]
On iOS, the „share results“ button doesn't do anything, if the user has uninstalled default iOS Mail app. I am currently only using GMail app and deinstalled Apple's Mail app. After installing Apple's Mail app again, the „share results“ functionality worked again.

**Comment by cokes518** [comment]
We'll have a look to see if we can bring up a share sheet so you can select another mail app provider. but this is working as expected.
