### ISSUE TITLE
Failed transactions - invalid,bad_nonce

### ISSUE THREAD

**Issue by caseypugh** [helium/hotspot-app#741]
**Describe the bug**
I sent 8, separate transactions from a single wallet all to another wallet address. I sent them all immediately in a row, and only one of them succeeded. The other 7 failed and received the following error:
```
Failed Transaction
Unable to complete payment transaction to {address} for reason: {invalid,bad_nonce}.

Please try again.
```

**To Reproduce**

1. Open mobile app
2. Send multiple transactions in a row to same wallet
3. Wait a while for them to go through
4. Eventually you should see most of them failed

**Expected behavior**
I expect all the transactions to go through when sending multiple transactions in a row to the same wallet address. Seems like the mobile app isnt keep track of nonces very well?

**Screenshots**
<img src="https://user-images.githubusercontent.com/156097/123867445-5e46f980-d8fc-11eb-9327-558fe70a6a9c.png" width =250 />
<img src="https://user-images.githubusercontent.com/156097/123867420-571feb80-d8fc-11eb-9add-cc4cad65d3a7.png" width =250 />

**Smartphone:**
- Device: `iPhone XS`
- OS: `iOS 14.6`
- App Version `3.3.1`

**Comment by cokes518** [comment]
with the introduction of validators running the consensus group, block times and stability have greatly improved that should support multiple consecutive payment transactions without waiting for each to clear. 

it's recommended, however, that payments should be spaced out as nonces can be received out of order, which causes failed transactions.

**Comment by Pseudothink** [comment]
Same problem here, easily reproduced by sending multiple payments in a short time.  Would be nice to not need to wait for a payment to clear "pending" status, to proceed with a second.  Barring that, it'd be nice to get a configurable alert once pending transactions clear, so I could proceed with subsequent payments (or some other notification once it is safe to send another transaction without worrying about nonces being received out of order.)
![Screenshot_20210802-160048](https://user-images.githubusercontent.com/3343030/128070662-344bba15-d86d-47ba-b22e-d3a3d388d15a.png)
![Screenshot_20210803-115800](https://user-images.githubusercontent.com/3343030/128070664-9daa9726-a6e2-48e9-a7b6-f3c9cb0e2732.png)
![Screenshot_20210803-115812](https://user-images.githubusercontent.com/3343030/128070666-d76b8d77-4192-4a55-be87-55b3a5d1f554.png)
![Screenshot_20210803-122152](https://user-images.githubusercontent.com/3343030/128070668-383e9c2c-4b62-4c33-874f-42e776c27397.png)
![Screenshot_20210803-122200](https://user-images.githubusercontent.com/3343030/128070669-706c5c22-e884-4249-8e76-ea37f0e91905.png)
![Screenshot_20210803-122439](https://user-images.githubusercontent.com/3343030/128070671-860e8fdc-baf4-4954-82ba-5933052b9271.png)

**Comment by cokes518** [comment]
There might be something the blockchain can do better in processing these transactions (that is the ultimate root cause), so the core devs are going to start the investigation there. Not really a Hotspot App issue at the moment.
