### ISSUE TITLE
Notification Screen Redesign

### ISSUE THREAD

**Issue by tyler-whitman** [helium/hotspot-app#743]
Implement new designs for the notification screen.

![Screen Shot 2021-06-30 at 10 49 44 AM](https://user-images.githubusercontent.com/6345962/124008250-145c2300-d991-11eb-99b2-7e3debc9cd1c.png)

**Comment by cokes518** [comment]
As discussed in the meeting today:

- [ ] change sorting to new at top
- [ ] group by day and group by type, if on the same day
- [ ] add date next to type

<img width="306" alt="image" src="https://user-images.githubusercontent.com/19331274/124174407-2c9b7300-da61-11eb-9517-69c4a7fb157b.png">
