### ISSUE TITLE
QR code onboarding

### ISSUE THREAD

**Issue by x-logic-iot** [helium/hotspot-app#749]
**Describe the bug**
Added our gateway to the menu among other gateways (menu.PNG), but only if we add our gateway for the Bluetooth onboarding (bluetooth_onboarding.PNG). If we write the code as shown in the attachment image (qr_code_onboarding.PNG), the gateway doesn’t appear in the menu. Could you please guide us on adding the gateway via QR code onboarding? We have tried following the official Hotspot Integration guide but unfortunately haven’t found it enough informative. 

**To Reproduce**

1. Go to 'My hotspots'
2. Click on 'Set up Hotspot'
3. Scroll down to 'X-LOGIC Hotspot'
4.  Error - 'X-LOGIC Hotspot doesn't appear if added for the QR code onboarding'

**Expected behavior**
X-LOGIC Hotspot to appear as an option among other hotspots (when QR code onboarding is enabled).

**Screenshots**

Bluetooth onboarding
![bluetooth_onboarding](https://user-images.githubusercontent.com/85619906/124110579-ab47de80-da68-11eb-8415-eb683d3ea06d.PNG)

QR code onboarding
![qr_code_onboarding](https://user-images.githubusercontent.com/85619906/124110585-abe07500-da68-11eb-8eb5-1e5c1d68f3da.PNG)

Set up Hotspots menu (when Bluetooth onboarding is enabled)
![menu](https://user-images.githubusercontent.com/85619906/124110584-abe07500-da68-11eb-8067-07d3f55570b2.PNG)

**Smartphone (please complete the following information):**

- Device: Nexus 6 API 28
- App Version 3.3.2

**Additional context**
Application started with yarn android

**Comment by matthewcarlreetz** [comment]
We temporarily have QR onboarding guarded by a feature flag that is driven by the wallet api. We will need your wallet addresses in order to enable this feature for you. 

For a quick fix go to the file `src/store/features/featuresSlice.ts` and set qrOnboardEnabled to true (line 32) like so...
```ts
  state.qrOnboardEnabled = true
```

**Comment by cokes518** [comment]
@x-logic-iot it looks like you're still in the process with MOC. We'll wait until you're at the integration step before moving further.

**Comment by x-logic-iot** [comment]
@matthewcarlreetz  Thank you for your answer. I got to this screen after enabling the flag:

      state.qrOnboardEnabled = true

![SCANQR2](https://user-images.githubusercontent.com/85619906/124280570-22ed3a80-db49-11eb-83d0-77ca5b449709.PNG)

@cokes518 Could you please explain what do you mean by MOC? 

We are about to send our KYC/B procedure and following that we will send our gateway for the hardware audit. So, if my understanding is right, we need to send our gateway for the audit before integration with the mobile app?

**Comment by matthewcarlreetz** [comment]
@x-logic-iot the QR text needs to be a string not an array of strings. That changed and I haven’t updated the sample. Sorry about that.

**Comment by x-logic-iot** [comment]
@matthewcarlreetz It's not a problem. My QR text is a single string, am I missing something else?

![qrString](https://user-images.githubusercontent.com/85619906/124442734-531d1f00-dd7d-11eb-9966-76fc74321ed4.PNG)

**Comment by matthewcarlreetz** [comment]
@x-logic-iot  You need to remove the square brackets.
It should be 
```ts
qr: 'Visit x-logic.net/onboard...'
```

**Comment by x-logic-iot** [comment]
@matthewcarlreetz thank you for assistance, now it looks good. Could you please clarify, do we need to send our gateway for the hardware audit before integration with the mobile app? When exactly can we contact you to implement our gateway to your mobile app?

**Comment by cokes518** [comment]
@x-logic-iot please check in with Sophi from MOC. You are moving ahead out of order - hardware audit needs to conclude before anything on the mobile app can occur.

**Comment by x-logic-iot** [comment]
@cokes518 thank you for clearing this up. We will contact Sophi soon.
