### ISSUE TITLE
Relayout Activity Screen

### ISSUE THREAD

**Issue by matthewcarlreetz** [helium/hotspot-app#750]
https://www.figma.com/file/x07XtWRI573FfO8duPMIEz/3.4.0?node-id=1%3A121

![3 4 0 2021-07-01 at 11 14 02 AM](https://user-images.githubusercontent.com/1760821/124156617-75e9c380-da5d-11eb-9781-03c988040ad9.jpg)

**Comment by cokes518** [comment]
Start with top half of the UI:

- [ ] New send/receive icons
- [ ] Show DC, HST balance, show staked HNT balance, show liquid balance.
- [ ] introduce filters: All | Pending | Mining Rewards | Payments | Hotspot | Validators

For Mining Rewards: hotspot and validator rewards
For Payments: payment v1, v2, burn
For Hotspot: add, assert, transfer
For Validators: stake, unstake, transfer
