### ISSUE TITLE
Hotspot Details: Witness Tab

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#763]
- [x] blank state witnesses
- [x] witness list
- [ ] expanded witness list

Blank state:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/19331274/124823885-89e26900-df26-11eb-8b39-1e1862cc610d.png">

Witness List:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/19331274/124823943-9961b200-df26-11eb-990c-ee1fde67dc0f.png">

`450 m away` should be based on lat/long calculation on chain, not resolution distance.

Expanded Witness List:
Stretch goal

<img width="281" alt="image" src="https://user-images.githubusercontent.com/19331274/124824072-beeebb80-df26-11eb-8190-debe9e13ede9.png">

**Comment by tyler-whitman** [comment]
Should we split out the expanded witness view for now?
