### ISSUE TITLE
Comma button blocked for transfers, can't sending parts of HNT

### ISSUE THREAD

**Issue by Danski0** [helium/hotspot-app#765]
**Describe the bug**
When sending HNT it is not possible to add a comma for sending parts of HNT.

**To Reproduce**
1. Start a transcation
2. "Amount (HNT)" field has Comma button greyd out while the field instantly deletes Dots. Blocking sending anything other than whole HNT.

Could be a geo-problem as some countries use Comma (such as Sweden) instead of Dot as decimal-seperator.

**Screenshots**
![comma-bug](https://user-images.githubusercontent.com/2648089/125082119-1d52a000-e0c7-11eb-8aea-9b86e3cfc4ea.png)

**Smartphone:**
- Device: Samsung Galaxy S10
- OS: Android 11
- App Version: V3.3.2

**Additional context**
Workaround is using "send max" button and then changing numbers as this adds the comma successfully.

**Comment by tyler-whitman** [comment]
@Danski0 are you using the built in Samsung Keyboard? I think its a problem with that keyboard specifically, when I try it with German language on a Google keyboard it allows the `,`.

**Comment by tyler-whitman** [comment]
@Danski0 Another workaround for this problem is to get the Google Keyboard from the Playstore. We are working on fixing it in the app but if you are willing, thats one way to have it working correctly.
