### ISSUE TITLE
Introduce some type of notice about inconsistency with Disco Mode

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#770]
Router is still struggling and there's no ETA on improvements. To avoid confusion with those running discovery mode, we can add an interim popup that disco mode feature may be inconsistent while we improve backend infrastructure.

"Discovery Mode Performance"
"The backend service for Discovery Mode is experiencing performance issues and users may see inconsistent results."
"OK"

We'll show this popup once per **wallet** account, maximum 1x/day.

**Comment by matthewcarlreetz** [comment]
@cokes518 If a user is logged in on two separate devices, is it ok to show the error on both?

**Comment by cokes518** [comment]
Yes
________________________________
