### ISSUE TITLE
Android 3.4.0 App Performance

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#784]
User with 68 Hotspots:
LG V60 android
android 11. kernal 4.19.113

Says side swiping with shortcut nav is bad, app unusable.

User with 20 Hotspots
Samsung S20
He's sending me a video of performance.

**Comment by JayHNT-REN** [comment]
Upon logging in, app seems to pause for a few seconds. Hotspot list sometimes stops before loading entire list. When clicking on individual hotspot, clicking on any options at the bottom of app (both within the hotspot tab, as well as clicking on other tabs), clicking anything on the map, etc., a long delay occurs before any action (sometimes well over 1 minute). The app seems to pause during this - the scroll at the top stops.
