### ISSUE TITLE
Scanning payment QR code blanks screen

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#790]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/19331274/125859488-cb77901c-7dd2-4796-b0cb-f6b1c29796c9.png">

contents of QR
```{
  "type": "payment",
  "address": "13iupFgtU2HKy9Yndfq58CfBvzNFqGuVrEid1G3QWAMhBTjf1R1",
  "amount": 1
}
```

this looks well-constructed, and was working up until 1pm PST 7/15. I can reproduce, so we should be able to find logs.

**Comment by Bogardo** [comment]
I found out the issue with the above JSON structure. The `amount` **must** be a string.

This crashes the app:

```
{"type":"payment","address":"13iupFgtU2HKy9Yndfq58CfBvzNFqGuVrEid1G3QWAMhBTjf1R1", "amount": 1}
```

![image](https://user-images.githubusercontent.com/388557/125860355-f3e98923-2461-476d-845e-6daf81d918f1.png)


And this works
```
{"type":"payment","address":"13iupFgtU2HKy9Yndfq58CfBvzNFqGuVrEid1G3QWAMhBTjf1R1", "amount": "1"}
```

![image](https://user-images.githubusercontent.com/388557/125860418-c8335fb1-844b-411f-93d3-f33be839b314.png)
