### ISSUE TITLE
Transfer Wallet Button not working

### ISSUE THREAD

**Issue by domanjeremy** [helium/hotspot-app#804]
https://user-images.githubusercontent.com/30632726/126003166-25c270c5-9e4b-49e5-a55d-52a4cbca2867.MP4

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

**Additional context**

the app is up to date with version 3.4. The hotspot is fully synced and online. Both wallets have successfully transferred HNT to one another. The hotspot has not had an issue witnessing or sending a beacon

**Comment by cokes518** [comment]
confirmed that a sign out/sign in fixed the issue.
