### ISSUE TITLE
Serious issue with helium wallets

### ISSUE THREAD

**Issue by anukak** [helium/hotspot-app#806]
**Describe the bug**

**To Reproduce**
Here i sthe problem I faced

1) Created an account on iphone in Feb 2021
2) Saved all the sees work phrases in sequence
3) Ordered hotspot. Received July 15. Outdoor hotspot. Connected it thru POE and cat 6 cable
4) Using the wallet created in Feb activated hotspot
5) Re confirmed the 12 seed phrase words in the app and rechecked that I noted them down correctly in sequence
6) Hotspot name "skinny spruce panda"
7) Was connected and started syncing. Also showing up in the wallet in app
8) After verifying the seed phrases in the app, writing them down, I had to restart the app and reauthenticate
9) Reauthenticated using same seed phrases in same sequence
10) Got an error that no hotspot belong to this wallet
11) upon checking the wallet owner of this hotspot is 13jFu6VZnGE18PUhDUWyNBEgyQzPJCGCrnhj7AVSB2a8SsBWLn6 . Same location where I activated it.
12) My wallet ID shows up as 149jJeEARUbV1JymfqTcHhzNNBeESV5wn3RPK8UP5PSsBiPzajs
13) How it it possible that after verifying the seed phrases and entering them again in same order, the wallet ID has changed
14) It is my hotspot ordered from Nebra that I received in 15th July personally , activated using the helium app in a wallet 
15)Wrote down the seed phrases in same order
16)Logged in again using same seed phrases and find out that wallet id is different for the installed hotspot
17) This is clearly a bug in helium. 
18) It would be good to fix this problem so that I can start to manage my wallet. Thus far the hotspot has synced and is active but I can't manage it using the seed phrases that were used to set it up

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- Device:iphone 11
- OS: [e.g. iOS8.1] iOS 14.1
- App Version [e.g. 3.3.0]3.4.1

**Additional context**

**Comment by cokes518** [comment]
It looks like the seed phrase was written down incorrectly somehow. There is zero chance that the wallet will generate a different private/public key pair using the same 12 seed words.

**Comment by anukak** [comment]
Looks like bug is not in the protocol to create a wallet, but the way helium app created by helium.com handles and displays the 12 word phrases or the way association between the wallet and the  12 words is created and managed in helium.com repository.

Only after doubly verifying that "Reveal Words" shows the same  exact words that I had written down, I activated the hotspot in the account. After logging out, logged back in using same phrases that were written down. Have created one and only account. So not sure how this could happen. Seems like helium.com app has an issue that needs to be investigated. Maybe fraud is involved. Request you to reopen and investigate.

**Comment by avalanche08** [comment]
i have the same issue @cokes518 , I am very certain I used the same 12 words as I keep 2 back ups of it and cross compare. Just synced my hotspot 2 days ago and yesterday, I managed to log in and out of my wallet for the past 2 days for about 4 to 5 times using the exact 12 words and only yesterday afternoon, after trying again, the wallet is not the same anymore. Trust me, it's all EXACTLY THE SAME!!!. Otherwise, if not, you won't be able to log out anyway. You need to look into it, its not a joke to encounter that problem on that almost $600 device

**Comment by ghumanggg** [comment]
same thing happened with me. I entered seed phrase and it took to another account which does not show my miner and zero hnt balance.....I dont know  what is the reason

**Comment by ghumanggg** [comment]
> i have the same issue @cokes518 , I am very certain I used the same 12 words as I keep 2 back ups of it and cross compare. Just synced my hotspot 2 days ago and yesterday, I managed to log in and out of my wallet for the past 2 days for about 4 to 5 times using the exact 12 words and only yesterday afternoon, after trying again, the wallet is not the same anymore. Trust me, it's all EXACTLY THE SAME!!!. Otherwise, if not, you won't be able to log out anyway. You need to look into it, its not a joke to encounter that problem on that almost $600 device

yes ...same thing happened with me ......on 27 april 2022...it is taking me to another wallet address.

**Comment by Ryan-Goldstein** [comment]
The only way to get into the wrong wallet is by entering the wrong words. I have helped literally dozens who have reported the same thing, that they're 100% sure that they've entered the words correctly, only to realize later that one of the words was incorrect.

There are many very similar words on the list of valid words, such as cool/cook, use/used, swap/swamp, snack/snake, oven/over, price/prize, winner/winter, etc).

What I would recommend is comparing each word you think is correct with the valid word list [here](https://github.com/helium/helium-wallet-rs/blob/master/src/mnemonic/wordlists/english.txt), and swapping them with similar words that you may have written down incorrectly.

**Comment by dpappyp** [comment]
The wallet seems to displaying an incorrect seed phrase.  I tried importing it to other wallet apps and every one says it's invalid.  Yes, the words are correct, checked many times and retyped many times, wrong all the time
