### ISSUE TITLE
Updated Nebra onboarding instructions

### ISSUE THREAD

**Issue by shawaj** [helium/hotspot-app#810]
Need to update the onboarding instructions for Nebra hotspots in the app. Will work on a PR.

However, @cokes518 what's the process for updating the translations?

**Comment by cokes518** [comment]
@shawaj we send all files out for translation on a semi-regular cadence. so it will be done automatically for you.

**Comment by shawaj** [comment]
Oh amazing! That's nice and easy then 👍
