### ISSUE TITLE
Witness list on checklist gives both "pending" and "complete" messages at same time

### ISSUE THREAD

**Issue by shawaj** [helium/hotspot-app#817]
**Describe the bug**

Witness list on checklist gives both "pending" and "complete" messages at same time.

**To Reproduce**

Only seems to happen on certain hotspots in the app not on all of them

**Expected behavior**

Should show either pending or completed

**Screenshots**
![Screenshot_20210721-051821_Helium](https://user-images.githubusercontent.com/3359418/126430510-b37c448e-507d-4d55-a54b-cd4d43a34bd0.jpg)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S21 Ultra 5G
- OS: Android
- App Version 3.4.2

**Additional context**

**Comment by cokes518** [comment]
if it's still happening, can we get some hotspot names?

**Comment by shawaj** [comment]
@cokes518 sorry totally missed your message. think this was `zealous chocolate pike` but seems to have been fixed now anyway :-)
