### ISSUE TITLE
Withdraw amount displayed incorrectly

### ISSUE THREAD

**Issue by sb4223** [helium/hotspot-app#836]
**Describe the bug**
The withdraw amount on the right (in blue) being displayed it looks crunched over so it can’t display the full number compared to the inbound amount on the left (in green).

**To Reproduce**

1. Go to My wallet 
2. Click on Green or blue bar on all activity 

**Expected behavior**
The withdraw amount to be displayed properly like the deposit amount in green.

**Screenshots**
![E86EFF4C-048D-4FA9-B598-9CEB12A3BAB2](https://user-images.githubusercontent.com/87998011/127035830-c85e92c3-0dab-4d38-bd7f-e4bf1a336a3e.jpeg)

**Smartphone (please complete the following information):**

- Device: IPhone 12 Pro
- OS: IOS 14.7
- App Version 3.4.3

**Additional context**
None

**Comment by cokes518** [comment]
to fix: move the $credit / $debit to a new line.
