### ISSUE TITLE
Add fiat currency selector in settings

### ISSUE THREAD

**Issue by mabrodeur** [helium/hotspot-app#848]
**Describe the bug**
Currently, the app is using the phone's locale/country to choose which currency is displayed when the Convert HNT to Currency option is active.
This is a bad behavior because most of the time we cannot change the whole phone's locale to have a different currency in the app.
Ex: we want to display the value in USD but are in Canada, it would display in CAD. We cannot change the phone's locale otherwise the AppStore would not operate in the right country.

**To Reproduce**

1. Go to Settings
2. Scroll down and activate Convert HNT to Currency
3. Notice that the currency is displayed in your phone's locale/country (which is not US) when you want it to be seen in USD.

**Expected behavior**
Have a list of currencies to convert to instead of using the phone's locale/country.

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: iOS 14.6
- App Version 3.4.3

**Additional context**
Tag: improvement more than a bug.
I saw a lot of people asking for this feature in a few Discord servers.

**Comment by mabrodeur** [comment]
I am well aware of that feature. But I don't think this is the good way to do it and a lot of users are asking for a fix for this.
It's not because your phone is in a language/locale that you want the currency to always be fixed to that local.

For example: USD is a currency that is used everywhere but you cannot see the USD value of the coin if you are not located in the US or if your phone is not set to English US.

I don't think it would be really hard to add a dropdown list for the wanted currency instead of always using the phone's locale.

I think it would be a really useful improvement to the app.

**Comment by cokes518** [comment]
fair point. what I think we can do is add a dropdown to select the currencies that coin gecko supports, that will override the locale if you choose to view the dollar value.

**Comment by mabrodeur** [comment]
That would be great yes!

**Comment by cokes518** [comment]
Per coin gecko, supported fiat currencies: 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/19331274/128090501-2f53afd3-8e49-4a6b-a5dc-9d7f452ba165.png">

In the App > Settings, under Convert HNT to Currency, add a currency picker, sorted alphabetically. When a user selects a currency here, it will override the default locale-selected currency.

**Comment by cokes518** [comment]
assigning to @mabrodeur based on conversation in #hotspot-app-development channel.

**Comment by matthewcarlreetz** [comment]
> Per coin gecko, supported fiat currencies: <img alt="image" width="665" src="https://user-images.githubusercontent.com/19331274/128090501-2f53afd3-8e49-4a6b-a5dc-9d7f452ba165.png">
> 
> In the App > Settings, under Convert HNT to Currency, add a currency picker, sorted alphabetically. When a user selects a currency here, it will override the default locale-selected currency.

@cokes518 Where did you find the list of supported currencies? I'm not seeing the Euro on this list. I would think that should be on here?
