### ISSUE TITLE
Location assert immediately after antenna update reverts antenna information

### ISSUE THREAD

**Issue by EdBallou** [helium/hotspot-app#866]
**Describe the bug**
When doing a location assert just after an antenna update, it clears out the antenna information that was set previously. Please note, this was separated by 4 blocks between actions.

**To Reproduce**

Please note I have attempted to replicate this as I believe it should be able to be tested easily on TestNet which I don't have access to.
1. Update antenna information (from default to non-default)
2. Submit to blockchain
3. Assert new location (in my example, it ended up being 4 blocks later)
4. Submit to blockchain
5. Look up hotspot details
6. Antenna info has reverted to default values

**Expected behavior**
The antenna information that I updated should remain through the location assert.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone8
- OS: Windows/Chrome
- App Version: latest

**Additional context**
I noticed it's the same on explorer as well. So whether in the app or in a browser, it shows the block transactions the same. So it appears like it's an issue with the app. I don't believe I closed the app or anything. I performed the two actions sequentially.

**Comment by cokes518** [comment]
what does the information say in the API? api.helium.io/v1/hotspots/:hotspotaddress

**Comment by EdBallou** [comment]
> what does the information say in the API? api.helium.io/v1/hotspots/:hotspotaddress

gain: 12,
elevation: 0,

**Comment by cokes518** [comment]
Did the location update from the second transaction?

What was the original gain/elevation in the first transaction?

**Comment by EdBallou** [comment]
Yep, location is correct.

So the order I did it in...

1. Original location assert (long time ago), never set the antenna location
2. Antenna update to 8m with 8 gain just recently
3. location assert to new location (4 blocks later)
4. antenna info shows as 0m and 1.2 gain

**Comment by jameses986** [comment]
I am also having trouble asserting new antenna info in the Helium app.
Original setup: first location, 3 dbi antenna, 4m height.  No issues inserting all this information.
Recently revised location: new location asserted with no issues, antenna height to 44m with no issues, but antenna field is not able to be edited.  It is reading out as 3.0 dbi with no option to change.
Miner is Nebra Outdoor Hotspot.
Using app on iPhone 7 with app version v3.4.3

I would like to update antenna specs, but the bottom line question is... Does it matter to the algorithms or mining functionality to set antenna specs?

**Comment by EdBallou** [comment]
@jameses986 - I think your questions are awesome and sound like cokes' reply in Discord that this whole space is being rethought. 

As far as I'm aware, the data is being used to assist in building rewards v3 and therefore, not relevant to current calculations/functionality but I could be wrong here.

**Comment by cokes518** [comment]
this issue is pretty stale now. however, in 3.9.0 we re-fixed an issue on assert that looks up existing data on the API to prevent reverting data, if you haven't changed it. please reopen a new issue if this is still happening.
