### ISSUE TITLE
Selecting Location tab in Hotspot Settings fails when there is no asserted location

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#867]
Steps to reproduce:
1. Add a Hotspot using the onboarding flow
2. Set a location later
3. go to Hotspot details, tap settings
4. Tap Update Settings
5. select Update Location tab
6. crash

Has happened to several users on Android, iOS but the devs are unable to reproduce. Will wait for more crash logs to come through to see if we can dig deeper.

**Comment by cokes518** [comment]
seems like an update to 3.4.4 has resolved the issue for at least 1 user. will keep monitoring and close when enough people have confirmed it's fixed.

**Comment by nickhel** [comment]
I use iOS 14.4 (iPhone 7). 
I have Helium app version 3.4.5.
Three miners (syncrobit) are linked to my wallet. 
2 miners are up and running with locations asserted. 
I skipped the location assertion for the 3rd one while deciding where to install it. Now the Helium app just shuts down without any warning or error message. I go to the hotspot's settings and select "Update Hotspot". Under options I click on update location button on the left and the app closes immediately.
