### ISSUE TITLE
Diagnostics show 100% even though block height is still far away from current block

### ISSUE THREAD

**Issue by LilaQ** [helium/hotspot-app#871]
When connecting to a hotspot, the diagnostics show 100% even though the hotspot can still be +1000 blocks away from the current block. Not sure if the current block is old data at that moment, or if there is bad rounding in place. This will give users the impression that their hotspots are fully synced, when they are not.

**Comment by cokes518** [comment]
That UI is likely using the 1500 block buffer and so if it's below 1500 blocks away, it'll say it's synced. Let me look into how we can make this better.

**Comment by cokes518** [comment]
diagnostic report now shows block height and not a percentage in 3.9.0
