### ISSUE TITLE
"Send Report to Support" on iOS works only for default Mail app

### ISSUE THREAD

**Issue by LilaQ** [helium/hotspot-app#872]
**Describe the bug**
When trying to send diagnostics over "Send Report to Support" button, the iOS app won't budge if you haven't set Apple's mail app for the default mail app (which a lot of people haven't) - suspecting an deprecated mailto call here.

**To Reproduce**
Use iPhone. Set e.g. GMail app for default mail app. Open Helium app, connect via BT, diagnostics, push "Send Report to Support", see nothing happen

**Expected behavior**
Mail app should open, no matter which one is set as default by the user.

**Smartphone (please complete the following information):**

- iPhone 12, iOS 14.2.1

**Comment by cokes518** [comment]
this is as designed and restricted by apple. closing as won't fix.
