### ISSUE TITLE
hotspot transfer doesnt work

### ISSUE THREAD

**Issue by rokasrr** [helium/hotspot-app#873]
1. Go to '...' Hotspot transfer
2. Click on '....' Input buyer address and clicking send transfer request
4. no error, but it doesnt work, button is active, but doesnt work.

- Device: [e.g. iPhone6] Huawei P20
- OS: [e.g. iOS8.1] Lastest
- App Version [e.g. 3.3.0] Latest 2021-08-07

**Comment by cokes518** [comment]
Is this still happening? Can you provide the name of the Hotspot you're trying to transfer so we can investigate?

**Comment by cokes518** [comment]
closing this for now. if it still happens, please open a new issue.
