### ISSUE TITLE
Activity Types for app wallet screen

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#90]
Activity Detail Cards

- [x] payment v1
- [ ] payment v2
- [x] receive HNT
- [x] burn HNT
- [x] transfer Hotspot
- [x] pending transactions
- [x] add hotspot
- [x] assert location
- [x] mining rewards

Old App Screens as FYI:
**Transfer Hotspot: seller**
<img width="266" alt="image" src="https://user-images.githubusercontent.com/19331274/104509242-3e19bd00-559e-11eb-88c9-10f32181736c.png">
**Transfer Hotspot: buyer**
<img width="230" alt="image" src="https://user-images.githubusercontent.com/19331274/104509274-4b36ac00-559e-11eb-90e2-99c476634ffb.png">
**Burn HNT**
<img width="282" alt="image" src="https://user-images.githubusercontent.com/19331274/104509338-643f5d00-559e-11eb-8fe2-bfbc135d3162.png">
**Payment_v2**
<img width="226" alt="image" src="https://user-images.githubusercontent.com/19331274/104509401-77522d00-559e-11eb-9f45-1a5d4e08ff6e.png">

**Comment by PeterMain** [comment]
What exactly is happening on payment _v2 there? multiple recipients?

**Comment by cokes518** [comment]
Transaction hash to go in the kebab
