### ISSUE TITLE
Onboarding more than one Hotspot in a row can throw "This Hotspot is already onboarded" error

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#902]
Users pairing multiple hotspots in a row:

First onboarding completes without issue. when pairing 2nd hotspot, they select 2nd hotspot in bluetooth list, but first hotspot is used to construct add_gateway transaction and then get the error “this hotspot is already onboarded”.

App must be storing some state in memory, because this can be resolved by completely closing the app and unplugging other hotspots.

We should check out:
- is the app actually pairing with hotspot2 on the bluetooth screen?
- is the app using the onboarding address of hotspot1 in the add_gateway transaction?

**Comment by shawaj** [comment]
@ap on Discord mentioned this to us before as well. #636 looks like. Have reproduced on our side too. If you need any further info let me know :-)

**Comment by cokes518** [comment]
@shawaj bobcat was able to resolve this issue. turns out their hotspots were not advertising a unique ID. perhaps that's the same issue with nebras?

**Comment by Zoko1989** [comment]
Did this bug have a fix? Im having the same issue now. Onboarded 3 of 4 indoor units, 2 work fine, 1 is 'internal server error', the other is 'currently unavailable' on the nebra dashboard.

On the helium app, 3 are onboarded and 1 is 'you already own this hotspot'

I have tried restarting hotspots separately several time, reinstalling helium app several times.

Thanks
