### ISSUE TITLE
Mobile app hangs on mapping far mis-asserted HS

### ISSUE THREAD

**Issue by wolfenhawke** [helium/hotspot-app#909]
**Describe the bug**
The mobile app hangs and must be killed and restarted to continue. Symptom seems to be wrong assertion by witness.

**To Reproduce**

1. Open app and pick a hotspot that has been witness by a wrong asserted far away hotspot.
2. Select Witnesses, scroll through (don't need to see the wrong asserted hotspot, but it should be there)
3. Select map filter to show "Witnesses", accept
3. Map will zoom out to extent of world required to show all witnesses
4. possible error conditions:
- map will hang after a few seconds
- map will hang while zooming in on a location (may still be time based)

**Expected behavior**
Map and application should not hang.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone11
- OS: iOS14.7.1
- App Version v3.4.7

**Additional context**
Have been seeing this problem for about 3 days. Now other hotspots in the vicinity of this mis-asserted HS are seeing it and my app hangs when I open them up too. This behavior is replicable.

![IMG_4510](https://user-images.githubusercontent.com/12172960/130678530-26ef6529-e30b-40d6-8ff3-2570292eeb9d.PNG)
-- suspicious asserted hotspot in witnesses that is 4280Km away

![IMG_4511](https://user-images.githubusercontent.com/12172960/130678573-64db35be-d852-4eb4-bc73-7221c5c983ab.PNG)
-- selecting Witnesses, map filter

![IMG_4512](https://user-images.githubusercontent.com/12172960/130678600-8663e501-2e83-4dcc-b930-18503bb64cc8.PNG)
-- app map view zoomed out, app is still operational

![IMG_4513](https://user-images.githubusercontent.com/12172960/130678621-5b5a69b0-833d-4793-863a-d61d0c731f1f.PNG)
--- app is hung

**Comment by cokes518** [comment]
I can reproduce with hotspot Eager Scarlet Skunk. The issue is likely root cause to the map rendering all the Hotspots in its witness list that is extremely far away.
