### ISSUE TITLE
RE : One Helium Account with two helium wallet addresses

### ISSUE THREAD

**Issue by calvindick** [helium/hotspot-app#916]
**Describe the bug**

Around 4 months ago I deposited 175 HNT into my daughters helium account. I set up this account and have the 12 words. When I checked the wallet last week the 175 was missing. I then went onto my wallet and found that the wallet address had changed. I thought this was not possible.

I then went onto a different device loaded up an account with the existing 12 words and was able to restore the original account.

So these 12 words for one account have two different wallet addresses on two different devices. Wallet addresses are 

 13BG5iLTAwPPyRLxACPTwPf7epnXUL5PNKaUkX9SB3WrycHBfUf Original Wallet Address

13N5wQX43XzbK1z5DSGFGfsLdp859MkHiZdXhZ9ExVgd8zEHkuH New Wallet Address

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

**Additional context**

**Comment by cokes518** [comment]
closing for staleness. make sure your 12 words are entered correctly and in the same order.
