### ISSUE TITLE
Helium App keeps crashing at Bluetooth pairing

### ISSUE THREAD

**Issue by aelyacho** [helium/hotspot-app#917]
**Describe the bug**
I am trying to pair my android phone with my hotspot in order to change the internet settings but everytime I click on the pair button in the hotspot settings, the app crashes.

**To Reproduce**

1. Go to your hotspot and click on settings at the right top corner
2. Click on pair Bluetooth
3. The app crashes.

**Expected behavior**
By clicking on the pair button, the app is supposed to show me all available hotspots to which I can connect.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: OnePlus 6
- OS: Android 10
- App Version 3.4.7

**Comment by aelyacho** [comment]
Additional information: Yes, I tried to delete the cache and even uninstalled and reinstalled the app but the bug keeps persisting.

**Comment by cokes518** [comment]
hi @aelyacho who made your hotspot? are you able to select the hotspot name from the list, and *then* it crashes?

**Comment by aelyacho** [comment]
Hi, it started working again right now. I reinstalled the app twice and rebooted twice and nothing changed after that, but it just got fixed right now on its own. Thanks for your fast reply tho! The hotspot is the Sensecap M1 from Seeedstudio and no, I was not able to select the hotspot. The app was crashing right after clicking on the pair button.
