### ISSUE TITLE
Summary Page does not include validators

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#931]
as part of validator support, we were to include Validators as part of the Home page summary
"Your x Hotspots earned y HNT"
"Your x Validators and y Hotspots earned z HNT"
"Your x Validators earned y HNT"

This doesn't seem to be the case.
![IMG_4B4C7CB74E1B-1](https://user-images.githubusercontent.com/19331274/132395090-1a2a41a9-5195-4ec3-a773-0370b20e1686.jpeg)

**Comment by matthewcarlreetz** [comment]
I just tested this out and it appears to be working for me. Is it still an issue for you @cokes518?
![IMG_2B857A8F9D0D-1](https://user-images.githubusercontent.com/1760821/134008349-1efef797-1054-487f-8910-188d126b21c1.jpeg)
