### ISSUE TITLE
Add warning if payment being sent to new or hotspot/validator address

### ISSUE THREAD

**Issue by heliumredbeard** [helium/hotspot-app#935]
To help prevent sending HNT to an incorrect wallet, detect if the payee does not exist or is a hotspot/validator address, and show a warning/confirmation screen.  Suggested text:

"The Payee address does not yet exist, or looks like a Hotspot.  Do you want to proceed?"

**Comment by cokes518** [comment]
In the validation we should show red text above the "Send HNT" button that says
"Not a valid Helium Wallet Address" and disable the Send HNT button.
