### ISSUE TITLE
The correct order integrating QR code onboarding for maker？

### ISSUE THREAD

**Issue by FTwOoO** [helium/hotspot-app#941]
Open Helium-app, scan the QR code, the qr code content is like string:
```
helium://add_gateway/{txn}
```
then the txn is signed by wallet and then commit to helium, **if the owner field of txn must equal to 
then wallet address**(is it right?), to generate the txn before QR code generated, must run the miner command in gateway:

```shell
sudo docker exec miner miner txn add_gateway owner={ownerAddress} --payer {payerAddress}
===> 
{txn}
```

Based on what I said above, I think, if i(maker) want to integrate QR code onboarding:

1. folk and add add directory to src/makers/ of https://github.com/helium/hotspot-app, add files including hotspots.ts like https://github.com/helium/hotspot-app/blob/main/src/makers/clodpi/hotspots.ts, which contains lines:
```
  onboardType: 'QR',
  onboardUrl: 'https://xxxx.xyz/dashboard',
```

2. build the App to apk, then install App on my phone
3. open the App, select the hotspot item which added in step 1
4. clieck the website(URL is onboardUrl) to open a dashboard developed by maker
5. enter the hotspot productId/macId or other unique ID which uniquely identifies the hotspot, and enter the Helium-App `wallet  address`
6. then, the website notify the gateway through the connection from hotspot to maker's backend, the hotspot run the command which generate `{txn}` using Helium-App `wallet address` as ownerAddress and the payerAddress
7. the website generate a QR code with string `helium://add_gateway/{txn}`
8. using the Helium-App to scan the QR code, and the process the txn, signed by the wallet acccout, commit to the helium blockchain.

Question:
* Is the onborading process above correct?
* the owner field of txn must equal to wallet address who want to add the hotspot ?
* Can the QR code be affixed to the product during hotspot production?
* onboardUrl in hotspots.ts must be required?

**Comment by cokes518** [comment]
Are you a maker applying under the HIP19 process?

**Comment by cappuccino5** [comment]
> Are you a maker applying under the HIP19 process?

yeh, #941 Question What is the development process like

**Comment by cokes518** [comment]
please direct these questions to your designated maker channel. thanks for understanding.
