### ISSUE TITLE
Unable to update antenna dbi or height, black screen

### ISSUE THREAD

**Issue by drusau** [helium/hotspot-app#957]
**Describe the bug**
I have set up a hotspot, everything is working as it should. I upgraded the antenna and raised the hotspot to a higher location. I go to “update hotspot” in the app, then I go to “update antenna.” Hotspot setting is set to sensecap M1 @ antenna dbi 2.6. I select “custom antenna.” The default dbi is 1.0 if I do not change anything and select “update antenna” then I am taken to a conformation page and can pay the fee and complete the update. If I try to change the values for TX/RX Gain or Height then when I click “done” the screen goes black and I cannot complete the update. I have to start over and it does the same thing every time. I look at my settings and the antenna does not update. So I am unable to change the height and cannot update my custom antenna to any other dbi other than 1.0. So the problem (black screen) happens after the fields are changed in the TX/RX gain and/or Height. 

**To Reproduce**

1. Go to hotspot and select “hotspot settings”
2. Click on 'update hotspot’
3. Click on ‘select antenna’
4. Click on ‘custom antenna’
5. Click on ‘TX/RX gain’
6. Click on ‘1.0 dBi’ and change value
7. And or Click on ‘height’ and change value 
7. Click on ‘update antenna’ or ‘Done’
8. Screen becomes black with only option to go ‘back’ or ‘X’ out of window. 

**Expected behavior**
I expect to see the screen with the 55,000 charge and conformation screen, instead screen turns black. 

**Screenshots**

![0B5B1F24-E3AA-49F6-AE87-274ED03D4114](https://user-images.githubusercontent.com/42974023/134944095-d1ebefdc-614a-4848-8ca3-119092193c77.png)
![4C0726ED-06EC-4451-B762-8DA2B58ECEBC](https://user-images.githubusercontent.com/42974023/134944100-d00a769f-f21a-403d-889a-a12e6e545778.png)

**Smartphone (please complete the following information):**

Replicated this on two devices
- Device: [iPhone se 2nd generation]
- OS: [iOS14.8]
- App Version [3.5.0]
- Device: [iPad Pro 12.9inch 3rd generation]
- OS: [iOS 14.6]
- App Version [3.5.0]

**Additional context**

My hotspot is Sensecap M1. I also connected a Bluetooth keyboard and so the number pad disappears and I am able to select “update antenna” instead of “done” and I still get the same result, a black screen.

**Comment by cokes518** [comment]
do you have a location set on the hotspot?

**Comment by cokes518** [comment]
we're unable to reproduce on our side. if you can give us your hotspot name, we can investigate further.

**Comment by drusau** [comment]
I have this problem with both my hotspots. My main hotspot is Witty Caramel Hare and Flat Chocolate Boa.

Yes I have the location set on the two hotspots. 

I have a video of this happening but I cannot send it because the file exceeds the size limit for ***@***.***



Thanks for looking into this.
Andrew

**Comment by cokes518** [comment]
we can't reproduce at all. can you try again on 3.6.0?

**Comment by drusau** [comment]
I just reproduced it. Here is a link to see what I experience. 

https://share.icloud.com/photos/0yjdBNKngm6NWR8wLoKIhzigA#Home

Andrew

Send from myphone ;(D

**Comment by drusau** [comment]
Any update? Did you see the video? Any hotspot that has already been allocated to a location I cannot update either. I tried moving one today and cannot update the location or custom antenna.

**Comment by drusau** [comment]
USA. Also the first time I set up a hotspot I can chose custom antenna and height no problem. But to update location or height or dbi I have the same problem. 

Send from myphone ;(D

**Comment by dkang17** [comment]
I've had this issue every since this came out as well.

Device: [iPhone 12 mini]
OS: [iOS15.1]
App Version [3.7.1]
Hotspot: Original Helium Hotspot

**Comment by cokes518** [comment]
is this issue still happening?

**Comment by drusau** [comment]
Yes on my iPhone. But I used my friend’s android and got everything updated. 

Send from myphone ;(D
