### ISSUE TITLE
Hotspot app wrong location assertion

### ISSUE THREAD

**Issue by jurajpe** [helium/hotspot-app#962]
**Describe the bug**
The location of the hotspot is asserted in a incorrect location
**To Reproduce**

1. Go to 'settings' 'update hotspot'
2. Click on 'update location'
3. Tap 'change location'
4. See error: the error occurs after this step. In the location window you place your hotspot correctly and press continue, on the next window where you should confirm the change it is still the same map same location. It is the final confirmation page where the bug happens. Here in this window the location is not correct and is OFF to what you chose in the previous steps. The image is very small in this window so easy to not to spot it. Also the google coordinates are wrong. If you choose to go back,the location at the previous window is correct. You have to cheat in the location window to compensate foe the error.  

**Expected behavior**
I would expect the location as I chose it to be exactly where it will be shown in the confirmation window!

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [iphone se 2020]
- OS: [e.g. iOS14.7.1]
- App Version [e.g. 3.6.0]

**Additional context**
Happened to me and some other users.
It would seem that the coordinate system in the user variable space, so the first map where I can move it. Is not aligned with the confirmation window coordinate system. 
Some deviation to real world is acceptable of course, but it should be spot on in the app for the assertion process.
Also the final confirmation window is small and you cannot really see if it is correct.

**Comment by cokes518** [comment]
what is the lat/long coordinates of what you selected in the app, and the lat/long coordinates on the API?

**Comment by cokes518** [comment]
we may have found the issue where on the last page of the assert screen, where the Submit button appears, the pointer is slightly off on the map. This describes what you're saying in that the map is super tiny on that screen.

However, once you've asserted, the coordinates should be close (snapped to the nearest res 12, then extrapolated up to res 8 for explorer and app) to the original selection. Can you confirm this is the case?
