### ISSUE TITLE
Transferred miner pending

### ISSUE THREAD

**Issue by ProfessorHtx** [helium/hotspot-app#967]
I purchased a miner and it was transferred into my wallet. The seller sent the request twice now it shows 1 is pending. I've attempted to cancel, accept with no success. The seller deleted his app and no longer has seed phrase. Its been 6 days and request hasn't canceled.See screen shots of helium app.
![Screenshot_20211010-230311_Helium](https://user-images.githubusercontent.com/92286280/136732334-171249e9-d17e-42e5-98da-356f9273d635.jpg)
![Screenshot_20211010-230327_Helium](https://user-images.githubusercontent.com/92286280/136732348-e4542887-6237-4074-ad11-a857196a9f21.jpg)
![Screenshot_20211010-230405_Helium](https://user-images.githubusercontent.com/92286280/136732352-0c90df45-b080-4ea2-bf0b-f767fa19fad7.jpg)

**Comment by cokes518** [comment]
the seller will need to sign back into his account, cancel the transfer request, and try again. do you see the notification in your app?

**Comment by ProfessorHtx** [comment]
No luck on that. I'll see if he can find phrase.

**Comment by ProfessorHtx** [comment]
Tried it and no luck the seller was able to locate phrase and its not in his wallet nor pending.

**Comment by ProfessorHtx** [comment]
![Screenshot_20211018-130147_Helium](https://user-images.githubusercontent.com/92286280/137783669-32c67719-cef7-43cb-b238-171bc6bcdecf.jpg)

**Comment by cokes518** [comment]
we cleared the transaction from a table. please check again?

**Comment by ProfessorHtx** [comment]
Cleared thanks.

**Comment by PapRIkaNL** [comment]
@cokes518 Hello, I have found this thread because I have the **exact** same issue.  Nobody can help me on Discord or Telegram. The hotspot I bought is Polished Grape Ferret, it works and I have full access, but still the transaction is pending and the buyer can't help me. If the issue is the same, can you also clear the database table please?

**Comment by Krachbummente1992** [comment]
Hello @cokes518 , i have also the exact same problem from yesterday at the time the network was instable.  I bought a Hotspot called "Sneaky Beige Chipmunk" and it is still Pending. It would be great if you can help me. Thanks a lot

**Comment by Matixas26** [comment]
@cokes518 Have the same problem. I have the miner mining for me but it says the transaction is pending and I can't cancel it. The hotspot name is "Bumpy Mango Elephant"

**Comment by ionumrginean** [comment]
@cokes518 Hi! I have the same problem. Zealous Lavender Wombat is the name of the miner. Can you help me, please?
Thank you!

**Comment by Ricktang77** [comment]
Hi , I have the same problem , my miner “ Winning Lenon Capybara “. Says it’s pending transfer , but I am unable to cancel or get rid of that message .  The hotspot is currently in my wallet.  Can you help me please . 
![79668CDA-A837-4DE1-BE6D-20D8797759BB](https://user-images.githubusercontent.com/97934342/149875101-f1d4613c-c7b6-40c0-8a76-e8125102390a.png)
![632CF790-3D70-487A-A7B3-D98B92C56AF4](https://user-images.githubusercontent.com/97934342/149875110-daa87242-e096-49a0-b419-eb0954135f2b.png)
![DA93AE72-5F2D-4C34-B7E3-4AE469FBD3DE](https://user-images.githubusercontent.com/97934342/149875115-fac3555b-4990-45c5-8e30-5e94f3466a78.png)

**Comment by cosmindut** [comment]
Hello guys, I have the same problem, I am trying to transfer a hotspot over two weeks. What can I do?🙏

**Comment by 65bert73** [comment]
Same issue here. All Activities have status Pending. Seven pending activities, what is wrong here? Should I remove and reinstall the app to resolve this issue? Who can help us to resolve this??
