### ISSUE TITLE
HNT inaccessable after transfering hotspot

### ISSUE THREAD

**Issue by Ubiquitous** [helium/hotspot-app#968]
I transferred a hotspot to another wallet (which already had an existing hotspot). The transfer worked, although when I open the helium app and login to the previous wallet the balance says $0. 

When I view the balance of the destination wallet (which now contains two hotspots) it only shows the balance of the existing hotspot. 

On the explorer I can see the previous wallet address with the balance it has in it, although I'm not sure how to access the HNT in it now because the app says $0 and zero hotspots for that same address.

**EDIT:** I tried accessing the previous wallet via the iOS simulator and was able to see the HNT balance within the wallet. It's unclear why the balance shows zero on the actual physical device.

**Comment by cokes518** [comment]
Closing for lack of information. Please file a new issue if this persists.
