### ISSUE TITLE
Hotspot asserted in different location than shown in app

### ISSUE THREAD

**Issue by capjbadger007** [helium/hotspot-app#969]
**Description**
When user asserts a hotspot location, sometimes the hotspot is actually placed far away from the location the user asserted.
This is not a display issue or a "snap to res12" issue. See attached image. The assert in this case is 70m or ~ten res12 hexes away from the user selected location. 

**Steps To Reproduce**
1. Begin process to assert hotspot in the app
2. Manually move map to place pin
3. Confirm location (app still shows user chosen location)

**Expected Results**
Hotspot is asserted to center of user selected res12 hex.

**Actual Results**
When asserted location is checked on something like Hotspotty or Helium Vision, hotspot location is not in the spot shown in the app when the assert was confirmed.

**Screenshots**

![asserts](https://user-images.githubusercontent.com/87449898/137080642-6a172b19-731b-439f-ade8-711a096b49cd.jpg)

**Smartphone (please complete the following information):**

- Device: All devices
- OS: NA
- App Version: NA

**Additional context**
This has been reported in the helium discord multiple times over the last few weeks.
Little-Steel-Fly

**Comment by CreamyG31337** [comment]
this always happens. you can tell when you try to set the location to whatever, the confirmation screen already shows a different spot. then the final confirmation gives yet another location. sometimes I keep re-doing this until the final location seems close enough, other times I just give up.

**Comment by waveform06** [comment]
> this always happens. you can tell when you try to set the location to whatever, the confirmation screen already shows a different spot. then the final confirmation gives yet another location. sometimes I keep re-doing this until the final location seems close enough, other times I just give up.

Happened to me several times too. On occasion I even picked the Res 12 I wanted to be in using  https://tak2siva.github.io/ and I was asserted a few Res12s away.

**Comment by Rickster20** [comment]
Same thing happened to me this past week. The actual dot does not appear to be accurate, but the street name did change. 🤷‍♂️ So, I’m not sure if this is par for the course or it its going to cause issues. Any response or feedback/suggestions from folks at Helium?

**Comment by JohnMacrae** [comment]
I too have encountered this bug. It always seems to move north by about 200m - enough to move me to wrong hex. Had to pay to revert it to correct location
