### ISSUE TITLE
iOS helium app crashing until reboot.

### ISSUE THREAD

**Issue by enorym** [helium/hotspot-app#979]
**Describe the bug**
Keeps crashing until I reboot

**To Reproduce**

1. Launch app
2. Hope it works
3. Crashes
4. Reboot

**Expected behavior**
App work?

**Screenshots**
![image](https://user-images.githubusercontent.com/32758728/137662784-af3970f3-53be-4701-9c6c-6f4bf35b0ddb.jpeg)

![image](https://user-images.githubusercontent.com/32758728/137662833-2f3870be-9766-40c4-a585-723018ae9117.png)

![image](https://user-images.githubusercontent.com/32758728/137662845-88846c71-2f7c-4f7e-a312-6c0161cf88ab.png)

![Uploading 137662851...]

**Comment by ryny24** [comment]
Crashing for me too. Android on OnePlus 8 Pro.
