### ISSUE TITLE
App still says syncing and relayed after 48+ hours after earning rewards and fully synced

### ISSUE THREAD

**Issue by Lupi619** [helium/hotspot-app#982]
**Describe the bug**
App still says I'm syncing and relayed, after 48 hours of being synced and getting rewards according to the diagnostics within the app. Also the helium explorer says I'm synced and earning rewards.  I've already had 3 witnesses and received rewards, that is confirmed on the explorer as well as within the app. Under progress it says syncing to blockchain and transfer data is pending. 
The port 44158 is confirmed and open.   I even installed the app on both an iPhone and an Android imported my wallet but same thing.  I cannot even try to use the discovery mode because it claims it is still syncing.  It has been at least 48 hours since my 1st reward and 1st challenge created.  

**To Reproduce**
just use the app as normal on a new MNTD Rakwireless Miner. 

1. Go to 'App, and select miner'

**Expected behavior**
I'm expecting the app and Helium explorer to be in sync or at least have the app give more detail of what is going on.  Most people in discords seem to say that this is normal behavior for the app which is odd after 48 hours. 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone6s, and Samsung s9
- OS: iOS 15.0.2 and Android 10
- App Version 3.6.0

**Additional context**

**Comment by cokes518** [comment]
This is a result of peer-to-peer gossip on the network taking a long time to proliferate information about Hotspots. As this is a decentralized network, there's no centralized source of information until the network gossips the sync and relay status across the network of over 270,000 Hotspots.

both the app and explorer relies on API data that is eventually gossiped to them.
