### ISSUE TITLE
App wasn't responding and Wallet Showing ZERO (0) Balance after re-install

### ISSUE THREAD

**Issue by rakesh2906** [helium/hotspot-app#997]
**Describe the bug**
Am using IOS 15 version , My helium App dint open until I re-install it. 
Once I opened my App , My wallet showing 0 balance . I have X amount of HNT before I re-install the app.

**Smartphone (please complete the following information):**

- Device: [e.g. IPhone 12 Pro]
- OS: [15.0.2]
- App Version [e.g. 3.3.0]

**Comment by somar1989** [comment]
I’m having issues with the app also
